Repository OCA/hr, pull requests merged in 2018-12, with the labels that each got.

#495 [12.0][MIG] hr_employee_social_media
  hr_employee_social_media/README.rst
  hr_employee_social_media/__init__.py
  hr_employee_social_media/__manifest__.py
  hr_employee_social_media/data/social_media.xml
  hr_employee_social_media/i18n/ar.po
  hr_employee_social_media/i18n/cs_CZ.po
  hr_employee_social_media/i18n/de.po
  hr_employee_social_media/i18n/es.po
  hr_employee_social_media/i18n/fi.po
  hr_employee_social_media/i18n/fr.po
  hr_employee_social_media/i18n/hr.po
  hr_employee_social_media/i18n/hr_HR.po
  hr_employee_social_media/i18n/hr_employee_social_media.pot
  hr_employee_social_media/i18n/it.po
  hr_employee_social_media/i18n/lt.po
  hr_employee_social_media/i18n/nl_NL.po
  hr_employee_social_media/i18n/pl.po
  hr_employee_social_media/i18n/pt_BR.po
  hr_employee_social_media/i18n/ro.po
  hr_employee_social_media/i18n/sl.po
  hr_employee_social_media/models/__init__.py
  hr_employee_social_media/models/hr_employee.py
  hr_employee_social_media/models/hr_social_media.py
  hr_employee_social_media/readme/CONTRIBUTORS.rst
  hr_employee_social_media/readme/DESCRIPTION.rst
  hr_employee_social_media/security/ir.model.access.csv
  hr_employee_social_media/static/description/icon.png
  hr_employee_social_media/static/description/index.html
  hr_employee_social_media/views/hr_employee_view.xml
  hr_employee_social_media/views/hr_social_media.xml
Labels: approved, needs review, ready to merge

#523 [IMP] hr_skill 11.0.2.0.0
  hr_attendance_rfid/readme/CONFIGURE.rst
  hr_attendance_rfid/readme/CONTRIBUTORS.rst
  hr_attendance_rfid/readme/DESCRIPTION.rst
  hr_attendance_rfid/readme/USAGE.rst
  hr_payslip_change_state/__manifest__.py
  hr_skill/README.rst
  hr_skill/__manifest__.py
  hr_skill/migrations/11.0.2.0.0/post-migrate.py
  hr_skill/models/__init__.py
  hr_skill/models/hr_employee.py
  hr_skill/models/hr_employee_skill.py
  hr_skill/models/hr_skill.py
  hr_skill/readme/CONFIGURATION.rst
  hr_skill/readme/CONTRIBUTORS.rst
  hr_skill/readme/CREDITS.rst
  hr_skill/readme/DESCRIPTION.rst
  hr_skill/readme/USAGE.rst
  hr_skill/security/ir.model.access.csv
  hr_skill/views/hr_employee.xml
  hr_skill/views/hr_employee_skill.xml
  hr_skill/views/hr_skill.xml
Labels: approved, needs review

#522 hr_expense_analytic_tag: New module
  hr_expense_analytic_tag/README.rst
  hr_expense_analytic_tag/__init__.py
  hr_expense_analytic_tag/__manifest__.py
  hr_expense_analytic_tag/models/__init__.py
  hr_expense_analytic_tag/models/hr_expense.py
  hr_expense_analytic_tag/readme/CONTRIBUTORS.rst
  hr_expense_analytic_tag/readme/DESCRIPTION.rst
  hr_expense_analytic_tag/readme/USAGE.rst
  hr_expense_analytic_tag/static/description/index.html
  hr_expense_analytic_tag/tests/__init__.py
  hr_expense_analytic_tag/tests/test_hr_expense_analytic_tag.py
  hr_expense_analytic_tag/views/hr_expense_sheet_views.xml
  hr_expense_analytic_tag/views/hr_expense_views.xml
Labels: approved, needs review

#525 [MIG] hr_expense_invoice: Migration to 11.0
  hr_expense_invoice/README.rst
  hr_expense_invoice/__init__.py
  hr_expense_invoice/__manifest__.py
  hr_expense_invoice/i18n/cs_CZ.po
  hr_expense_invoice/i18n/es.po
  hr_expense_invoice/i18n/fr.po
  hr_expense_invoice/i18n/hr.po
  hr_expense_invoice/i18n/hr_expense_invoice.pot
  hr_expense_invoice/i18n/nl_NL.po
  hr_expense_invoice/i18n/pt.po
  hr_expense_invoice/models/__init__.py
  hr_expense_invoice/models/hr_expense.py
  hr_expense_invoice/models/hr_expense_sheet.py
  hr_expense_invoice/readme/CONTRIBUTORS.rst
  hr_expense_invoice/readme/DESCRIPTION.rst
  hr_expense_invoice/readme/ROADMAP.rst
  hr_expense_invoice/readme/USAGE.rst
  hr_expense_invoice/static/description/icon.png
  hr_expense_invoice/static/description/index.html
  hr_expense_invoice/tests/__init__.py
  hr_expense_invoice/tests/test_hr_expense_invoice.py
  hr_expense_invoice/views/hr_expense_views.xml
Labels: needs review

#529 [IMP] Add uniqueness constraint
  hr_skill/models/hr_employee_skill.py
Labels: approved, enhancement, needs review

#530 [IMP] Skill view
  hr_skill/__manifest__.py
  hr_skill/views/hr_skill.xml
Labels: approved, needs review
