Repository OCA/hr, pull requests merged in 2018-11, with the labels that each got.

#488 [12.0][MIG] hr_employee_id
  hr_employee_id/README.rst
  hr_employee_id/__init__.py
  hr_employee_id/__manifest__.py
  hr_employee_id/data/hr_employee_sequence.xml
  hr_employee_id/i18n/ar.po
  hr_employee_id/i18n/cs_CZ.po
  hr_employee_id/i18n/de.po
  hr_employee_id/i18n/es.po
  hr_employee_id/i18n/fi.po
  hr_employee_id/i18n/fr.po
  hr_employee_id/i18n/hr.po
  hr_employee_id/i18n/hr_HR.po
  hr_employee_id/i18n/hr_employee_id.pot
  hr_employee_id/i18n/it.po
  hr_employee_id/i18n/lt.po
  hr_employee_id/i18n/nl_NL.po
  hr_employee_id/i18n/pt_BR.po
  hr_employee_id/i18n/ro.po
  hr_employee_id/i18n/sl.po
  hr_employee_id/models/__init__.py
  hr_employee_id/models/hr_employee.py
  hr_employee_id/models/res_company.py
  hr_employee_id/models/res_config_settings.py
  hr_employee_id/readme/CONFIGURE.rst
  hr_employee_id/readme/CONTRIBUTORS.rst
  hr_employee_id/readme/DESCRIPTION.rst
  hr_employee_id/readme/INSTALL.rst
  hr_employee_id/readme/ROADMAP.rst
  hr_employee_id/readme/USAGE.rst
  hr_employee_id/static/description/index.html
  hr_employee_id/tests/__init__.py
  hr_employee_id/tests/test_employee_id.py
  hr_employee_id/views/hr_employee_views.xml
  hr_employee_id/views/res_config_settings_views.xml
Labels: needs review

#489 [12.0][ADD] hr_employee_relatives: alternative to hr_family
  hr_employee_relative/README.rst
  hr_employee_relative/__init__.py
  hr_employee_relative/__manifest__.py
  hr_employee_relative/data/data_relative_relation.xml
  hr_employee_relative/models/__init__.py
  hr_employee_relative/models/hr_employee.py
  hr_employee_relative/models/hr_employee_relative.py
  hr_employee_relative/models/hr_employee_relative_relation.py
  hr_employee_relative/readme/CONTRIBUTORS.rst
  hr_employee_relative/readme/DESCRIPTION.rst
  hr_employee_relative/security/ir.model.access.csv
  hr_employee_relative/static/description/index.html
  hr_employee_relative/tests/__init__.py
  hr_employee_relative/tests/test_hr_employee_relatives.py
  hr_employee_relative/views/hr_employee.xml
  hr_employee_relative/views/hr_employee_relative.xml
Labels: approved, ready to merge

#421 [ADD] hr_attendance_report_theoretical_time
  .travis.yml
  hr_attendance_report_theoretical_time/README.rst
  hr_attendance_report_theoretical_time/__init__.py
  hr_attendance_report_theoretical_time/__manifest__.py
  hr_attendance_report_theoretical_time/i18n/es.po
  hr_attendance_report_theoretical_time/i18n/hr_attendance_report_theoretical_time.pot
  hr_attendance_report_theoretical_time/models/__init__.py
  hr_attendance_report_theoretical_time/models/hr_attendance.py
  hr_attendance_report_theoretical_time/models/hr_employee.py
  hr_attendance_report_theoretical_time/models/hr_holidays.py
  hr_attendance_report_theoretical_time/models/hr_holidays_public.py
  hr_attendance_report_theoretical_time/models/hr_holidays_status.py
  hr_attendance_report_theoretical_time/readme/CONFIGURE.rst
  hr_attendance_report_theoretical_time/readme/CONTRIBUTORS.rst
  hr_attendance_report_theoretical_time/readme/CREDITS.rst
  hr_attendance_report_theoretical_time/readme/DESCRIPTION.rst
  hr_attendance_report_theoretical_time/readme/INSTALL.rst
  hr_attendance_report_theoretical_time/readme/ROADMAP.rst
  hr_attendance_report_theoretical_time/readme/USAGE.rst
  hr_attendance_report_theoretical_time/reports/__init__.py
  hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report.py
  hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report_views.xml
  hr_attendance_report_theoretical_time/security/hr_attendance_report_theoretical_time_security.xml
  hr_attendance_report_theoretical_time/security/ir.model.access.csv
  hr_attendance_report_theoretical_time/static/description/icon.png
  hr_attendance_report_theoretical_time/static/description/icon.svg
  hr_attendance_report_theoretical_time/static/description/index.html
  hr_attendance_report_theoretical_time/tests/__init__.py
  hr_attendance_report_theoretical_time/tests/test_hr_attendance_report_theoretical_time.py
  hr_attendance_report_theoretical_time/views/hr_employee_views.xml
  hr_attendance_report_theoretical_time/views/hr_holidays_status_views.xml
Labels: approved, needs review, ready to merge

#502 [12.0][ADD] hr_employee_service: employee service information & duration
  hr_employee_service/README.rst
  hr_employee_service/__init__.py
  hr_employee_service/__manifest__.py
  hr_employee_service/models/__init__.py
  hr_employee_service/models/hr_employee.py
  hr_employee_service/readme/CONTRIBUTORS.rst
  hr_employee_service/readme/DESCRIPTION.rst
  hr_employee_service/static/description/index.html
  hr_employee_service/tests/__init__.py
  hr_employee_service/tests/test_hr_employee_service.py
  hr_employee_service/views/hr_employee.xml
Labels: approved, ready to merge

#478 hr_holidays_hour: fix HrHolidaysRemainingLeavesUser VIEW query
  hr_holidays_hour/report/hr_holidays_report.py
Labels: approved

#494 [12.0][ADD] hr_employee_document: documents attached to the employee profile
  hr_employee_document/README.rst
  hr_employee_document/__init__.py
  hr_employee_document/__manifest__.py
  hr_employee_document/models/__init__.py
  hr_employee_document/models/hr_employee.py
  hr_employee_document/readme/CONTRIBUTORS.rst
  hr_employee_document/readme/DESCRIPTION.rst
  hr_employee_document/static/description/index.html
  hr_employee_document/tests/__init__.py
  hr_employee_document/tests/test_hr_employee_document.py
  hr_employee_document/views/hr_employee.xml
Labels: approved, ready to merge
