Repository OCA/hr, pull requests merged in 2019-05, with the labels that each got.

#561 [10.0] [ADD] hr_citizenship: create module
  hr_citizenship/README.rst
  hr_citizenship/__init__.py
  hr_citizenship/__manifest__.py
  hr_citizenship/models/__init__.py
  hr_citizenship/models/hr_applicant.py
  hr_citizenship/models/hr_employee.py
  hr_citizenship/models/res_citizenship.py
  hr_citizenship/readme/CONTRIBUTORS.rst
  hr_citizenship/readme/DESCRIPTION.rst
  hr_citizenship/security/ir.model.access.csv
  hr_citizenship/security/res_groups.xml
  hr_citizenship/static/description/icon.png
  hr_citizenship/static/description/index.html
  hr_citizenship/tests/__init__.py
  hr_citizenship/tests/test_citizenship.py
  hr_citizenship/views/hr_applicant.xml
  hr_citizenship/views/hr_employee.xml
Labels: approved, ready to merge

#482 [MIG] hr_contract_multi_job: Migration from v11 to v12
  hr_contract_multi_job/README.rst
  hr_contract_multi_job/__init__.py
  hr_contract_multi_job/__manifest__.py
  hr_contract_multi_job/i18n/ar.po
  hr_contract_multi_job/i18n/de.po
  hr_contract_multi_job/i18n/es.po
  hr_contract_multi_job/i18n/fi.po
  hr_contract_multi_job/i18n/fr.po
  hr_contract_multi_job/i18n/it.po
  hr_contract_multi_job/i18n/pt_BR.po
  hr_contract_multi_job/i18n/ro.po
  hr_contract_multi_job/i18n/sl.po
  hr_contract_multi_job/models/__init__.py
  hr_contract_multi_job/models/hr_contract.py
  hr_contract_multi_job/models/hr_contract_job.py
  hr_contract_multi_job/models/hr_job.py
  hr_contract_multi_job/readme/CONTRIBUTORS.rst
  hr_contract_multi_job/readme/DESCRIPTION.rst
  hr_contract_multi_job/readme/INSTALL.rst
  hr_contract_multi_job/readme/USAGE.rst
  hr_contract_multi_job/security/ir.model.access.csv
  hr_contract_multi_job/static/description/icon.png
  hr_contract_multi_job/tests/__init__.py
  hr_contract_multi_job/tests/test_hr_contract_multi_jobs.py
  hr_contract_multi_job/views/hr_contract_view.xml
Labels: needs review

#583 [11.0][FIX/IMP] hr_employee_firstname: make required attributes dynamic
  hr_employee_firstname/README.rst
  hr_employee_firstname/__manifest__.py
  hr_employee_firstname/models/hr_employee.py
  hr_employee_firstname/tests/test_hr_employee_firstname.py
  hr_employee_firstname/views/hr_view.xml
Labels: approved

#590 [FIX] hr_holidays_public: Traceback when change the date was fixed
  hr_holidays_public/models/hr_holidays_public.py
  hr_holidays_public/views/hr_holidays_public_view.xml
Labels: approved, needs review

#587 [MIG][11.0] hr attendance reason
  hr_attendance_reason/README.rst
  hr_attendance_reason/__init__.py
  hr_attendance_reason/__manifest__.py
  hr_attendance_reason/data/hr_attendance_reason_data.xml
  hr_attendance_reason/i18n/hr_attendance_reason.pot
  hr_attendance_reason/models/__init__.py
  hr_attendance_reason/models/hr_attendance.py
  hr_attendance_reason/models/hr_attendance_reason.py
  hr_attendance_reason/readme/CONTRIBUTORS.rst
  hr_attendance_reason/readme/DESCRIPTION.rst
  hr_attendance_reason/readme/USAGE.rst
  hr_attendance_reason/security/ir.model.access.csv
  hr_attendance_reason/static/description/index.html
  hr_attendance_reason/tests/__init__.py
  hr_attendance_reason/tests/test_hr_attendance_reason.py
  hr_attendance_reason/views/hr_attendance_reason_view.xml
  hr_attendance_reason/views/hr_attendance_view.xml
Labels: approved

#584 [12.0][MIG] hr_expense_invoice
  hr_expense_invoice/README.rst
  hr_expense_invoice/__init__.py
  hr_expense_invoice/__manifest__.py
  hr_expense_invoice/i18n/cs_CZ.po
  hr_expense_invoice/i18n/de.po
  hr_expense_invoice/i18n/es.po
  hr_expense_invoice/i18n/fr.po
  hr_expense_invoice/i18n/hr.po
  hr_expense_invoice/i18n/hr_expense_invoice.pot
  hr_expense_invoice/i18n/nl_NL.po
  hr_expense_invoice/i18n/pt.po
  hr_expense_invoice/models/__init__.py
  hr_expense_invoice/models/hr_expense.py
  hr_expense_invoice/models/hr_expense_sheet.py
  hr_expense_invoice/readme/CONTRIBUTORS.rst
  hr_expense_invoice/readme/DESCRIPTION.rst
  hr_expense_invoice/readme/ROADMAP.rst
  hr_expense_invoice/readme/USAGE.rst
  hr_expense_invoice/static/description/icon.png
  hr_expense_invoice/static/description/index.html
  hr_expense_invoice/tests/__init__.py
  hr_expense_invoice/tests/test_hr_expense_invoice.py
  hr_expense_invoice/views/hr_expense_views.xml
Labels: approved, ready to merge

#592 [11.0][MIG] hr_employee_display_own_info
  hr_employee_display_own_info/README.rst
  hr_employee_display_own_info/__init__.py
  hr_employee_display_own_info/__manifest__.py
  hr_employee_display_own_info/i18n/hr_employee_display_own_info.pot
  hr_employee_display_own_info/models/__init__.py
  hr_employee_display_own_info/models/hr_employee.py
  hr_employee_display_own_info/readme/CONTRIBUTORS.rst
  hr_employee_display_own_info/readme/DESCRIPTION.rst
  hr_employee_display_own_info/static/description/icon.png
  hr_employee_display_own_info/static/description/index.html
  hr_employee_display_own_info/tests/__init__.py
  hr_employee_display_own_info/tests/test_employee_display_own_info.py
  hr_employee_display_own_info/views/hr_employee.xml
Labels: approved, ready to merge

#589 [MIG][11.0] hr_employee_seniority
  hr_employee_seniority/README.rst
  hr_employee_seniority/__init__.py
  hr_employee_seniority/__manifest__.py
  hr_employee_seniority/i18n/ar.po
  hr_employee_seniority/i18n/cs_CZ.po
  hr_employee_seniority/i18n/de.po
  hr_employee_seniority/i18n/es.po
  hr_employee_seniority/i18n/fi.po
  hr_employee_seniority/i18n/fr.po
  hr_employee_seniority/i18n/hr.po
  hr_employee_seniority/i18n/hr_HR.po
  hr_employee_seniority/i18n/hr_employee_seniority.pot
  hr_employee_seniority/i18n/it.po
  hr_employee_seniority/i18n/lt.po
  hr_employee_seniority/i18n/nl_NL.po
  hr_employee_seniority/i18n/pt_BR.po
  hr_employee_seniority/i18n/ro.po
  hr_employee_seniority/i18n/sl.po
  hr_employee_seniority/models/__init__.py
  hr_employee_seniority/models/hr_employee.py
  hr_employee_seniority/readme/CONTRIBUTORS.rst
  hr_employee_seniority/readme/DESCRIPTION.rst
  hr_employee_seniority/tests/__init__.py
  hr_employee_seniority/tests/test_employee_seniority.py
  hr_employee_seniority/views/employee_views.xml
Labels: approved, ready to merge

#567 [ADD] hr_attendance_modification_tracking
  hr_attendance_modification_tracking/README.rst
  hr_attendance_modification_tracking/__init__.py
  hr_attendance_modification_tracking/__manifest__.py
  hr_attendance_modification_tracking/models/__init__.py
  hr_attendance_modification_tracking/models/hr_attendance.py
  hr_attendance_modification_tracking/readme/CONTRIBUTORS.rst
  hr_attendance_modification_tracking/readme/DESCRIPTION.rst
  hr_attendance_modification_tracking/static/description/icon.png
  hr_attendance_modification_tracking/static/description/index.html
  hr_attendance_modification_tracking/views/hr_attendance_view.xml
Labels: approved, ready to merge

#595 [IMP] holidays_public: Return Intervals with holiday lines
  hr_holidays_public/__manifest__.py
  hr_holidays_public/models/resource.py
Labels: approved

#501 [12.0][ADD] hr_holidays_accrual_advanced: Advanced accrual leave allocations
  hr_holidays_accrual_advanced/README.rst
  hr_holidays_accrual_advanced/__init__.py
  hr_holidays_accrual_advanced/__manifest__.py
  hr_holidays_accrual_advanced/models/__init__.py
  hr_holidays_accrual_advanced/models/hr_leave.py
  hr_holidays_accrual_advanced/models/hr_leave_allocation.py
  hr_holidays_accrual_advanced/models/hr_leave_allocation_accruement.py
  hr_holidays_accrual_advanced/models/resource_calendar_leaves.py
  hr_holidays_accrual_advanced/readme/CONTRIBUTORS.rst
  hr_holidays_accrual_advanced/readme/DESCRIPTION.rst
  hr_holidays_accrual_advanced/readme/ROADMAP.rst
  hr_holidays_accrual_advanced/readme/USAGE.rst
  hr_holidays_accrual_advanced/security/hr_holidays_accrual_security.xml
  hr_holidays_accrual_advanced/security/ir.model.access.csv
  hr_holidays_accrual_advanced/static/description/index.html
  hr_holidays_accrual_advanced/tests/__init__.py
  hr_holidays_accrual_advanced/tests/test_hr_holidays_accrual_advanced.py
  hr_holidays_accrual_advanced/views/hr_leave_allocation.xml
  hr_holidays_accrual_advanced/views/hr_leave_allocation_accruement.xml
  hr_holidays_accrual_advanced/wizards/__init__.py
  hr_holidays_accrual_advanced/wizards/hr_leave_allocation_accrual_calculator.py
  hr_holidays_accrual_advanced/wizards/hr_leave_allocation_accrual_calculator.xml
Labels: needs review

#571 [11.0] [MIG] hr_employee_calendar_planning
  hr_employee_calendar_planning/README.rst
  hr_employee_calendar_planning/__init__.py
  hr_employee_calendar_planning/__manifest__.py
  hr_employee_calendar_planning/hooks.py
  hr_employee_calendar_planning/i18n/hr_employee_calendar_planning.pot
  hr_employee_calendar_planning/models/__init__.py
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/models/resource_calendar.py
  hr_employee_calendar_planning/readme/CONFIGURE.rst
  hr_employee_calendar_planning/readme/CONTRIBUTORS.rst
  hr_employee_calendar_planning/readme/DESCRIPTION.rst
  hr_employee_calendar_planning/readme/INSTALL.rst
  hr_employee_calendar_planning/readme/ROADMAP.rst
  hr_employee_calendar_planning/security/ir.model.access.csv
  hr_employee_calendar_planning/static/description/index.html
  hr_employee_calendar_planning/tests/__init__.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
  hr_employee_calendar_planning/views/hr_employee_views.xml
Labels: approved, ready to merge

#591 [MIG][11.0] hr_attendance_autoclose
  hr_attendance_autoclose/README.rst
  hr_attendance_autoclose/__init__.py
  hr_attendance_autoclose/__manifest__.py
  hr_attendance_autoclose/data/hr_attendance.xml
  hr_attendance_autoclose/data/hr_attendance_reason.xml
  hr_attendance_autoclose/i18n/hr_attendance_autoclose.pot
  hr_attendance_autoclose/models/__init__.py
  hr_attendance_autoclose/models/hr_attendance.py
  hr_attendance_autoclose/models/res_company.py
  hr_attendance_autoclose/readme/CONTRIBUTORS.rst
  hr_attendance_autoclose/readme/DESCRIPTION.rst
  hr_attendance_autoclose/readme/USAGE.rst
  hr_attendance_autoclose/static/description/index.html
  hr_attendance_autoclose/tests/__init__.py
  hr_attendance_autoclose/tests/test_hr_attendance_auto_close.py
  hr_attendance_autoclose/views/hr_attendance_view.xml
  hr_attendance_autoclose/views/res_company_view.xml
Labels: approved

#518 [12.0] [MIG] hr_employee_phone_extension
  hr_employee_phone_extension/README.rst
  hr_employee_phone_extension/__init__.py
  hr_employee_phone_extension/__manifest__.py
  hr_employee_phone_extension/i18n/ar.po
  hr_employee_phone_extension/i18n/cs_CZ.po
  hr_employee_phone_extension/i18n/de.po
  hr_employee_phone_extension/i18n/es.po
  hr_employee_phone_extension/i18n/fi.po
  hr_employee_phone_extension/i18n/fr.po
  hr_employee_phone_extension/i18n/hr.po
  hr_employee_phone_extension/i18n/hr_HR.po
  hr_employee_phone_extension/i18n/hr_employee_phone_extension.pot
  hr_employee_phone_extension/i18n/it.po
  hr_employee_phone_extension/i18n/lt.po
  hr_employee_phone_extension/i18n/nl_NL.po
  hr_employee_phone_extension/i18n/pt_BR.po
  hr_employee_phone_extension/i18n/ro.po
  hr_employee_phone_extension/i18n/sl.po
  hr_employee_phone_extension/models/__init__.py
  hr_employee_phone_extension/models/hr_employee.py
  hr_employee_phone_extension/readme/CONTRIBUTORS.rst
  hr_employee_phone_extension/readme/DESCRIPTION.rst
  hr_employee_phone_extension/readme/INSTALL.rst
  hr_employee_phone_extension/readme/USAGE.rst
  hr_employee_phone_extension/static/description/icon.png
  hr_employee_phone_extension/views/hr_employee_view.xml
Labels: approved, ready to merge

#576 [11.0][FIX] hr_attendance_report_theoretical_time Minor changes
  hr_attendance_report_theoretical_time/__manifest__.py
  hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report_views.xml
Labels: approved

#593 [10.0][FIX/IMP] hr_employee_firstname: make required attributes dynamic
  hr_employee_firstname/__manifest__.py
  hr_employee_firstname/init_hook.py
  hr_employee_firstname/models/hr_employee.py
  hr_employee_firstname/tests/test_hr_employee_firstname.py
  hr_employee_firstname/views/hr_view.xml
Labels: approved, ready to merge

#598 [MIG][11.0] hr_holidays_validity_date
  hr_holidays_validity_date/README.rst
  hr_holidays_validity_date/__init__.py
  hr_holidays_validity_date/__manifest__.py
  hr_holidays_validity_date/i18n/ar.po
  hr_holidays_validity_date/i18n/cs_CZ.po
  hr_holidays_validity_date/i18n/de.po
  hr_holidays_validity_date/i18n/es.po
  hr_holidays_validity_date/i18n/fr.po
  hr_holidays_validity_date/i18n/hr.po
  hr_holidays_validity_date/i18n/hr_HR.po
  hr_holidays_validity_date/i18n/hr_holidays_validity_date.pot
  hr_holidays_validity_date/i18n/sl.po
  hr_holidays_validity_date/models/__init__.py
  hr_holidays_validity_date/models/hr_holidays.py
  hr_holidays_validity_date/readme/CONTRIBUTORS.rst
  hr_holidays_validity_date/readme/DESCRIPTION.rst
  hr_holidays_validity_date/static/description/icon.png
  hr_holidays_validity_date/tests/__init__.py
  hr_holidays_validity_date/tests/test_hr_holidays_validity_date.py
  hr_holidays_validity_date/views/hr_holidays_view.xml
Labels: approved, ready to merge

#608 [12.0][MIG] hr_employee_calendar_planning
  hr_employee_calendar_planning/README.rst
  hr_employee_calendar_planning/__init__.py
  hr_employee_calendar_planning/__manifest__.py
  hr_employee_calendar_planning/hooks.py
  hr_employee_calendar_planning/i18n/hr_employee_calendar_planning.pot
  hr_employee_calendar_planning/models/__init__.py
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/models/resource_calendar.py
  hr_employee_calendar_planning/readme/CONFIGURE.rst
  hr_employee_calendar_planning/readme/CONTRIBUTORS.rst
  hr_employee_calendar_planning/readme/DESCRIPTION.rst
  hr_employee_calendar_planning/readme/INSTALL.rst
  hr_employee_calendar_planning/readme/ROADMAP.rst
  hr_employee_calendar_planning/security/ir.model.access.csv
  hr_employee_calendar_planning/static/description/icon.png
  hr_employee_calendar_planning/static/description/index.html
  hr_employee_calendar_planning/tests/__init__.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
  hr_employee_calendar_planning/views/hr_employee_views.xml
Labels: approved
