Repository OCA/hr, pull requests merged in 2019-03, with the labels that each got.

#560 [12.0] hr_attendance_report_theoretical_time: My Attendance as default
  hr_attendance_report_theoretical_time/__manifest__.py
  hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report_views.xml
Labels: approved, ready to merge

#557 hr_expense_cancel: lets to cancel and correct expenses
  hr_expense_cancel/README.rst
  hr_expense_cancel/__init__.py
  hr_expense_cancel/__manifest__.py
  hr_expense_cancel/hooks.py
  hr_expense_cancel/i18n/es.po
  hr_expense_cancel/models/__init__.py
  hr_expense_cancel/models/account_payment.py
  hr_expense_cancel/models/hr_expense.py
  hr_expense_cancel/readme/CONTRIBUTORS.rst
  hr_expense_cancel/readme/DESCRIPTION.rst
  hr_expense_cancel/readme/INSTALL.rst
  hr_expense_cancel/readme/USAGE.rst
  hr_expense_cancel/static/description/index.html
  hr_expense_cancel/tests/__init__.py
  hr_expense_cancel/tests/test_hr_expense_cancel.py
  hr_expense_cancel/views/hr_expense_views.xml
  hr_expense_cancel/wizard/__init__.py
  hr_expense_cancel/wizard/hr_expense_sheet_register_payment.py
Labels: approved

#536 [12.0][FIX] hr_employee_service_contract: remove duplicate view
  hr_employee_service_contract/__manifest__.py
  hr_employee_service_contract/models/hr_employee.py
  hr_employee_service_contract/views/hr_employee.xml
Labels: approved, ready to merge

#563 [10.0][FIX] mute exeptions, pylint improvements
  hr_attendance_reason/data/hr_attendance_reason_data.xml
  hr_attendance_rfid/tests/test_hr_attendance_rfid_process.py
  hr_employee_firstname/views/hr_view.xml
  hr_employee_id/models/hr_employee.py
  hr_employee_legacy_id/models/hr.py
  hr_employee_seniority/models/hr_employee.py
  hr_family/__manifest__.py
  hr_family/models/__init__.py
  hr_family/models/hr_children.py
  hr_family/models/hr_employee.py
  hr_holidays_hour/models/hr_holidays.py
  hr_holidays_hour/tests/test_leave_hours.py
  hr_holidays_imposed_days/models/hr_imposed_holidays.py
  hr_holidays_meeting_name/views/hr_holidays_view.xml
  hr_holidays_validity_date/tests/test_hr_holidays_validity_date.py
  hr_payroll_cancel/models/hr_payroll.py
  hr_period/__manifest__.py
  hr_period/tests/test_payslip.py
  hr_period/views/date_range_type_view.xml
  hr_period/views/hr_payslip_run_view.xml
  hr_public_holidays/static/src/js/holidays_highlighter.js
  hr_public_holidays/tests/test_public_holidays.py
  hr_recruitment_skill/__manifest__.py
  hr_recruitment_skill/views/hr_recruitment_skill.xml
  hr_worked_days_from_timesheet/views/hr_payslip_view.xml
Labels: approved

#566 [FIX] hr_public_holidays: Wrong variable usage
  hr_public_holidays/static/src/js/holidays_highlighter.js
Labels: approved

#565 [ADD] hr_employee_calendar_planning: Employee Calendar Planning
  hr_employee_calendar_planning/README.rst
  hr_employee_calendar_planning/__init__.py
  hr_employee_calendar_planning/__manifest__.py
  hr_employee_calendar_planning/hooks.py
  hr_employee_calendar_planning/models/__init__.py
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/models/resource_calendar.py
  hr_employee_calendar_planning/readme/CONFIGURE.rst
  hr_employee_calendar_planning/readme/CONTRIBUTORS.rst
  hr_employee_calendar_planning/readme/DESCRIPTION.rst
  hr_employee_calendar_planning/readme/INSTALL.rst
  hr_employee_calendar_planning/readme/ROADMAP.rst
  hr_employee_calendar_planning/security/ir.model.access.csv
  hr_employee_calendar_planning/static/description/index.html
  hr_employee_calendar_planning/tests/__init__.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
  hr_employee_calendar_planning/views/hr_employee_views.xml
Labels: approved

#568 [IMP] hr_skill
  hr_skill/views/hr_skill.xml
Labels: approved, enhancement
