Repository OCA/hr, pull requests merged in 2019-06, with the labels that each got.

#605 [12.0][MIG] hr_attendance_reason
  hr_attendance_reason/README.rst
  hr_attendance_reason/__init__.py
  hr_attendance_reason/__manifest__.py
  hr_attendance_reason/data/hr_attendance_reason_data.xml
  hr_attendance_reason/i18n/es.po
  hr_attendance_reason/i18n/hr_attendance_reason.pot
  hr_attendance_reason/models/__init__.py
  hr_attendance_reason/models/hr_attendance.py
  hr_attendance_reason/models/hr_attendance_reason.py
  hr_attendance_reason/readme/CONTRIBUTORS.rst
  hr_attendance_reason/readme/DESCRIPTION.rst
  hr_attendance_reason/readme/USAGE.rst
  hr_attendance_reason/security/ir.model.access.csv
  hr_attendance_reason/static/description/icon.png
  hr_attendance_reason/static/description/index.html
  hr_attendance_reason/tests/__init__.py
  hr_attendance_reason/tests/test_hr_attendance_reason.py
  hr_attendance_reason/views/hr_attendance_reason_view.xml
  hr_attendance_reason/views/hr_attendance_view.xml
Labels: approved, ready to merge

#612 [12.0][IMP] hr_employee_calendar_planning
  hr_employee_calendar_planning/models/hr_employee.py
Labels: approved

#618 [12.0][IMP] hr_expense_invoice
  hr_expense_invoice/__manifest__.py
  hr_expense_invoice/views/hr_expense_views.xml
Labels: approved

#588 [12.0][ADD] hr_expense_advance_clearing
  hr_expense_advance_clearing/README.rst
  hr_expense_advance_clearing/__init__.py
  hr_expense_advance_clearing/__manifest__.py
  hr_expense_advance_clearing/data/advance_product.xml
  hr_expense_advance_clearing/models/__init__.py
  hr_expense_advance_clearing/models/account_payment.py
  hr_expense_advance_clearing/models/hr_expense.py
  hr_expense_advance_clearing/models/hr_expense_sheet.py
  hr_expense_advance_clearing/readme/CONFIGURE.rst
  hr_expense_advance_clearing/readme/CONTRIBUTORS.rst
  hr_expense_advance_clearing/readme/DESCRIPTION.rst
  hr_expense_advance_clearing/readme/INSTALL.rst
  hr_expense_advance_clearing/readme/USAGE.rst
  hr_expense_advance_clearing/static/description/icon.png
  hr_expense_advance_clearing/static/description/index.html
  hr_expense_advance_clearing/tests/__init__.py
  hr_expense_advance_clearing/tests/test_hr_expense_advance_clearing.py
  hr_expense_advance_clearing/views/hr_expense_views.xml
  hr_expense_advance_clearing/wizard/__init__.py
  hr_expense_advance_clearing/wizard/hr_expense_sheet_register_payment.py
Labels: approved, ready to merge

#630 [12.0][FIX] Travis Failing Holidays Leave Type Validity
  hr_attendance_report_theoretical_time/tests/test_hr_attendance_report_theoretical_time.py
  hr_holidays_accrual_advanced/tests/test_hr_holidays_accrual_advanced.py
  hr_holidays_leave_repeated/tests/test_holidays_leave_repeated.py
  hr_holidays_length_validation/tests/test_hr_holidays_length_validation.py
Labels: approved

#633 [12.0][FIX] Allow reading skills by everyone
  hr_skill/security/ir.model.access.csv
Labels: approved, bug, merged 🎉, needs review

#625 [12.0][ADD] Migration script from hr_employee_seniority
  hr_employee_service_contract/migrations/12.0.1.0.0/pre-migration.py
Labels: approved, ready to merge
