Repository OCA/hr, pull requests merged in 2019-07, with the labels that each got.

#639 [IMP] hr_holiday_compute_days: Remove unneeded field
  hr_holidays_compute_days/models/hr_holidays.py
  hr_holidays_compute_days/views/hr_holidays_views.xml
Labels: needs review

#638 [FIX] field service_duration does not exist on view
  hr_employee_service/views/hr_employee.xml
Labels: approved, ready to merge

#650 [12.0][FIX] hr_holidays_notify_employee_manager: tests
  hr_holidays_notify_employee_manager/readme/CONTRIBUTORS.rst
  hr_holidays_notify_employee_manager/tests/test_hr_holiday_notify_employee_manager.py
Labels: merged 🎉
