Repository OCA/hr, pull requests merged in 2019-02, with the labels that each got.

#533 [12.0] [MIG] hr_payroll_cancel
  hr_payroll_cancel/README.rst
  hr_payroll_cancel/__init__.py
  hr_payroll_cancel/__manifest__.py
  hr_payroll_cancel/i18n/cs_CZ.po
  hr_payroll_cancel/i18n/de.po
  hr_payroll_cancel/i18n/fr.po
  hr_payroll_cancel/i18n/hr_payroll_cancel.pot
  hr_payroll_cancel/i18n/sl.po
  hr_payroll_cancel/models/__init__.py
  hr_payroll_cancel/models/hr_payroll.py
  hr_payroll_cancel/readme/CONTRIBUTORS.rst
  hr_payroll_cancel/readme/DESCRIPTION.rst
  hr_payroll_cancel/readme/USAGE.rst
  hr_payroll_cancel/static/description/icon.png
  hr_payroll_cancel/static/description/index.html
  hr_payroll_cancel/tests/__init__.py
  hr_payroll_cancel/tests/test_hr_payroll_cancel.py
  hr_payroll_cancel/views/hr_payslip_view.xml
Labels: approved, ready to merge

#550 [ADD] migration script for hr_emergency_contact
  hr_emergency_contact/migrations/10.0.1.0.0/pre-migration.py
Labels: needs review

#534 [12.0][MIG] hr_holidays_public
  hr_holidays_public/README.rst
  hr_holidays_public/__init__.py
  hr_holidays_public/__manifest__.py
  hr_holidays_public/i18n/ar.po
  hr_holidays_public/i18n/de.po
  hr_holidays_public/i18n/es.po
  hr_holidays_public/i18n/fi.po
  hr_holidays_public/i18n/fr.po
  hr_holidays_public/i18n/hr.po
  hr_holidays_public/i18n/hr_HR.po
  hr_holidays_public/i18n/hr_holidays_public.pot
  hr_holidays_public/i18n/it.po
  hr_holidays_public/i18n/nl_NL.po
  hr_holidays_public/i18n/pl.po
  hr_holidays_public/i18n/pt_BR.po
  hr_holidays_public/i18n/ro.po
  hr_holidays_public/i18n/sl.po
  hr_holidays_public/models/__init__.py
  hr_holidays_public/models/hr_holidays_public.py
  hr_holidays_public/models/hr_leave.py
  hr_holidays_public/models/hr_leave_type.py
  hr_holidays_public/models/resource_calendar.py
  hr_holidays_public/readme/CONFIGURE.rst
  hr_holidays_public/readme/CONTRIBUTORS.rst
  hr_holidays_public/readme/DESCRIPTION.rst
  hr_holidays_public/readme/ROADMAP.rst
  hr_holidays_public/readme/USAGE.rst
  hr_holidays_public/security/ir.model.access.csv
  hr_holidays_public/static/description/icon.png
  hr_holidays_public/static/description/icon.svg
  hr_holidays_public/static/description/index.html
  hr_holidays_public/tests/__init__.py
  hr_holidays_public/tests/test_holidays_calculation.py
  hr_holidays_public/tests/test_holidays_public.py
  hr_holidays_public/views/hr_holidays_public_view.xml
  hr_holidays_public/views/hr_leave_type.xml
  hr_holidays_public/wizards/__init__.py
  hr_holidays_public/wizards/holidays_public_next_year_wizard.py
  hr_holidays_public/wizards/holidays_public_next_year_wizard.xml
Labels: approved, ready to merge

#548 [11.0][FIX] hr_job_category: fix access group
  hr_job_category/views/hr_view.xml
Labels: approved, ready to merge

#552 [IMP] Add color to hr_skill
  hr_skill/models/hr_skill.py
  hr_skill/views/hr_skill.xml
Labels: approved, enhancement

#539 [12.0][MIG] hr_holidays_leave_auto_approve
  hr_holidays_leave_auto_approve/README.rst
  hr_holidays_leave_auto_approve/__init__.py
  hr_holidays_leave_auto_approve/__manifest__.py
  hr_holidays_leave_auto_approve/i18n/ar.po
  hr_holidays_leave_auto_approve/i18n/cs_CZ.po
  hr_holidays_leave_auto_approve/i18n/de.po
  hr_holidays_leave_auto_approve/i18n/es.po
  hr_holidays_leave_auto_approve/i18n/fa.po
  hr_holidays_leave_auto_approve/i18n/fr.po
  hr_holidays_leave_auto_approve/i18n/fr_CH.po
  hr_holidays_leave_auto_approve/i18n/hr.po
  hr_holidays_leave_auto_approve/i18n/hr_HR.po
  hr_holidays_leave_auto_approve/i18n/hr_holidays_leave_auto_approve.pot
  hr_holidays_leave_auto_approve/i18n/nl_NL.po
  hr_holidays_leave_auto_approve/i18n/sl.po
  hr_holidays_leave_auto_approve/models/__init__.py
  hr_holidays_leave_auto_approve/models/hr_leave.py
  hr_holidays_leave_auto_approve/models/hr_leave_type.py
  hr_holidays_leave_auto_approve/readme/CONFIGURE.rst
  hr_holidays_leave_auto_approve/readme/CONTRIBUTORS.rst
  hr_holidays_leave_auto_approve/readme/DESCRIPTION.rst
  hr_holidays_leave_auto_approve/tests/__init__.py
  hr_holidays_leave_auto_approve/tests/test_hr_holidays_leave_auto_approve.py
  hr_holidays_leave_auto_approve/views/hr_holidays_status.xml
Labels: approved, ready to merge

#510 [10.0][ADD]hr_attendance_autoclose
  hr_attendance_autoclose/README.rst
  hr_attendance_autoclose/__init__.py
  hr_attendance_autoclose/__manifest__.py
  hr_attendance_autoclose/data/hr_attendance.xml
  hr_attendance_autoclose/data/hr_attendance_reason.xml
  hr_attendance_autoclose/models/__init__.py
  hr_attendance_autoclose/models/hr_attendance.py
  hr_attendance_autoclose/models/res_company.py
  hr_attendance_autoclose/readme/CONTRIBUTORS.rst
  hr_attendance_autoclose/readme/DESCRIPTION.rst
  hr_attendance_autoclose/readme/USAGE.rst
  hr_attendance_autoclose/static/description/index.html
  hr_attendance_autoclose/tests/__init__.py
  hr_attendance_autoclose/tests/test_hr_attendance_auto_close.py
  hr_attendance_autoclose/views/hr_attendance_view.xml
  hr_attendance_autoclose/views/res_company_view.xml
  oca_dependencies.txt
Labels: approved, ready to merge

#509 [ADD][10.0]hr_attendance_reason
  hr_attendance_reason/README.rst
  hr_attendance_reason/__init__.py
  hr_attendance_reason/__manifest__.py
  hr_attendance_reason/data/hr_attendance_reason_data.xml
  hr_attendance_reason/models/__init__.py
  hr_attendance_reason/models/hr_attendance.py
  hr_attendance_reason/models/hr_attendance_reason.py
  hr_attendance_reason/readme/CONTRIBUTORS.rst
  hr_attendance_reason/readme/DESCRIPTION.rst
  hr_attendance_reason/readme/USAGE.rst
  hr_attendance_reason/security/ir.model.access.csv
  hr_attendance_reason/static/description/index.html
  hr_attendance_reason/tests/__init__.py
  hr_attendance_reason/tests/test_hr_attendance_reason.py
  hr_attendance_reason/views/hr_attendance_reason_view.xml
  hr_attendance_reason/views/hr_attendance_view.xml
  oca_dependencies.txt
Labels: approved, ready to merge

#496 [12.0][MIG] hr_skill
  hr_skill/README.rst
  hr_skill/__init__.py
  hr_skill/__manifest__.py
  hr_skill/i18n/ar.po
  hr_skill/i18n/cs_CZ.po
  hr_skill/i18n/de.po
  hr_skill/i18n/en.po
  hr_skill/i18n/es.po
  hr_skill/i18n/fa.po
  hr_skill/i18n/fi.po
  hr_skill/i18n/fr.po
  hr_skill/i18n/gl.po
  hr_skill/i18n/hr.po
  hr_skill/i18n/hr_HR.po
  hr_skill/i18n/hr_skill.pot
  hr_skill/i18n/it.po
  hr_skill/i18n/lt.po
  hr_skill/i18n/nl_NL.po
  hr_skill/i18n/pl.po
  hr_skill/i18n/pt_BR.po
  hr_skill/i18n/ro.po
  hr_skill/i18n/sl.po
  hr_skill/i18n/sv.po
  hr_skill/models/__init__.py
  hr_skill/models/hr_employee.py
  hr_skill/models/hr_employee_skill.py
  hr_skill/models/hr_skill.py
  hr_skill/readme/CONFIGURATION.rst
  hr_skill/readme/CONTRIBUTORS.rst
  hr_skill/readme/CREDITS.rst
  hr_skill/readme/DESCRIPTION.rst
  hr_skill/readme/USAGE.rst
  hr_skill/security/ir.model.access.csv
  hr_skill/static/description/icon.png
  hr_skill/static/description/index.html
  hr_skill/tests/__init__.py
  hr_skill/tests/test_hr_skill.py
  hr_skill/views/hr_employee.xml
  hr_skill/views/hr_employee_skill.xml
  hr_skill/views/hr_skill.xml
Labels: approved, needs review

#497 [12.0][ADD] hr_contract_currency: non-default currency for contract
  hr_contract_currency/README.rst
  hr_contract_currency/__init__.py
  hr_contract_currency/__manifest__.py
  hr_contract_currency/models/__init__.py
  hr_contract_currency/models/hr_contract.py
  hr_contract_currency/readme/CONTRIBUTORS.rst
  hr_contract_currency/readme/DESCRIPTION.rst
  hr_contract_currency/static/description/index.html
  hr_contract_currency/tests/__init__.py
  hr_contract_currency/tests/test_hr_contract_currency.py
  hr_contract_currency/views/hr_contract.xml
Labels: approved, ready to merge

#556 [12.0][MIG] hr_attendance_theoretical_time_report: Migration to 12.0
  hr_attendance_report_theoretical_time/README.rst
  hr_attendance_report_theoretical_time/__init__.py
  hr_attendance_report_theoretical_time/__manifest__.py
  hr_attendance_report_theoretical_time/i18n/de.po
  hr_attendance_report_theoretical_time/i18n/es.po
  hr_attendance_report_theoretical_time/i18n/hr_attendance_report_theoretical_time.pot
  hr_attendance_report_theoretical_time/models/__init__.py
  hr_attendance_report_theoretical_time/models/hr_attendance.py
  hr_attendance_report_theoretical_time/models/hr_employee.py
  hr_attendance_report_theoretical_time/models/hr_holidays_public.py
  hr_attendance_report_theoretical_time/models/hr_leave.py
  hr_attendance_report_theoretical_time/models/hr_leave_type.py
  hr_attendance_report_theoretical_time/readme/CONFIGURE.rst
  hr_attendance_report_theoretical_time/readme/CONTRIBUTORS.rst
  hr_attendance_report_theoretical_time/readme/CREDITS.rst
  hr_attendance_report_theoretical_time/readme/DESCRIPTION.rst
  hr_attendance_report_theoretical_time/readme/INSTALL.rst
  hr_attendance_report_theoretical_time/readme/ROADMAP.rst
  hr_attendance_report_theoretical_time/readme/USAGE.rst
  hr_attendance_report_theoretical_time/reports/__init__.py
  hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report.py
  hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report_views.xml
  hr_attendance_report_theoretical_time/security/hr_attendance_report_theoretical_time_security.xml
  hr_attendance_report_theoretical_time/security/ir.model.access.csv
  hr_attendance_report_theoretical_time/static/description/icon.png
  hr_attendance_report_theoretical_time/static/description/icon.svg
  hr_attendance_report_theoretical_time/static/description/index.html
  hr_attendance_report_theoretical_time/tests/__init__.py
  hr_attendance_report_theoretical_time/tests/test_hr_attendance_report_theoretical_time.py
  hr_attendance_report_theoretical_time/views/hr_attendance_views.xml
  hr_attendance_report_theoretical_time/views/hr_employee_views.xml
  hr_attendance_report_theoretical_time/views/hr_leave_type_views.xml
Labels: approved, needs review, ready to merge

#551 [12.0][ADD] hr_holidays_validate_days: check for outdated number of days requested
  hr_holidays_length_validation/README.rst
  hr_holidays_length_validation/__init__.py
  hr_holidays_length_validation/__manifest__.py
  hr_holidays_length_validation/models/__init__.py
  hr_holidays_length_validation/models/hr_leave.py
  hr_holidays_length_validation/readme/CONTRIBUTORS.rst
  hr_holidays_length_validation/readme/DESCRIPTION.rst
  hr_holidays_length_validation/readme/USAGE.rst
  hr_holidays_length_validation/static/description/index.html
  hr_holidays_length_validation/tests/__init__.py
  hr_holidays_length_validation/tests/test_hr_holidays_length_validation.py
  hr_holidays_length_validation/views/hr_leave.xml
Labels: approved, ready to merge
