Repository OCA/hr, pull requests merged in 2019-01, with the labels that each got.

#517 [12.0] [MIG] hr_experience
  hr_experience/README.rst
  hr_experience/__init__.py
  hr_experience/__manifest__.py
  hr_experience/i18n/ar.po
  hr_experience/i18n/cs_CZ.po
  hr_experience/i18n/de.po
  hr_experience/i18n/es.po
  hr_experience/i18n/fa.po
  hr_experience/i18n/fi.po
  hr_experience/i18n/fr.po
  hr_experience/i18n/gl.po
  hr_experience/i18n/hr.po
  hr_experience/i18n/hr_HR.po
  hr_experience/i18n/hr_experience.pot
  hr_experience/i18n/it.po
  hr_experience/i18n/lt.po
  hr_experience/i18n/nl_NL.po
  hr_experience/i18n/pl.po
  hr_experience/i18n/pt_BR.po
  hr_experience/i18n/ro.po
  hr_experience/i18n/sl.po
  hr_experience/models/__init__.py
  hr_experience/models/hr_academic.py
  hr_experience/models/hr_certification.py
  hr_experience/models/hr_curriculum.py
  hr_experience/models/hr_employee.py
  hr_experience/models/hr_experience.py
  hr_experience/readme/CONTRIBUTORS.rst
  hr_experience/readme/DESCRIPTION.rst
  hr_experience/readme/USAGE.rst
  hr_experience/security/hr_security.xml
  hr_experience/security/ir.model.access.csv
  hr_experience/static/description/icon.png
  hr_experience/views/hr_academic_view.xml
  hr_experience/views/hr_certification_view.xml
  hr_experience/views/hr_employee_view.xml
  hr_experience/views/hr_professional_view.xml
Labels: approved, ready to merge

#519 [12.0] [MIG] hr_holidays_settings
  hr_holidays_settings/README.rst
  hr_holidays_settings/__init__.py
  hr_holidays_settings/__manifest__.py
  hr_holidays_settings/i18n/ar.po
  hr_holidays_settings/i18n/de.po
  hr_holidays_settings/i18n/es.po
  hr_holidays_settings/i18n/fa.po
  hr_holidays_settings/i18n/fi.po
  hr_holidays_settings/i18n/fr.po
  hr_holidays_settings/i18n/hr.po
  hr_holidays_settings/i18n/hr_HR.po
  hr_holidays_settings/i18n/hr_holidays_settings.pot
  hr_holidays_settings/i18n/it.po
  hr_holidays_settings/i18n/nl_NL.po
  hr_holidays_settings/i18n/pt_BR.po
  hr_holidays_settings/i18n/ro.po
  hr_holidays_settings/i18n/sl.po
  hr_holidays_settings/readme/CONTRIBUTORS.rst
  hr_holidays_settings/readme/DESCRIPTION.rst
  hr_holidays_settings/readme/USAGE.rst
  hr_holidays_settings/static/description/icon.png
  hr_holidays_settings/views/res_config_settings.xml
Labels: approved, ready to merge

#546 [IMP] description
  hr_skill/models/hr_skill.py
  hr_skill/views/hr_skill.xml
Labels: approved, enhancement

#373 10.0 Add hr_recruitment_candidate_multi_applicant
  hr_recruitment_candidate_multi_applicant/README.rst
  hr_recruitment_candidate_multi_applicant/__init__.py
  hr_recruitment_candidate_multi_applicant/__manifest__.py
  hr_recruitment_candidate_multi_applicant/i18n/fr.po
  hr_recruitment_candidate_multi_applicant/i18n/hr_recruitment_candidate_multi_applicant.pot
  hr_recruitment_candidate_multi_applicant/models/__init__.py
  hr_recruitment_candidate_multi_applicant/models/hr_applicant.py
  hr_recruitment_candidate_multi_applicant/tests/__init__.py
  hr_recruitment_candidate_multi_applicant/tests/test_multi_applicant.py
  hr_recruitment_candidate_multi_applicant/views/applicant.xml
Labels: approved, needs review, ready to merge
