Repository OCA/hr, pull requests merged in 2020-07, with the labels that each got.

#855 [13.0][MIG] hr_employee_ssn
  hr_employee_ssn/README.rst
  hr_employee_ssn/__init__.py
  hr_employee_ssn/__manifest__.py
  hr_employee_ssn/i18n/fr.po
  hr_employee_ssn/i18n/hr_employee_ssn.pot
  hr_employee_ssn/readme/CONTRIBUTORS.rst
  hr_employee_ssn/readme/DESCRIPTION.rst
  hr_employee_ssn/static/description/icon.png
  hr_employee_ssn/static/description/index.html
  hr_employee_ssn/views/hr_employee_views.xml
  setup/hr_employee_ssn/odoo/addons/hr_employee_ssn
  setup/hr_employee_ssn/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#844 [12.0][IMP] hr_attendance_modification_tracking: ADD 'time changed' -contains all commits-
  hr_attendance_modification_tracking/__init__.py
  hr_attendance_modification_tracking/__manifest__.py
  hr_attendance_modification_tracking/i18n/es.po
  hr_attendance_modification_tracking/models/hr_attendance.py
  hr_attendance_modification_tracking/readme/CONTRIBUTORS.rst
  hr_attendance_modification_tracking/readme/DESCRIPTION.rst
  hr_attendance_modification_tracking/tests/__init__.py
  hr_attendance_modification_tracking/tests/test_hr_attendance.py
  hr_attendance_modification_tracking/views/hr_attendance_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#858 [12.0][IMP] hr_attendance_modification_tracking: add manual column pre-install
  hr_attendance_modification_tracking/__init__.py
  hr_attendance_modification_tracking/__manifest__.py
  hr_attendance_modification_tracking/hooks.py
  hr_attendance_modification_tracking/migrations/12.0.1.2.0/pre-migration.py
  hr_attendance_modification_tracking/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#859 [FIX] hr_attendance_modification_tracking: sudo read
  hr_attendance_modification_tracking/models/hr_attendance.py
Labels: approved, bot is merging ⏳

#680 [11.0][MIG] Backport of hr_employee_social_media from v12
  hr_employee_social_media/README.rst
  hr_employee_social_media/__init__.py
  hr_employee_social_media/__manifest__.py
  hr_employee_social_media/data/social_media.xml
  hr_employee_social_media/i18n/ar.po
  hr_employee_social_media/i18n/cs_CZ.po
  hr_employee_social_media/i18n/de.po
  hr_employee_social_media/i18n/es.po
  hr_employee_social_media/i18n/fi.po
  hr_employee_social_media/i18n/fr.po
  hr_employee_social_media/i18n/hr.po
  hr_employee_social_media/i18n/hr_HR.po
  hr_employee_social_media/i18n/hr_employee_social_media.pot
  hr_employee_social_media/i18n/it.po
  hr_employee_social_media/i18n/lt.po
  hr_employee_social_media/i18n/nl_NL.po
  hr_employee_social_media/i18n/pl.po
  hr_employee_social_media/i18n/pt_BR.po
  hr_employee_social_media/i18n/ro.po
  hr_employee_social_media/i18n/sl.po
  hr_employee_social_media/models/__init__.py
  hr_employee_social_media/models/hr_employee.py
  hr_employee_social_media/models/hr_social_media.py
  hr_employee_social_media/readme/CONTRIBUTORS.rst
  hr_employee_social_media/readme/DESCRIPTION.rst
  hr_employee_social_media/security/ir.model.access.csv
  hr_employee_social_media/static/description/icon.png
  hr_employee_social_media/static/description/index.html
  hr_employee_social_media/tests/__init__.py
  hr_employee_social_media/tests/test_social_media.py
  hr_employee_social_media/views/hr_employee_view.xml
  hr_employee_social_media/views/hr_social_media.xml
Labels: approved, bot is merging ⏳, ready to merge

#687 [13.0][MIG]hr_contract_multi_job
  hr_contract_multi_job/README.rst
  hr_contract_multi_job/__init__.py
  hr_contract_multi_job/__manifest__.py
  hr_contract_multi_job/i18n/ar.po
  hr_contract_multi_job/i18n/de.po
  hr_contract_multi_job/i18n/es.po
  hr_contract_multi_job/i18n/fi.po
  hr_contract_multi_job/i18n/fr.po
  hr_contract_multi_job/i18n/hr_contract_multi_job.pot
  hr_contract_multi_job/i18n/it.po
  hr_contract_multi_job/i18n/pt_BR.po
  hr_contract_multi_job/i18n/ro.po
  hr_contract_multi_job/i18n/sl.po
  hr_contract_multi_job/models/__init__.py
  hr_contract_multi_job/models/hr_contract.py
  hr_contract_multi_job/models/hr_contract_job.py
  hr_contract_multi_job/models/hr_job.py
  hr_contract_multi_job/readme/CONTRIBUTORS.rst
  hr_contract_multi_job/readme/DESCRIPTION.rst
  hr_contract_multi_job/readme/USAGE.rst
  hr_contract_multi_job/security/ir.model.access.csv
  hr_contract_multi_job/static/description/icon.png
  hr_contract_multi_job/static/description/index.html
  hr_contract_multi_job/tests/__init__.py
  hr_contract_multi_job/tests/test_hr_contract_multi_jobs.py
  hr_contract_multi_job/views/hr_contract_view.xml
  setup/hr_contract_multi_job/odoo/addons/hr_contract_multi_job
  setup/hr_contract_multi_job/setup.py
Labels: approved, ready to merge

#829 [12.0] .gitignore: add !static/lib/ as per oca rules
  .gitignore
Labels: approved, bot is merging ⏳, ready to merge

#860 [13.0][MIG] hr_employee_medical_examination
  hr_employee_medical_examination/README.rst
  hr_employee_medical_examination/__init__.py
  hr_employee_medical_examination/__manifest__.py
  hr_employee_medical_examination/i18n/es.po
  hr_employee_medical_examination/i18n/hr_employee_medical_examination.pot
  hr_employee_medical_examination/models/__init__.py
  hr_employee_medical_examination/models/hr_employee.py
  hr_employee_medical_examination/models/hr_employee_medical_examination.py
  hr_employee_medical_examination/readme/CONTRIBUTORS.rst
  hr_employee_medical_examination/readme/DESCRIPTION.rst
  hr_employee_medical_examination/readme/USAGE.rst
  hr_employee_medical_examination/security/hr_employee_medical_examination_security.xml
  hr_employee_medical_examination/security/ir.model.access.csv
  hr_employee_medical_examination/static/description/icon.png
  hr_employee_medical_examination/static/description/index.html
  hr_employee_medical_examination/tests/__init__.py
  hr_employee_medical_examination/tests/test_hr_employee_medical_examination.py
  hr_employee_medical_examination/views/hr_employee_medical_examination_views.xml
  hr_employee_medical_examination/views/hr_employee_views.xml
  hr_employee_medical_examination/wizards/__init__.py
  hr_employee_medical_examination/wizards/wizard_generate_medical_examination.py
  hr_employee_medical_examination/wizards/wizard_generate_medical_examination.xml
Labels: approved, bot is merging ⏳, ready to merge
