Repository OCA/hr, pull requests merged in 2020-05, with the labels that each got.

#778 [12.0][IMP] hr_holidays_leave_auto_approve: disable creation of activity
  hr_holidays_leave_auto_approve/models/hr_leave.py
Labels: approved, bot is merging ⏳

#832 [13.0][MIG] hr_employee_calendar_planning
  hr_employee_calendar_planning/README.rst
  hr_employee_calendar_planning/__init__.py
  hr_employee_calendar_planning/__manifest__.py
  hr_employee_calendar_planning/hooks.py
  hr_employee_calendar_planning/i18n/ca.po
  hr_employee_calendar_planning/i18n/ca_ES.po
  hr_employee_calendar_planning/i18n/es.po
  hr_employee_calendar_planning/i18n/hr_employee_calendar_planning.pot
  hr_employee_calendar_planning/models/__init__.py
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/models/resource_calendar.py
  hr_employee_calendar_planning/readme/CONFIGURE.rst
  hr_employee_calendar_planning/readme/CONTRIBUTORS.rst
  hr_employee_calendar_planning/readme/DESCRIPTION.rst
  hr_employee_calendar_planning/readme/INSTALL.rst
  hr_employee_calendar_planning/readme/ROADMAP.rst
  hr_employee_calendar_planning/security/ir.model.access.csv
  hr_employee_calendar_planning/static/description/icon.png
  hr_employee_calendar_planning/static/description/index.html
  hr_employee_calendar_planning/tests/__init__.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
  hr_employee_calendar_planning/views/hr_employee_views.xml
Labels: approved, bot is merging ⏳

#775 [13.0][MIG] hr_employee_relative
  hr_employee_relative/README.rst
  hr_employee_relative/__init__.py
  hr_employee_relative/__manifest__.py
  hr_employee_relative/data/data_relative_relation.xml
  hr_employee_relative/i18n/es.po
  hr_employee_relative/i18n/fr.po
  hr_employee_relative/i18n/hr.po
  hr_employee_relative/i18n/hr_employee_relative.pot
  hr_employee_relative/models/__init__.py
  hr_employee_relative/models/hr_employee.py
  hr_employee_relative/models/hr_employee_relative.py
  hr_employee_relative/models/hr_employee_relative_relation.py
  hr_employee_relative/readme/CONTRIBUTORS.rst
  hr_employee_relative/readme/DESCRIPTION.rst
  hr_employee_relative/security/ir.model.access.csv
  hr_employee_relative/static/description/icon.png
  hr_employee_relative/static/description/index.html
  hr_employee_relative/tests/__init__.py
  hr_employee_relative/tests/test_hr_employee_relatives.py
  hr_employee_relative/views/hr_employee.xml
  hr_employee_relative/views/hr_employee_relative.xml
  setup/hr_employee_relative/odoo/addons/hr_employee_relative
  setup/hr_employee_relative/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#834 [IMP] hr_family: Groups for family now could be extended
  hr_family/views/hr_employee.xml
Labels: approved, bot is merging ⏳

#835 [IMP] hr_family: Groups for family now could be extended
  hr_family/views/hr_employee.xml
Labels: bot is merging ⏳
