Repository OCA/hr, pull requests merged in 2020-02, with the labels that each got.

#746 [12.0][FIX] hr_expense_advance_clearing
  hr_expense_advance_clearing/__manifest__.py
  hr_expense_advance_clearing/models/hr_expense_sheet.py
Labels: approved, ready to merge

#710 [12.0][MIG] hr_course
  hr_course/README.rst
  hr_course/__init__.py
  hr_course/__manifest__.py
  hr_course/i18n/es.po
  hr_course/i18n/hr_course.pot
  hr_course/models/__init__.py
  hr_course/models/hr_course.py
  hr_course/models/hr_employee.py
  hr_course/readme/CONTRIBUTORS.rst
  hr_course/readme/DESCRIPTION.rst
  hr_course/readme/USAGE.rst
  hr_course/security/course_security.xml
  hr_course/security/ir.model.access.csv
  hr_course/static/description/icon.png
  hr_course/static/description/index.html
  hr_course/tests/__init__.py
  hr_course/tests/test_hr_course.py
  hr_course/views/hr_course_category_views.xml
  hr_course/views/hr_course_views.xml
  hr_course/views/hr_employee_views.xml
Labels: approved, ready to merge

#792 [11.0][FIX] theoretical_time: Context was not imported on wizard
  hr_attendance_report_theoretical_time/wizards/wizard_theoretical_time.py
Labels: approved

#791 [12.0][FIX] theoretical_time: Context was not imported on wizard
  hr_attendance_report_theoretical_time/wizards/wizard_theoretical_time.py
Labels: approved

#780 [11.0][IMP] hr_autoclose: max_hours_hook
  hr_attendance_autoclose/models/hr_attendance.py
  hr_attendance_autoclose/models/hr_employee.py
Labels: approved, ready to merge

#772 [12.0] [MIG] hr_employee_age
  hr_employee_age/README.rst
  hr_employee_age/__init__.py
  hr_employee_age/__manifest__.py
  hr_employee_age/i18n/ar.po
  hr_employee_age/i18n/cs_CZ.po
  hr_employee_age/i18n/de.po
  hr_employee_age/i18n/es.po
  hr_employee_age/i18n/fi.po
  hr_employee_age/i18n/fr.po
  hr_employee_age/i18n/hr.po
  hr_employee_age/i18n/hr_HR.po
  hr_employee_age/i18n/hr_employee_age.pot
  hr_employee_age/i18n/it.po
  hr_employee_age/i18n/lt.po
  hr_employee_age/i18n/nl_NL.po
  hr_employee_age/i18n/pt_BR.po
  hr_employee_age/i18n/ro.po
  hr_employee_age/i18n/sl.po
  hr_employee_age/models/__init__.py
  hr_employee_age/models/hr_employee.py
  hr_employee_age/readme/CONTRIBUTORS.rst
  hr_employee_age/readme/DESCRIPTION.rst
  hr_employee_age/readme/INSTALL.rst
  hr_employee_age/readme/USAGE.rst
  hr_employee_age/static/description/icon.png
  hr_employee_age/static/description/index.html
  hr_employee_age/tests/__init__.py
  hr_employee_age/tests/test_hr_employee.py
  hr_employee_age/views/hr_employee.xml
Labels: approved, ready to merge

#508 [10.0][IMP] Refactor create_next_year_public_holidays wizard
  hr_public_holidays/wizards/public_holidays_next_year_wizard.py
Labels: approved, ready to merge

#614 [FIX] run reconciliation on recordset
  hr_expense_cancel/hooks.py
Labels: approved, ready to merge

#572 [MIG] hr_employee_data_from_work_address to v10
  hr_employee_data_from_work_address/README.rst
  hr_employee_data_from_work_address/__init__.py
  hr_employee_data_from_work_address/__manifest__.py
  hr_employee_data_from_work_address/data/res_partner_category.xml
  hr_employee_data_from_work_address/init_hook.py
  hr_employee_data_from_work_address/models/__init__.py
  hr_employee_data_from_work_address/models/hr_employee.py
  hr_employee_data_from_work_address/readme/CONTRIBUTORS.rst
  hr_employee_data_from_work_address/readme/CREDITS.rst
  hr_employee_data_from_work_address/readme/DESCRIPTION.rst
  hr_employee_data_from_work_address/readme/USAGE.rst
  hr_employee_data_from_work_address/static/description/index.html
  hr_employee_data_from_work_address/tests/__init__.py
  hr_employee_data_from_work_address/tests/test_hr_employee_data_from_work_address.py
  hr_employee_data_from_work_address/views/hr_employee.xml
Labels: approved, needs review, ready to merge

#709 [12.0][MIG] hr_calendar_rest_time
  hr_calendar_rest_time/README.rst
  hr_calendar_rest_time/__init__.py
  hr_calendar_rest_time/__manifest__.py
  hr_calendar_rest_time/i18n/hr_calendar_rest_time.pot
  hr_calendar_rest_time/migrations/12.0.1.0.0/post-migration.py
  hr_calendar_rest_time/models/__init__.py
  hr_calendar_rest_time/models/resource_calendar.py
  hr_calendar_rest_time/models/resource_calendar_attendance.py
  hr_calendar_rest_time/models/resource_mixin.py
  hr_calendar_rest_time/readme/CONTRIBUTORS.rst
  hr_calendar_rest_time/readme/DESCRIPTION.rst
  hr_calendar_rest_time/readme/HISTORY.rst
  hr_calendar_rest_time/readme/USAGE.rst
  hr_calendar_rest_time/static/description/icon.png
  hr_calendar_rest_time/static/description/index.html
  hr_calendar_rest_time/tests/__init__.py
  hr_calendar_rest_time/tests/test_hr_calendar_rest_time.py
  hr_calendar_rest_time/views/resource_calendar_attendance.xml
  resource_hook/README.rst
  resource_hook/__init__.py
  resource_hook/__manifest__.py
  resource_hook/hooks.py
  resource_hook/i18n/resource_hook.pot
  resource_hook/models/__init__.py
  resource_hook/models/resource_mixin.py
  resource_hook/readme/CONTRIBUTORS.rst
  resource_hook/readme/DESCRIPTION.rst
  resource_hook/readme/HISTORY.rst
  resource_hook/static/description/icon.png
  resource_hook/static/description/index.html
Labels: approved
