Repository OCA/hr, pull requests merged in 2020-11, with the labels that each got.

#918 [14.0][REF] hr_employee_firstname,hr_employee_lastnames: Removed partner-contact dependencies
  hr_employee_firstname/__manifest__.py
  hr_employee_firstname/i18n/es.po
  hr_employee_firstname/models/__init__.py
  hr_employee_firstname/models/base_config_settings.py
  hr_employee_firstname/models/hr_employee.py
  hr_employee_firstname/tests/test_hr_employee_firstname.py
  hr_employee_firstname/views/base_config_view.xml
  hr_employee_lastnames/__manifest__.py
  hr_employee_lastnames/hook.py
  hr_employee_lastnames/models/hr_employee.py
  hr_employee_lastnames/tests/test_hr_employee_lastnames.py
Labels: approved, bot is merging ⏳

#921 [UPD] Brainbean Apps => CorporateHub
  hr_employee_social_media/README.rst
  hr_employee_social_media/__manifest__.py
  hr_employee_social_media/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#922 [UPD] Brainbean Apps => CorporateHub
  hr_contract_currency/README.rst
  hr_contract_currency/__manifest__.py
  hr_contract_currency/readme/CONTRIBUTORS.rst
  hr_contract_document/README.rst
  hr_contract_document/__manifest__.py
  hr_contract_document/readme/CONTRIBUTORS.rst
  hr_contract_rate/README.rst
  hr_contract_rate/__manifest__.py
  hr_contract_rate/readme/CONTRIBUTORS.rst
  hr_employee_document/README.rst
  hr_employee_document/__manifest__.py
  hr_employee_document/readme/CONTRIBUTORS.rst
  hr_employee_health/README.rst
  hr_employee_health/__manifest__.py
  hr_employee_health/readme/CONTRIBUTORS.rst
  hr_employee_id/README.rst
  hr_employee_id/__manifest__.py
  hr_employee_id/readme/CONTRIBUTORS.rst
  hr_employee_relative/README.rst
  hr_employee_relative/__manifest__.py
  hr_employee_relative/readme/CONTRIBUTORS.rst
  hr_employee_service/README.rst
  hr_employee_service/__manifest__.py
  hr_employee_service/readme/CONTRIBUTORS.rst
  hr_employee_service_contract/README.rst
  hr_employee_service_contract/__manifest__.py
  hr_employee_service_contract/readme/CONTRIBUTORS.rst
  hr_employee_social_media/README.rst
  hr_employee_social_media/__manifest__.py
  hr_employee_social_media/readme/CONTRIBUTORS.rst
  hr_employee_ssn/README.rst
  hr_employee_ssn/__manifest__.py
  hr_employee_ssn/readme/CONTRIBUTORS.rst
  hr_holidays_accrual_advanced/README.rst
  hr_holidays_accrual_advanced/__manifest__.py
  hr_holidays_accrual_advanced/readme/CONTRIBUTORS.rst
  hr_holidays_credit/README.rst
  hr_holidays_credit/__manifest__.py
  hr_holidays_credit/readme/CONTRIBUTORS.rst
  hr_holidays_leave_request_wizard/README.rst
  hr_holidays_leave_request_wizard/__manifest__.py
  hr_holidays_leave_request_wizard/readme/CONTRIBUTORS.rst
  hr_holidays_length_validation/README.rst
  hr_holidays_length_validation/__manifest__.py
  hr_holidays_length_validation/readme/CONTRIBUTORS.rst
  hr_holidays_notify_employee_manager/README.rst
  hr_holidays_notify_employee_manager/readme/CONTRIBUTORS.rst
  hr_holidays_public/README.rst
  hr_holidays_public/readme/CONTRIBUTORS.rst
  hr_holidays_settings/README.rst
  hr_holidays_settings/readme/CONTRIBUTORS.rst
  hr_skill/README.rst
  hr_skill/__manifest__.py
  hr_skill/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#920 [IMP] hr_employee_ppe: Add Maintainers and module credits
  hr_employee_ppe/__manifest__.py
  hr_employee_ppe/readme/CREDITS.rst
  hr_employee_ppe/static/description/banner.png
Labels: approved, bot is merging ⏳

#897 [13.0][MIG] hr_calendar_rest_time
  hr_calendar_rest_time/README.rst
  hr_calendar_rest_time/__init__.py
  hr_calendar_rest_time/__manifest__.py
  hr_calendar_rest_time/i18n/hr_calendar_rest_time.pot
  hr_calendar_rest_time/models/__init__.py
  hr_calendar_rest_time/models/resource_calendar.py
  hr_calendar_rest_time/models/resource_calendar_attendance.py
  hr_calendar_rest_time/models/resource_mixin.py
  hr_calendar_rest_time/readme/CONTRIBUTORS.rst
  hr_calendar_rest_time/readme/DESCRIPTION.rst
  hr_calendar_rest_time/readme/HISTORY.rst
  hr_calendar_rest_time/readme/USAGE.rst
  hr_calendar_rest_time/static/description/icon.png
  hr_calendar_rest_time/static/description/index.html
  hr_calendar_rest_time/tests/__init__.py
  hr_calendar_rest_time/tests/test_hr_calendar_rest_time.py
  hr_calendar_rest_time/views/resource_calendar_attendance.xml
  setup/hr_calendar_rest_time/odoo/addons/hr_calendar_rest_time
  setup/hr_calendar_rest_time/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#923 [IMP] hr_expense_advance_clearing: hide analytics tags as well
  hr_expense_advance_clearing/views/hr_expense_views.xml
Labels: approved, bot is merging ⏳

#750 [13.0][MIG] hr_employee_document
  hr_employee_document/README.rst
  hr_employee_document/__init__.py
  hr_employee_document/__manifest__.py
  hr_employee_document/i18n/fr.po
  hr_employee_document/i18n/hr.po
  hr_employee_document/i18n/hr_employee_document.pot
  hr_employee_document/models/__init__.py
  hr_employee_document/models/hr_employee.py
  hr_employee_document/readme/CONTRIBUTORS.rst
  hr_employee_document/readme/DESCRIPTION.rst
  hr_employee_document/static/description/icon.png
  hr_employee_document/static/description/index.html
  hr_employee_document/tests/__init__.py
  hr_employee_document/tests/test_hr_employee_document.py
  hr_employee_document/views/hr_employee.xml
  setup/hr_employee_document/odoo/addons/hr_employee_document
  setup/hr_employee_document/setup.py
Labels: approved, bot is merging ⏳

#927 [UPD] Brainbean Apps => CorporateHub
  hr_contract_currency/README.rst
  hr_contract_currency/__manifest__.py
  hr_contract_currency/readme/CONTRIBUTORS.rst
  hr_employee_document/README.rst
  hr_employee_document/__manifest__.py
  hr_employee_document/readme/CONTRIBUTORS.rst
  hr_employee_relative/README.rst
  hr_employee_relative/__manifest__.py
  hr_employee_relative/readme/CONTRIBUTORS.rst
  hr_employee_service/README.rst
  hr_employee_service/__manifest__.py
  hr_employee_service/readme/CONTRIBUTORS.rst
  hr_employee_service_contract/README.rst
  hr_employee_service_contract/__manifest__.py
  hr_employee_service_contract/readme/CONTRIBUTORS.rst
  hr_employee_ssn/README.rst
  hr_employee_ssn/__manifest__.py
  hr_employee_ssn/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#892 [12.0][ADD] hr_expense_receipt_require
  hr_expense_receipt_require/README.rst
  hr_expense_receipt_require/__init__.py
  hr_expense_receipt_require/__manifest__.py
  hr_expense_receipt_require/models/__init__.py
  hr_expense_receipt_require/models/hr_expense.py
  hr_expense_receipt_require/models/product_template.py
  hr_expense_receipt_require/readme/CONFIGURE.rst
  hr_expense_receipt_require/readme/CONTRIBUTORS.rst
  hr_expense_receipt_require/readme/DESCRIPTION.rst
  hr_expense_receipt_require/readme/USAGE.rst
  hr_expense_receipt_require/static/description/icon.png
  hr_expense_receipt_require/tests/__init__.py
  hr_expense_receipt_require/tests/test_hr_expense.py
  hr_expense_receipt_require/views/hr_expense_views.xml
Labels: approved, bot is merging ⏳

#931 [12.0][FIX] hr_employee_calendar_planning: generate when needed
  hr_employee_calendar_planning/models/resource_calendar.py
Labels: approved, bot is merging ⏳

#937 [14.0][MIG] hr_employee_relative
  hr_employee_relative/README.rst
  hr_employee_relative/__init__.py
  hr_employee_relative/__manifest__.py
  hr_employee_relative/data/data_relative_relation.xml
  hr_employee_relative/i18n/es.po
  hr_employee_relative/i18n/fr.po
  hr_employee_relative/i18n/hr.po
  hr_employee_relative/i18n/hr_employee_relative.pot
  hr_employee_relative/models/__init__.py
  hr_employee_relative/models/hr_employee.py
  hr_employee_relative/models/hr_employee_relative.py
  hr_employee_relative/models/hr_employee_relative_relation.py
  hr_employee_relative/readme/CONTRIBUTORS.rst
  hr_employee_relative/readme/DESCRIPTION.rst
  hr_employee_relative/security/ir.model.access.csv
  hr_employee_relative/static/description/icon.png
  hr_employee_relative/static/description/index.html
  hr_employee_relative/tests/__init__.py
  hr_employee_relative/tests/test_hr_employee_relatives.py
  hr_employee_relative/views/hr_employee.xml
  hr_employee_relative/views/hr_employee_relative.xml
  requirements.txt
  setup/hr_employee_relative/odoo/addons/hr_employee_relative
  setup/hr_employee_relative/setup.py
Labels: approved, bot is merging ⏳

#939 [14.0][MIG] hr_employee_ssn
  hr_employee_ssn/README.rst
  hr_employee_ssn/__init__.py
  hr_employee_ssn/__manifest__.py
  hr_employee_ssn/i18n/fr.po
  hr_employee_ssn/i18n/hr_employee_ssn.pot
  hr_employee_ssn/readme/CONTRIBUTORS.rst
  hr_employee_ssn/readme/DESCRIPTION.rst
  hr_employee_ssn/static/description/icon.png
  hr_employee_ssn/static/description/index.html
  hr_employee_ssn/views/hr_employee_views.xml
  setup/hr_employee_ssn/odoo/addons/hr_employee_ssn
  setup/hr_employee_ssn/setup.py
Labels: approved, bot is merging ⏳
