Repository OCA/hr, pull requests merged in 2020-04, with the labels that each got.

#808 [12.0][FIX] hr_expense_tier_validation : USAGE readme typo
  hr_expense_tier_validation/README.rst
  hr_expense_tier_validation/readme/USAGE.rst
  hr_expense_tier_validation/static/description/index.html
Labels: approved, bot is merging ⏳

#813 [12.0][IMP] float_time widget on hr_attendance_autoclose
  hr_attendance_autoclose/views/hr_attendance_view.xml
Labels: approved, bot is merging ⏳

#760 [10.0][FIX] Call correct process/function to validate holidays/leave
  hr_holidays_imposed_days/models/hr_imposed_holidays.py
Labels: approved, bot is merging ⏳

#788 [FIX] hr_holidays_public: avoid object mixing
  hr_holidays_public/models/resource_calendar.py
Labels: bot is merging ⏳

#782 [13.0][MIG] hr_employee_service
  hr_employee_service/README.rst
  hr_employee_service/__init__.py
  hr_employee_service/__manifest__.py
  hr_employee_service/i18n/de.po
  hr_employee_service/i18n/es.po
  hr_employee_service/i18n/fr.po
  hr_employee_service/i18n/hr_employee_service.pot
  hr_employee_service/models/__init__.py
  hr_employee_service/models/hr_employee.py
  hr_employee_service/readme/CONTRIBUTORS.rst
  hr_employee_service/readme/DESCRIPTION.rst
  hr_employee_service/static/description/icon.png
  hr_employee_service/static/description/index.html
  hr_employee_service/tests/__init__.py
  hr_employee_service/tests/test_hr_employee_service.py
  hr_employee_service/views/hr_employee.xml
  setup/hr_employee_service/odoo/addons/hr_employee_service
  setup/hr_employee_service/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#763 [12.0][IMP] hr_holidays_public: improve wizard
  hr_holidays_public/tests/test_holidays_public.py
  hr_holidays_public/views/hr_holidays_public_view.xml
  hr_holidays_public/wizards/holidays_public_next_year_wizard.py
  hr_holidays_public/wizards/holidays_public_next_year_wizard.xml
Labels: approved, bot is merging ⏳, ready to merge

#817 [12.0][FIX] resource_hook : hook function _get_work_hours in day_total
  resource_hook/hooks.py
Labels: approved, bot is merging ⏳, ready to merge
