Repository OCA/hr, pull requests merged in 2020-10, with the labels that each got.

#900 [IMP] hr_employee_firstname: ease extension
  hr_employee_firstname/models/hr_employee.py
Labels: bot is merging ⏳

#894 [13.0][MIG] hr_course
  hr_course/README.rst
  hr_course/__init__.py
  hr_course/__manifest__.py
  hr_course/i18n/es.po
  hr_course/i18n/hr_course.pot
  hr_course/models/__init__.py
  hr_course/models/hr_course.py
  hr_course/models/hr_employee.py
  hr_course/readme/CONTRIBUTORS.rst
  hr_course/readme/DESCRIPTION.rst
  hr_course/readme/USAGE.rst
  hr_course/security/course_security.xml
  hr_course/security/ir.model.access.csv
  hr_course/static/description/icon.png
  hr_course/static/description/index.html
  hr_course/tests/__init__.py
  hr_course/tests/test_hr_course.py
  hr_course/views/hr_course_category_views.xml
  hr_course/views/hr_course_views.xml
  hr_course/views/hr_employee_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#902 [MIG] hr_employee_lastnames: Migration to 11.0
  hr_employee_lastnames/README.rst
  hr_employee_lastnames/__init__.py
  hr_employee_lastnames/__manifest__.py
  hr_employee_lastnames/hook.py
  hr_employee_lastnames/i18n/es.po
  hr_employee_lastnames/i18n/hr_employee_lastnames.pot
  hr_employee_lastnames/models/__init__.py
  hr_employee_lastnames/models/hr_employee.py
  hr_employee_lastnames/readme/CONTRIBUTORS.rst
  hr_employee_lastnames/readme/DESCRIPTION.rst
  hr_employee_lastnames/readme/USAGE.rst
  hr_employee_lastnames/static/description/icon.png
  hr_employee_lastnames/static/description/index.html
  hr_employee_lastnames/tests/__init__.py
  hr_employee_lastnames/tests/test_hr_employee_lastnames.py
  hr_employee_lastnames/views/hr_views.xml
Labels: bot is merging ⏳

#903 [IMP] hr_employee_firstname: ease extension
  hr_employee_firstname/models/hr_employee.py
Labels: bot is merging ⏳

#904 [MIG] : Migration to 12.0
  hr_employee_lastnames/README.rst
  hr_employee_lastnames/__init__.py
  hr_employee_lastnames/__manifest__.py
  hr_employee_lastnames/hook.py
  hr_employee_lastnames/i18n/es.po
  hr_employee_lastnames/i18n/hr_employee_lastnames.pot
  hr_employee_lastnames/models/__init__.py
  hr_employee_lastnames/models/hr_employee.py
  hr_employee_lastnames/readme/CONTRIBUTORS.rst
  hr_employee_lastnames/readme/DESCRIPTION.rst
  hr_employee_lastnames/readme/USAGE.rst
  hr_employee_lastnames/static/description/icon.png
  hr_employee_lastnames/static/description/index.html
  hr_employee_lastnames/tests/__init__.py
  hr_employee_lastnames/tests/test_hr_employee_lastnames.py
  hr_employee_lastnames/views/hr_views.xml
Labels: bot is merging ⏳

#895 [13.0][MIG] hr_job_category
  hr_job_category/README.rst
  hr_job_category/__init__.py
  hr_job_category/__manifest__.py
  hr_job_category/i18n/de.po
  hr_job_category/i18n/es.po
  hr_job_category/i18n/fi.po
  hr_job_category/i18n/fr.po
  hr_job_category/i18n/hr_job_category.pot
  hr_job_category/i18n/it.po
  hr_job_category/i18n/pt_BR.po
  hr_job_category/i18n/ro.po
  hr_job_category/i18n/sl.po
  hr_job_category/models/__init__.py
  hr_job_category/models/hr.py
  hr_job_category/readme/CONTRIBUTORS.rst
  hr_job_category/readme/DESCRIPTION.rst
  hr_job_category/readme/INSTALL.rst
  hr_job_category/readme/USAGE.rst
  hr_job_category/static/description/icon.png
  hr_job_category/static/description/index.html
  hr_job_category/tests/__init__.py
  hr_job_category/tests/test_hr_job_categories.py
  hr_job_category/views/hr_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#908 [MIG] hr_branch: Migration to 14.0
  hr_branch/README.rst
  hr_branch/__init__.py
  hr_branch/__manifest__.py
  hr_branch/i18n/es.po
  hr_branch/i18n/hr_branch.pot
  hr_branch/models/__init__.py
  hr_branch/models/hr_department.py
  hr_branch/readme/CONTRIBUTORS.rst
  hr_branch/readme/DESCRIPTION.rst
  hr_branch/static/description/icon.png
  hr_branch/static/description/index.html
  hr_branch/views/hr_department_views.xml
  hr_branch/views/hr_employee_views.xml
Labels: bot is merging ⏳

#909 [12.0][FIX] hr_expense_payment_difference, correct initial amount to pay
  hr_expense_payment_difference/__init__.py
  hr_expense_payment_difference/models/__init__.py
  hr_expense_payment_difference/models/hr_expense.py
  hr_expense_payment_difference/wizards/__init__.py
  hr_expense_payment_difference/wizards/hr_expense_sheet_register_payment.py
Labels: approved, bot is merging ⏳

#907 MIG] hr_employee_lastnames: Migration to 13.0
  hr_employee_lastnames/:q
  hr_employee_lastnames/README.rst
  hr_employee_lastnames/__init__.py
  hr_employee_lastnames/__manifest__.py
  hr_employee_lastnames/hook.py
  hr_employee_lastnames/i18n/es.po
  hr_employee_lastnames/i18n/hr_employee_lastnames.pot
  hr_employee_lastnames/models/__init__.py
  hr_employee_lastnames/models/hr_employee.py
  hr_employee_lastnames/readme/CONTRIBUTORS.rst
  hr_employee_lastnames/readme/DESCRIPTION.rst
  hr_employee_lastnames/readme/USAGE.rst
  hr_employee_lastnames/static/description/icon.png
  hr_employee_lastnames/static/description/index.html
  hr_employee_lastnames/tests/__init__.py
  hr_employee_lastnames/tests/test_hr_employee_lastnames.py
  hr_employee_lastnames/views/hr_views.xml
Labels: bot is merging ⏳

#911 [MIG] hr_employee_firstname: Migration to 14.0
  hr_employee_firstname/README.rst
  hr_employee_firstname/__init__.py
  hr_employee_firstname/__manifest__.py
  hr_employee_firstname/i18n/ar.po
  hr_employee_firstname/i18n/cs_CZ.po
  hr_employee_firstname/i18n/de.po
  hr_employee_firstname/i18n/es.po
  hr_employee_firstname/i18n/fa.po
  hr_employee_firstname/i18n/fi.po
  hr_employee_firstname/i18n/fr.po
  hr_employee_firstname/i18n/hr.po
  hr_employee_firstname/i18n/hr_HR.po
  hr_employee_firstname/i18n/hr_employee_firstname.pot
  hr_employee_firstname/i18n/it.po
  hr_employee_firstname/i18n/lt.po
  hr_employee_firstname/i18n/nl_NL.po
  hr_employee_firstname/i18n/pt_BR.po
  hr_employee_firstname/i18n/ro.po
  hr_employee_firstname/i18n/sl.po
  hr_employee_firstname/init_hook.py
  hr_employee_firstname/models/__init__.py
  hr_employee_firstname/models/hr_employee.py
  hr_employee_firstname/readme/CONTRIBUTORS.rst
  hr_employee_firstname/readme/DESCRIPTION.rst
  hr_employee_firstname/readme/USAGE.rst
  hr_employee_firstname/static/description/icon.png
  hr_employee_firstname/static/description/index.html
  hr_employee_firstname/tests/__init__.py
  hr_employee_firstname/tests/test_hr_employee_firstname.py
  hr_employee_firstname/views/hr_view.xml
Labels: bot is merging ⏳

#912 [MIG] hr_employee_lastnames: Migration to 14.0
  hr_employee_lastnames/README.rst
  hr_employee_lastnames/__init__.py
  hr_employee_lastnames/__manifest__.py
  hr_employee_lastnames/hook.py
  hr_employee_lastnames/i18n/es.po
  hr_employee_lastnames/i18n/hr_employee_lastnames.pot
  hr_employee_lastnames/models/__init__.py
  hr_employee_lastnames/models/hr_employee.py
  hr_employee_lastnames/readme/CONTRIBUTORS.rst
  hr_employee_lastnames/readme/DESCRIPTION.rst
  hr_employee_lastnames/readme/USAGE.rst
  hr_employee_lastnames/static/description/icon.png
  hr_employee_lastnames/static/description/index.html
  hr_employee_lastnames/tests/__init__.py
  hr_employee_lastnames/tests/test_hr_employee_lastnames.py
  hr_employee_lastnames/views/hr_views.xml
Labels: bot is merging ⏳

#888 [10.0][FIX] hr_holidays_compute_days: fix issues with timezone
  hr_holidays_compute_days/README.rst
  hr_holidays_compute_days/models/hr_employee.py
  hr_holidays_compute_days/models/hr_holidays.py
  hr_holidays_compute_days/models/resource_calendar.py
  hr_holidays_compute_days/tests/test_holidays_compute_days.py
Labels: approved, bot is merging ⏳, ready to merge

#896 [13.0][MIG] resource_hook
  resource_hook/README.rst
  resource_hook/__init__.py
  resource_hook/__manifest__.py
  resource_hook/hooks.py
  resource_hook/i18n/resource_hook.pot
  resource_hook/models/__init__.py
  resource_hook/models/resource_calendar.py
  resource_hook/models/resource_mixin.py
  resource_hook/readme/CONTRIBUTORS.rst
  resource_hook/readme/DESCRIPTION.rst
  resource_hook/readme/HISTORY.rst
  resource_hook/static/description/icon.png
  resource_hook/static/description/index.html
  setup/resource_hook/odoo/addons/resource_hook
  setup/resource_hook/setup.py
Labels: approved, bot is merging ⏳

#833 [12.0][IMP] hr_attendance_rfid: Add record rule
  hr_attendance_rfid/__manifest__.py
  hr_attendance_rfid/data/ir_rule.xml
  hr_attendance_rfid/migrations/12.0.1.1.0/post-migration.py
  hr_attendance_rfid/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳, ready to merge

#853 13.0 [mig] hr employee service contract
  hr_employee_service_contract/README.rst
  hr_employee_service_contract/__init__.py
  hr_employee_service_contract/__manifest__.py
  hr_employee_service_contract/i18n/de.po
  hr_employee_service_contract/i18n/es.po
  hr_employee_service_contract/i18n/fr.po
  hr_employee_service_contract/i18n/hr_employee_service_contract.pot
  hr_employee_service_contract/models/__init__.py
  hr_employee_service_contract/models/hr_employee.py
  hr_employee_service_contract/readme/CONTRIBUTORS.rst
  hr_employee_service_contract/readme/DESCRIPTION.rst
  hr_employee_service_contract/static/description/icon.png
  hr_employee_service_contract/static/description/index.html
  hr_employee_service_contract/tests/__init__.py
  hr_employee_service_contract/tests/test_hr_employee_service.py
  setup/hr_employee_service_contract/odoo/addons/hr_employee_service_contract
  setup/hr_employee_service_contract/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#784 [13.0][MIG] hr_employee_language
  hr_employee_language/README.rst
  hr_employee_language/__init__.py
  hr_employee_language/__manifest__.py
  hr_employee_language/models/__init__.py
  hr_employee_language/models/hr_employee.py
  hr_employee_language/models/hr_employee_language.py
  hr_employee_language/readme/CONTRIBUTORS.rst
  hr_employee_language/readme/DESCRIPTION.rst
  hr_employee_language/readme/USAGE.rst
  hr_employee_language/security/ir.model.access.csv
  hr_employee_language/static/description/icon.png
  hr_employee_language/static/description/index.html
  hr_employee_language/views/hr_employee.xml
  hr_employee_language/views/hr_employee_language.xml
  setup/hr_employee_language/odoo/addons/hr_employee_language
  setup/hr_employee_language/setup.py
Labels: approved, bot is merging ⏳, ready to merge
