Repository OCA/hr, pull requests merged in 2020-09, with the labels that each got.

#878 [13.0][IMP] hr_employee_firstname: ease extension
  hr_employee_firstname/models/hr_employee.py
Labels: approved, bot is merging ⏳, ready to merge

#881 [10.0][IMP] hr_employee_firstname: ease extension
  hr_employee_firstname/models/hr_employee.py
Labels: bot is merging ⏳

#883 [FIX] hr_period: Error in onchange is fixed.
  hr_period/models/hr_period.py
Labels: approved, bot is merging ⏳

#884 [ADD] hr_branch: Allow define branch on employee department
  hr_branch/README.rst
  hr_branch/__init__.py
  hr_branch/__manifest__.py
  hr_branch/i18n/es.po
  hr_branch/models/__init__.py
  hr_branch/models/hr_department.py
  hr_branch/readme/CONTRIBUTORS.rst
  hr_branch/readme/DESCRIPTION.rst
  hr_branch/static/description/index.html
  hr_branch/views/hr_department_views.xml
  hr_branch/views/hr_employee_views.xml
Labels: approved, bot is merging ⏳

#846 [12.0][ADD] hr_employee_ppe
  hr_employee_ppe/README.rst
  hr_employee_ppe/__init__.py
  hr_employee_ppe/__manifest__.py
  hr_employee_ppe/data/hr_employee_ppe_cron.xml
  hr_employee_ppe/demo/hr_employee_ppe_demo.xml
  hr_employee_ppe/i18n/hr_employee_ppe.pot
  hr_employee_ppe/models/__init__.py
  hr_employee_ppe/models/hr_employee.py
  hr_employee_ppe/models/hr_employee_ppe.py
  hr_employee_ppe/models/hr_employee_ppe_equipment.py
  hr_employee_ppe/readme/CONFIGURE.rst
  hr_employee_ppe/readme/CONTRIBUTORS.rst
  hr_employee_ppe/readme/DESCRIPTION.rst
  hr_employee_ppe/readme/INSTALL.rst
  hr_employee_ppe/readme/USAGE.rst
  hr_employee_ppe/security/hr_employee_ppe_equipment.xml
  hr_employee_ppe/security/hr_security.xml
  hr_employee_ppe/security/ir.model.access.csv
  hr_employee_ppe/static/description/icon.png
  hr_employee_ppe/views/hr_employee_ppe_equipment.xml
  hr_employee_ppe/views/hr_employee_ppe_view.xml
  hr_employee_ppe/views/hr_employee_view.xml
Labels: bot is merging ⏳

#879 [12.0][ENH] hr_expense_petty_cash - add journal in petty cash holder
  hr_expense_petty_cash/README.rst
  hr_expense_petty_cash/models/account_invoice.py
  hr_expense_petty_cash/models/hr_expense_sheet.py
  hr_expense_petty_cash/models/petty_cash.py
  hr_expense_petty_cash/readme/CONTRIBUTORS.rst
  hr_expense_petty_cash/readme/DESCRIPTION.rst
  hr_expense_petty_cash/readme/USAGE.rst
  hr_expense_petty_cash/static/description/index.html
  hr_expense_petty_cash/tests/test_hr_expense_petty_cash.py
  hr_expense_petty_cash/views/hr_expense_sheet_views.xml
  hr_expense_petty_cash/views/petty_cash_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#889 [FIX] hr_expense_advance_clearing: analytic account visibility
  hr_expense_advance_clearing/views/hr_expense_views.xml
Labels: approved, bot is merging ⏳

#885 [IMP] hr_expense_invoice: onchange invoice
  hr_expense_invoice/README.rst
  hr_expense_invoice/models/hr_expense.py
  hr_expense_invoice/wizard/expense_create_invoice.py
Labels: approved, bot is merging ⏳

#880 [ADD] hr_employee_lastnames: Added module to split Last Name in Father's Last Name and Mother's Last Name
  hr_employee_firstname/models/hr_employee.py
  hr_employee_lastnames/README.rst
  hr_employee_lastnames/__init__.py
  hr_employee_lastnames/__manifest__.py
  hr_employee_lastnames/hook.py
  hr_employee_lastnames/i18n/es.po
  hr_employee_lastnames/models/__init__.py
  hr_employee_lastnames/models/hr_employee.py
  hr_employee_lastnames/readme/CONTRIBUTORS.rst
  hr_employee_lastnames/readme/DESCRIPTION.rst
  hr_employee_lastnames/readme/USAGE.rst
  hr_employee_lastnames/static/description/icon.png
  hr_employee_lastnames/tests/__init__.py
  hr_employee_lastnames/tests/test_hr_employee_lastnames.py
  hr_employee_lastnames/views/hr_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#887 [ADD] hr_recruitment_security: New module
  hr_recruitment_security/__init__.py
  hr_recruitment_security/__manifest__.py
  hr_recruitment_security/readme/CONTRIBUTORS.rst
  hr_recruitment_security/readme/DESCRIPTION.rst
  hr_recruitment_security/security/security.xml
  hr_recruitment_security/static/description/icon.png
  hr_recruitment_security/tests/__init__.py
  hr_recruitment_security/tests/test_access_rights.py
Labels: approved, bot is merging ⏳, ready to merge

#733 [12.0][ADD] hr_expense_petty_cash_sequence
  hr_expense_petty_cash_sequence/README.rst
  hr_expense_petty_cash_sequence/__init__.py
  hr_expense_petty_cash_sequence/__manifest__.py
  hr_expense_petty_cash_sequence/data/hr_expense_data.xml
  hr_expense_petty_cash_sequence/models/__init__.py
  hr_expense_petty_cash_sequence/models/hr_expense_sheet.py
  hr_expense_petty_cash_sequence/readme/CONFIGURE.rst
  hr_expense_petty_cash_sequence/readme/CONTRIBUTORS.rst
  hr_expense_petty_cash_sequence/readme/DESCRIPTION.rst
  hr_expense_petty_cash_sequence/static/description/icon.png
  hr_expense_petty_cash_sequence/static/description/index.html
  hr_expense_petty_cash_sequence/tests/__init__.py
  hr_expense_petty_cash_sequence/tests/test_hr_expense_petty_cash_sequence.py
Labels: approved, ready to merge

#898 [13.0][UPD] Eficent -> ForgeFlow
  hr_employee_calendar_planning/README.rst
  hr_employee_calendar_planning/readme/CONTRIBUTORS.rst
  hr_employee_calendar_planning/static/description/index.html
Labels: approved, bot is merging ⏳
