Repository OCA/hr, pull requests merged in 2020-03, with the labels that each got.

#794 [13.0][MIG] hr_employee_age
  .isort.cfg
  hr_employee_age/README.rst
  hr_employee_age/__init__.py
  hr_employee_age/__manifest__.py
  hr_employee_age/i18n/ar.po
  hr_employee_age/i18n/cs_CZ.po
  hr_employee_age/i18n/de.po
  hr_employee_age/i18n/es.po
  hr_employee_age/i18n/fi.po
  hr_employee_age/i18n/fr.po
  hr_employee_age/i18n/hr.po
  hr_employee_age/i18n/hr_HR.po
  hr_employee_age/i18n/hr_employee_age.pot
  hr_employee_age/i18n/it.po
  hr_employee_age/i18n/lt.po
  hr_employee_age/i18n/nl_NL.po
  hr_employee_age/i18n/pt_BR.po
  hr_employee_age/i18n/ro.po
  hr_employee_age/i18n/sl.po
  hr_employee_age/models/__init__.py
  hr_employee_age/models/hr_employee.py
  hr_employee_age/readme/CONTRIBUTORS.rst
  hr_employee_age/readme/DESCRIPTION.rst
  hr_employee_age/readme/USAGE.rst
  hr_employee_age/static/description/icon.png
  hr_employee_age/static/description/index.html
  hr_employee_age/tests/__init__.py
  hr_employee_age/tests/test_hr_employee.py
  hr_employee_age/views/hr_employee.xml
Labels: approved, ready to merge

#511 [10.0][ADD] hr_public_holidays : Allow to change dates in wizard
  hr_public_holidays/README.rst
  hr_public_holidays/tests/test_public_holidays.py
  hr_public_holidays/wizards/public_holidays_next_year_wizard.py
  hr_public_holidays/wizards/public_holidays_next_year_wizard.xml
Labels: approved, ready to merge

#771 [13.0][MIG] hr_employee_phone_extension
  hr_employee_phone_extension/README.rst
  hr_employee_phone_extension/__init__.py
  hr_employee_phone_extension/__manifest__.py
  hr_employee_phone_extension/i18n/ar.po
  hr_employee_phone_extension/i18n/cs_CZ.po
  hr_employee_phone_extension/i18n/de.po
  hr_employee_phone_extension/i18n/es.po
  hr_employee_phone_extension/i18n/fi.po
  hr_employee_phone_extension/i18n/fr.po
  hr_employee_phone_extension/i18n/hr.po
  hr_employee_phone_extension/i18n/hr_HR.po
  hr_employee_phone_extension/i18n/hr_employee_phone_extension.pot
  hr_employee_phone_extension/i18n/it.po
  hr_employee_phone_extension/i18n/lt.po
  hr_employee_phone_extension/i18n/nl_NL.po
  hr_employee_phone_extension/i18n/pt_BR.po
  hr_employee_phone_extension/i18n/ro.po
  hr_employee_phone_extension/i18n/sl.po
  hr_employee_phone_extension/models/__init__.py
  hr_employee_phone_extension/models/hr_employee.py
  hr_employee_phone_extension/readme/CONTRIBUTORS.rst
  hr_employee_phone_extension/readme/DESCRIPTION.rst
  hr_employee_phone_extension/readme/INSTALL.rst
  hr_employee_phone_extension/readme/USAGE.rst
  hr_employee_phone_extension/static/description/icon.png
  hr_employee_phone_extension/static/description/index.html
  hr_employee_phone_extension/views/hr_employee_view.xml
Labels: approved, ready to merge

#767 [12.0][MIG] hr_emergency_contact
  hr_employee_emergency_contact/README.rst
  hr_employee_emergency_contact/__init__.py
  hr_employee_emergency_contact/__manifest__.py
  hr_employee_emergency_contact/i18n/ar.po
  hr_employee_emergency_contact/i18n/cs_CZ.po
  hr_employee_emergency_contact/i18n/de.po
  hr_employee_emergency_contact/i18n/es.po
  hr_employee_emergency_contact/i18n/fi.po
  hr_employee_emergency_contact/i18n/fr.po
  hr_employee_emergency_contact/i18n/hr.po
  hr_employee_emergency_contact/i18n/hr_HR.po
  hr_employee_emergency_contact/i18n/hr_emergency_contact.pot
  hr_employee_emergency_contact/i18n/it.po
  hr_employee_emergency_contact/i18n/lt.po
  hr_employee_emergency_contact/i18n/nl_NL.po
  hr_employee_emergency_contact/i18n/pt_BR.po
  hr_employee_emergency_contact/i18n/ro.po
  hr_employee_emergency_contact/i18n/sl.po
  hr_employee_emergency_contact/models/__init__.py
  hr_employee_emergency_contact/models/hr_employee.py
  hr_employee_emergency_contact/readme/CONTRIBUTORS.rst
  hr_employee_emergency_contact/readme/DESCRIPTION.rst
  hr_employee_emergency_contact/readme/INSTALL.rst
  hr_employee_emergency_contact/readme/USAGE.rst
  hr_employee_emergency_contact/static/description/icon.png
  hr_employee_emergency_contact/static/description/index.html
  hr_employee_emergency_contact/views/hr_employee_views.xml
Labels: approved, ready to merge

#645 [11.0][MIG] hr_contract_default_trial_length
  hr_contract_default_trial_length/README.rst
  hr_contract_default_trial_length/__init__.py
  hr_contract_default_trial_length/__manifest__.py
  hr_contract_default_trial_length/i18n/ar.po
  hr_contract_default_trial_length/i18n/cs_CZ.po
  hr_contract_default_trial_length/i18n/de.po
  hr_contract_default_trial_length/i18n/es.po
  hr_contract_default_trial_length/i18n/fi.po
  hr_contract_default_trial_length/i18n/fr.po
  hr_contract_default_trial_length/i18n/hi_IN.po
  hr_contract_default_trial_length/i18n/hr.po
  hr_contract_default_trial_length/i18n/hr_contract_default_trial_length.pot
  hr_contract_default_trial_length/i18n/it.po
  hr_contract_default_trial_length/i18n/lt.po
  hr_contract_default_trial_length/i18n/nl_NL.po
  hr_contract_default_trial_length/i18n/pt_BR.po
  hr_contract_default_trial_length/i18n/ro.po
  hr_contract_default_trial_length/i18n/sl.po
  hr_contract_default_trial_length/models/__init__.py
  hr_contract_default_trial_length/models/hr_contract.py
  hr_contract_default_trial_length/models/hr_contract_type.py
  hr_contract_default_trial_length/readme/CONFIGURE.rst
  hr_contract_default_trial_length/readme/CONTRIBUTORS.rst
  hr_contract_default_trial_length/readme/DESCRIPTION.rst
  hr_contract_default_trial_length/readme/INSTALL.rst
  hr_contract_default_trial_length/readme/ROADMAP.rst
  hr_contract_default_trial_length/readme/USAGE.rst
  hr_contract_default_trial_length/static/description/icon.png
  hr_contract_default_trial_length/tests/__init__.py
  hr_contract_default_trial_length/tests/test_trial_length.py
  hr_contract_default_trial_length/views/hr_contract_type.xml
Labels: approved, ready to merge

#701 [12.0][MIG] hr_employee_medical_examination
  hr_employee_medical_examination/README.rst
  hr_employee_medical_examination/__init__.py
  hr_employee_medical_examination/__manifest__.py
  hr_employee_medical_examination/i18n/es.po
  hr_employee_medical_examination/i18n/hr_employee_medical_examination.pot
  hr_employee_medical_examination/models/__init__.py
  hr_employee_medical_examination/models/hr_employee.py
  hr_employee_medical_examination/models/hr_employee_medical_examination.py
  hr_employee_medical_examination/readme/CONTRIBUTORS.rst
  hr_employee_medical_examination/readme/DESCRIPTION.rst
  hr_employee_medical_examination/readme/USAGE.rst
  hr_employee_medical_examination/security/hr_employee_medical_examination_security.xml
  hr_employee_medical_examination/security/ir.model.access.csv
  hr_employee_medical_examination/static/description/icon.png
  hr_employee_medical_examination/static/description/index.html
  hr_employee_medical_examination/tests/__init__.py
  hr_employee_medical_examination/tests/test_hr_employee_medical_examination.py
  hr_employee_medical_examination/views/hr_employee_medical_examination_views.xml
  hr_employee_medical_examination/views/hr_employee_views.xml
  hr_employee_medical_examination/wizards/__init__.py
  hr_employee_medical_examination/wizards/wizard_generate_medical_examination.py
  hr_employee_medical_examination/wizards/wizard_generate_medical_examination.xml
Labels: approved, ready to merge

#765 [11.0][MIG] hr_expense_sequence: backport from v12 to v11
  hr_expense_sequence/README.rst
  hr_expense_sequence/__init__.py
  hr_expense_sequence/__manifest__.py
  hr_expense_sequence/data/hr_expense_data.xml
  hr_expense_sequence/hooks.py
  hr_expense_sequence/i18n/cs_CZ.po
  hr_expense_sequence/i18n/de.po
  hr_expense_sequence/i18n/es.po
  hr_expense_sequence/i18n/fi.po
  hr_expense_sequence/i18n/fr.po
  hr_expense_sequence/i18n/hr.po
  hr_expense_sequence/i18n/hr_expense_sequence.pot
  hr_expense_sequence/i18n/it.po
  hr_expense_sequence/i18n/nl_NL.po
  hr_expense_sequence/i18n/pt_BR.po
  hr_expense_sequence/i18n/sl.po
  hr_expense_sequence/models/__init__.py
  hr_expense_sequence/models/hr_expense_sheet.py
  hr_expense_sequence/readme/CONFIGURE.rst
  hr_expense_sequence/readme/CONTRIBUTORS.rst
  hr_expense_sequence/readme/DESCRIPTION.rst
  hr_expense_sequence/report/report_expense_sheet.xml
  hr_expense_sequence/static/description/icon.png
  hr_expense_sequence/static/description/index.html
  hr_expense_sequence/tests/__init__.py
  hr_expense_sequence/tests/test_hr_expense_sequence.py
  hr_expense_sequence/views/hr_expense_expense_view.xml
Labels: approved

#798 [12.0][ADD] hr_contract_rate: flexible wage
  hr_contract_rate/__init__.py
  hr_contract_rate/__manifest__.py
  hr_contract_rate/hooks.py
  hr_contract_rate/models/__init__.py
  hr_contract_rate/models/hr_contract.py
  hr_contract_rate/readme/CONTRIBUTORS.rst
  hr_contract_rate/readme/DESCRIPTION.rst
  hr_contract_rate/readme/USAGE.rst
  hr_contract_rate/tests/__init__.py
  hr_contract_rate/tests/test_hr_contract_rate.py
  hr_contract_rate/views/hr_contract.xml
Labels: approved, ready to merge

#800 [12.0][ADD] hr_contract_document: attach documents to contracts
  hr_contract_document/__init__.py
  hr_contract_document/__manifest__.py
  hr_contract_document/models/__init__.py
  hr_contract_document/models/hr_contract.py
  hr_contract_document/readme/CONTRIBUTORS.rst
  hr_contract_document/readme/DESCRIPTION.rst
  hr_contract_document/tests/__init__.py
  hr_contract_document/tests/test_hr_contract_document.py
  hr_contract_document/views/hr_contract.xml
  hr_contract_document/views/ir_attachment.xml
Labels: approved, ready to merge

#635 [12.0][ADD] hr_expense_payment_difference
  hr_expense_payment_difference/README.rst
  hr_expense_payment_difference/__init__.py
  hr_expense_payment_difference/__manifest__.py
  hr_expense_payment_difference/models/__init__.py
  hr_expense_payment_difference/models/account_payment.py
  hr_expense_payment_difference/models/hr_expense_sheet_register_payment.py
  hr_expense_payment_difference/readme/CONTRIBUTORS.rst
  hr_expense_payment_difference/readme/DESCRIPTION.rst
  hr_expense_payment_difference/readme/USAGE.rst
  hr_expense_payment_difference/static/description/index.html
  hr_expense_payment_difference/tests/__init__.py
  hr_expense_payment_difference/tests/test_hr_expense_payment_difference.py
  hr_expense_payment_difference/wizards/hr_expense_sheet_register_payment.xml
Labels: approved, merged 🎉, ready to merge

#783 [12.0][MIG] hr_employee_language
  hr_employee_language/README.rst
  hr_employee_language/__init__.py
  hr_employee_language/__manifest__.py
  hr_employee_language/models/__init__.py
  hr_employee_language/models/hr_employee.py
  hr_employee_language/models/hr_employee_language.py
  hr_employee_language/readme/CONTRIBUTORS.rst
  hr_employee_language/readme/DESCRIPTION.rst
  hr_employee_language/readme/USAGE.rst
  hr_employee_language/security/ir.model.access.csv
  hr_employee_language/static/description/icon.png
  hr_employee_language/static/description/index.html
  hr_employee_language/views/hr_employee.xml
  hr_employee_language/views/hr_employee_language.xml
Labels: approved, ready to merge

#806 [13.0][FIX] hr_employee_firstname : testscript
  hr_employee_firstname/tests/test_hr_employee_firstname.py
Labels: approved
