Repository OCA/hr, pull requests merged in 2021-12, with the labels that each got.

#1055 [13.0][IMP] hr_recruitment_security: Improve tests
  hr_recruitment_security/tests/test_access_rights.py
Labels: approved, bot is merging ⏳

#963 [REF] hr_expense_receipt_require: improve usage instructions
  hr_expense_receipt_require/readme/USAGE.rst
Labels: bug, bot is merging ⏳

#1056 [12.0][PORT] hr_expense_journal from 14.0
  hr_expense_journal/README.rst
  hr_expense_journal/__init__.py
  hr_expense_journal/__manifest__.py
  hr_expense_journal/i18n/hr_expense_journal.pot
  hr_expense_journal/models/__init__.py
  hr_expense_journal/models/hr_expense.py
  hr_expense_journal/readme/CONTRIBUTORS.rst
  hr_expense_journal/readme/DESCRIPTION.rst
  hr_expense_journal/readme/USAGE.rst
  hr_expense_journal/static/description/icon.png
  hr_expense_journal/static/description/index.html
  hr_expense_journal/views/hr_expense_views.xml
Labels: approved, bot is merging ⏳

#1027 [IMP] hr_employee_ppe: adapt it to new module hr_personal_equipment_request
  hr_employee_ppe/README.rst
  hr_employee_ppe/__manifest__.py
  hr_employee_ppe/data/hr_employee_ppe_cron.xml
  hr_employee_ppe/demo/hr_employee_ppe_demo.xml
  hr_employee_ppe/i18n/hr_employee_ppe.pot
  hr_employee_ppe/i18n/pt_BR.po
  hr_employee_ppe/migrations/12.0.2.0.0/post-migration.py
  hr_employee_ppe/models/__init__.py
  hr_employee_ppe/models/hr_employee.py
  hr_employee_ppe/models/hr_employee_ppe.py
  hr_employee_ppe/models/hr_employee_ppe_equipment.py
  hr_employee_ppe/models/hr_personal_equipment.py
  hr_employee_ppe/models/hr_personal_equipment_request.py
  hr_employee_ppe/models/product_template.py
  hr_employee_ppe/readme/CONFIGURE.rst
  hr_employee_ppe/readme/CONTRIBUTORS.rst
  hr_employee_ppe/readme/CREDITS.rst
  hr_employee_ppe/readme/DESCRIPTION.rst
  hr_employee_ppe/readme/USAGE.rst
  hr_employee_ppe/reports/hr_employee_ppe_report.xml
  hr_employee_ppe/reports/hr_employee_ppe_report_template.xml
  hr_employee_ppe/security/hr_employee_ppe_equipment.xml
  hr_employee_ppe/security/hr_security.xml
  hr_employee_ppe/security/ir.model.access.csv
  hr_employee_ppe/static/description/index.html
  hr_employee_ppe/tests/test_hr_employee_ppe.py
  hr_employee_ppe/views/hr_employee_ppe_equipment.xml
  hr_employee_ppe/views/hr_employee_ppe_view.xml
  hr_employee_ppe/views/hr_employee_view.xml
  hr_employee_ppe/views/hr_personal_equipment.xml
  hr_employee_ppe/views/hr_personal_equipment_request.xml
  hr_employee_ppe/views/product_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#1061 [14.0][MIG] hr_personal_equipment_request
  hr_personal_equipment_request/README.rst
  hr_personal_equipment_request/__init__.py
  hr_personal_equipment_request/__manifest__.py
  hr_personal_equipment_request/i18n/hr_personal_equipment_request.pot
  hr_personal_equipment_request/models/__init__.py
  hr_personal_equipment_request/models/hr_employee.py
  hr_personal_equipment_request/models/hr_personal_equipment.py
  hr_personal_equipment_request/models/hr_personal_equipment_request.py
  hr_personal_equipment_request/models/product_template.py
  hr_personal_equipment_request/readme/CONTRIBUTORS.rst
  hr_personal_equipment_request/readme/DESCRIPTION.rst
  hr_personal_equipment_request/readme/USAGE.rst
  hr_personal_equipment_request/security/hr_personal_equipment_request_security.xml
  hr_personal_equipment_request/security/ir.model.access.csv
  hr_personal_equipment_request/static/description/icon.png
  hr_personal_equipment_request/static/description/index.html
  hr_personal_equipment_request/tests/__init__.py
  hr_personal_equipment_request/tests/test_hr_personal_equipment_request.py
  hr_personal_equipment_request/views/hr_employee.xml
  hr_personal_equipment_request/views/hr_personal_equipment.xml
  hr_personal_equipment_request/views/hr_personal_equipment_request.xml
  hr_personal_equipment_request/views/product_template.xml
  setup/hr_personal_equipment_request/odoo/addons/hr_personal_equipment_request
  setup/hr_personal_equipment_request/setup.py
Labels: approved, bot is merging ⏳
