Repository OCA/hr, pull requests merged in 2021-01, with the labels that each got.

#954 [13.0] [FIX] hr_employee_lastnames: Delete :q
  hr_employee_lastnames/:q
Labels: approved

#827 [10.0] .gitignore: add !static/lib/ as per oca rules
  .gitignore
Labels: approved, bot is merging ⏳, ready to merge

#828 [11.0] .gitignore: add !static/lib/ as per oca rules
  .gitignore
Labels: approved, bot is merging ⏳, ready to merge

#826 [13.0] .gitignore: add !static/lib/ as per oca rules
  .gitignore
Labels: approved, bot is merging ⏳

#957 [12.0][FIX] name duplicate with module hr_expense_advance_clearing
  hr_expense_advance_clearing/models/hr_expense.py
  hr_expense_advance_clearing/models/hr_expense_sheet.py
  hr_expense_advance_clearing/tests/test_hr_expense_advance_clearing.py
  hr_expense_advance_clearing/views/hr_expense_views.xml
  hr_expense_advance_clearing/wizard/hr_expense_sheet_register_payment.py
  hr_expense_payment_difference/models/hr_expense.py
  hr_expense_payment_difference/wizards/hr_expense_sheet_register_payment.py
Labels: approved, bot is merging ⏳

#913 [13.0][MIG] hr_contract_reference
  hr_contract_reference/README.rst
  hr_contract_reference/__init__.py
  hr_contract_reference/__manifest__.py
  hr_contract_reference/data/hr_contract_sequence.xml
  hr_contract_reference/i18n/ar.po
  hr_contract_reference/i18n/cs_CZ.po
  hr_contract_reference/i18n/de.po
  hr_contract_reference/i18n/es.po
  hr_contract_reference/i18n/fi.po
  hr_contract_reference/i18n/fr.po
  hr_contract_reference/i18n/hi_IN.po
  hr_contract_reference/i18n/hr.po
  hr_contract_reference/i18n/hr_contract_reference.pot
  hr_contract_reference/i18n/it.po
  hr_contract_reference/i18n/lt.po
  hr_contract_reference/i18n/nl_NL.po
  hr_contract_reference/i18n/pt_BR.po
  hr_contract_reference/i18n/ro.po
  hr_contract_reference/i18n/sl.po
  hr_contract_reference/models/__init__.py
  hr_contract_reference/models/hr_contract.py
  hr_contract_reference/readme/CONFIGURE.rst
  hr_contract_reference/readme/CONTRIBUTORS.rst
  hr_contract_reference/readme/DESCRIPTION.rst
  hr_contract_reference/readme/USAGE.rst
  hr_contract_reference/static/description/icon.png
  hr_contract_reference/static/description/index.html
  hr_contract_reference/tests/__init__.py
  hr_contract_reference/tests/test_contract_reference.py
  hr_contract_reference/views/hr_contract_view.xml
  setup/hr_contract_reference/odoo/addons/hr_contract_reference
  setup/hr_contract_reference/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#956 13.0 mig hr contract rate
  hr_contract_rate/README.rst
  hr_contract_rate/__init__.py
  hr_contract_rate/__manifest__.py
  hr_contract_rate/hooks.py
  hr_contract_rate/i18n/hr_contract_rate.pot
  hr_contract_rate/models/__init__.py
  hr_contract_rate/models/hr_contract.py
  hr_contract_rate/readme/CONTRIBUTORS.rst
  hr_contract_rate/readme/DESCRIPTION.rst
  hr_contract_rate/readme/USAGE.rst
  hr_contract_rate/static/description/icon.png
  hr_contract_rate/static/description/index.html
  hr_contract_rate/tests/__init__.py
  hr_contract_rate/tests/test_hr_contract_rate.py
  hr_contract_rate/views/hr_contract.xml
  setup/hr_contract_rate/odoo/addons/hr_contract_rate
  setup/hr_contract_rate/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#960 [12.0][FIX] hr_attendance_report_theoretical_time: Remove search_default_my (context) when hr_attendance_theoretical_action is load from wizard
  hr_attendance_report_theoretical_time/readme/CONTRIBUTORS.rst
  hr_attendance_report_theoretical_time/wizards/wizard_theoretical_time.py
Labels: approved, bot is merging ⏳

#961 [12.0][IMP] hr_attendance_report_theoretical_time: Add department_id in report
  hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report.py
  hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report_views.xml
Labels: approved, bot is merging ⏳

#962 [IMP] Expense Product - Attachment required issue for bulk import (#4719)
  hr_expense_receipt_require/__manifest__.py
  hr_expense_receipt_require/models/hr_expense.py
  hr_expense_receipt_require/models/product_template.py
  hr_expense_receipt_require/readme/CONFIGURE.rst
  hr_expense_receipt_require/readme/USAGE.rst
  hr_expense_receipt_require/security/security_view.xml
  hr_expense_receipt_require/tests/test_hr_expense.py
  hr_expense_receipt_require/views/hr_expense_sheet_form.xml
Labels: approved
