Repository OCA/hr, pull requests merged in 2021-03, with the labels that each got.

#978 [14.0][MIG] hr_contract_reference: Migration to 14.0
  hr_contract_reference/README.rst
  hr_contract_reference/__init__.py
  hr_contract_reference/__manifest__.py
  hr_contract_reference/data/hr_contract_sequence.xml
  hr_contract_reference/i18n/ar.po
  hr_contract_reference/i18n/cs_CZ.po
  hr_contract_reference/i18n/de.po
  hr_contract_reference/i18n/es.po
  hr_contract_reference/i18n/fi.po
  hr_contract_reference/i18n/fr.po
  hr_contract_reference/i18n/hi_IN.po
  hr_contract_reference/i18n/hr.po
  hr_contract_reference/i18n/hr_contract_reference.pot
  hr_contract_reference/i18n/it.po
  hr_contract_reference/i18n/lt.po
  hr_contract_reference/i18n/nl_NL.po
  hr_contract_reference/i18n/pt_BR.po
  hr_contract_reference/i18n/ro.po
  hr_contract_reference/i18n/sl.po
  hr_contract_reference/models/__init__.py
  hr_contract_reference/models/hr_contract.py
  hr_contract_reference/readme/CONFIGURE.rst
  hr_contract_reference/readme/CONTRIBUTORS.rst
  hr_contract_reference/readme/DESCRIPTION.rst
  hr_contract_reference/readme/USAGE.rst
  hr_contract_reference/static/description/icon.png
  hr_contract_reference/static/description/index.html
  hr_contract_reference/tests/__init__.py
  hr_contract_reference/tests/test_contract_reference.py
  setup/hr_contract_reference/odoo/addons/hr_contract_reference
  setup/hr_contract_reference/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#929 [14.0][MIG] hr_employee_phone_extension
  hr_employee_phone_extension/README.rst
  hr_employee_phone_extension/__init__.py
  hr_employee_phone_extension/__manifest__.py
  hr_employee_phone_extension/i18n/ar.po
  hr_employee_phone_extension/i18n/cs_CZ.po
  hr_employee_phone_extension/i18n/de.po
  hr_employee_phone_extension/i18n/es.po
  hr_employee_phone_extension/i18n/fi.po
  hr_employee_phone_extension/i18n/fr.po
  hr_employee_phone_extension/i18n/hr.po
  hr_employee_phone_extension/i18n/hr_HR.po
  hr_employee_phone_extension/i18n/hr_employee_phone_extension.pot
  hr_employee_phone_extension/i18n/it.po
  hr_employee_phone_extension/i18n/lt.po
  hr_employee_phone_extension/i18n/nl_NL.po
  hr_employee_phone_extension/i18n/pt_BR.po
  hr_employee_phone_extension/i18n/ro.po
  hr_employee_phone_extension/i18n/sl.po
  hr_employee_phone_extension/models/__init__.py
  hr_employee_phone_extension/models/hr_employee.py
  hr_employee_phone_extension/readme/CONTRIBUTORS.rst
  hr_employee_phone_extension/readme/DESCRIPTION.rst
  hr_employee_phone_extension/readme/INSTALL.rst
  hr_employee_phone_extension/readme/USAGE.rst
  hr_employee_phone_extension/static/description/icon.png
  hr_employee_phone_extension/static/description/index.html
  hr_employee_phone_extension/views/hr_employee_view.xml
  setup/hr_employee_phone_extension/odoo/addons/hr_employee_phone_extension
  setup/hr_employee_phone_extension/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#933 [14.0][MIG] hr_contract_multi_job
  hr_contract_multi_job/README.rst
  hr_contract_multi_job/__init__.py
  hr_contract_multi_job/__manifest__.py
  hr_contract_multi_job/i18n/ar.po
  hr_contract_multi_job/i18n/de.po
  hr_contract_multi_job/i18n/es.po
  hr_contract_multi_job/i18n/fi.po
  hr_contract_multi_job/i18n/fr.po
  hr_contract_multi_job/i18n/hr_contract_multi_job.pot
  hr_contract_multi_job/i18n/it.po
  hr_contract_multi_job/i18n/pt_BR.po
  hr_contract_multi_job/i18n/ro.po
  hr_contract_multi_job/i18n/sl.po
  hr_contract_multi_job/models/__init__.py
  hr_contract_multi_job/models/hr_contract.py
  hr_contract_multi_job/models/hr_contract_job.py
  hr_contract_multi_job/models/hr_job.py
  hr_contract_multi_job/readme/CONTRIBUTORS.rst
  hr_contract_multi_job/readme/DESCRIPTION.rst
  hr_contract_multi_job/readme/USAGE.rst
  hr_contract_multi_job/security/ir.model.access.csv
  hr_contract_multi_job/static/description/icon.png
  hr_contract_multi_job/static/description/index.html
  hr_contract_multi_job/tests/__init__.py
  hr_contract_multi_job/tests/test_hr_contract_multi_jobs.py
  hr_contract_multi_job/views/hr_contract_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#974 [13.0][MIG] hr_employee_ppe: Migration to 13.0
  hr_employee_ppe/README.rst
  hr_employee_ppe/__init__.py
  hr_employee_ppe/__manifest__.py
  hr_employee_ppe/data/hr_employee_ppe_cron.xml
  hr_employee_ppe/demo/hr_employee_ppe_demo.xml
  hr_employee_ppe/i18n/hr_employee_ppe.pot
  hr_employee_ppe/i18n/pt_BR.po
  hr_employee_ppe/models/__init__.py
  hr_employee_ppe/models/hr_employee.py
  hr_employee_ppe/models/hr_employee_ppe.py
  hr_employee_ppe/models/hr_employee_ppe_equipment.py
  hr_employee_ppe/readme/CONFIGURE.rst
  hr_employee_ppe/readme/CONTRIBUTORS.rst
  hr_employee_ppe/readme/CREDITS.rst
  hr_employee_ppe/readme/DESCRIPTION.rst
  hr_employee_ppe/readme/INSTALL.rst
  hr_employee_ppe/readme/USAGE.rst
  hr_employee_ppe/security/hr_employee_ppe_equipment.xml
  hr_employee_ppe/security/hr_security.xml
  hr_employee_ppe/security/ir.model.access.csv
  hr_employee_ppe/static/description/banner.png
  hr_employee_ppe/static/description/icon.png
  hr_employee_ppe/static/description/index.html
  hr_employee_ppe/tests/__init__.py
  hr_employee_ppe/tests/test_hr_employee_ppe.py
  hr_employee_ppe/views/hr_employee_ppe_equipment.xml
  hr_employee_ppe/views/hr_employee_ppe_view.xml
  hr_employee_ppe/views/hr_employee_view.xml
  setup/hr_employee_ppe/odoo/addons/hr_employee_ppe
  setup/hr_employee_ppe/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#983 [13.0][MIG] hr_recruitment_security: Migration to 13.0
  hr_recruitment_security/README.rst
  hr_recruitment_security/__init__.py
  hr_recruitment_security/__manifest__.py
  hr_recruitment_security/i18n/hr_recruitment_security.pot
  hr_recruitment_security/readme/CONTRIBUTORS.rst
  hr_recruitment_security/readme/DESCRIPTION.rst
  hr_recruitment_security/security/security.xml
  hr_recruitment_security/static/description/icon.png
  hr_recruitment_security/static/description/index.html
  hr_recruitment_security/tests/__init__.py
  hr_recruitment_security/tests/test_access_rights.py
  hr_recruitment_security/views/hr_job_views.xml
  setup/hr_recruitment_security/odoo/addons/hr_recruitment_security
  setup/hr_recruitment_security/setup.py
Labels: approved, bot is merging ⏳

#985 [12.0][FIX+imp] hr_expense_invoice: Set empty tax_ids when create_invoice wizard + Remove expense_create_invoice wizard according to shee
  hr_expense_invoice/__init__.py
  hr_expense_invoice/__manifest__.py
  hr_expense_invoice/migrations/12.0.1.4.0/pre-migration.py
  hr_expense_invoice/models/hr_expense_sheet.py
  hr_expense_invoice/tests/test_hr_expense_invoice.py
  hr_expense_invoice/views/hr_expense_views.xml
  hr_expense_invoice/wizard/__init__.py
  hr_expense_invoice/wizard/expense_create_invoice.py
  hr_expense_invoice/wizard/expense_create_invoice.xml
  hr_expense_invoice/wizard/hr_expense_sheet_register_payment.py
Labels: bot is merging ⏳
