Repository OCA/hr, pull requests merged in 2021-05, with the labels that each got.

#926 Remove `sudo` keyword
  .travis.yml
Labels: approved, ready to merge

#574 [ADD] hr_calendar_multiweek
  hr_calendar_multiweek/README.rst
  hr_calendar_multiweek/__init__.py
  hr_calendar_multiweek/__manifest__.py
  hr_calendar_multiweek/models/__init__.py
  hr_calendar_multiweek/models/resource_calendar.py
  hr_calendar_multiweek/readme/CONTRIBUTORS.rst
  hr_calendar_multiweek/readme/DESCRIPTION.rst
  hr_calendar_multiweek/readme/USAGE.rst
  hr_calendar_multiweek/static/description/icon.png
  hr_calendar_multiweek/static/description/index.html
  hr_calendar_multiweek/tests/__init__.py
  hr_calendar_multiweek/tests/test_resource_calendar.py
  hr_calendar_multiweek/views/resource_calendar.xml
Labels: approved, bot is merging ⏳, ready to merge

#915 [13.0][MIG]hr_contract_document
  hr_contract_document/README.rst
  hr_contract_document/__init__.py
  hr_contract_document/__manifest__.py
  hr_contract_document/i18n/hr_contract_document.pot
  hr_contract_document/models/__init__.py
  hr_contract_document/models/hr_contract.py
  hr_contract_document/readme/CONTRIBUTORS.rst
  hr_contract_document/readme/DESCRIPTION.rst
  hr_contract_document/static/description/icon.png
  hr_contract_document/static/description/index.html
  hr_contract_document/tests/__init__.py
  hr_contract_document/tests/test_hr_contract_document.py
  hr_contract_document/views/hr_contract.xml
  hr_contract_document/views/ir_attachment.xml
  setup/hr_contract_document/odoo/addons/hr_contract_document
  setup/hr_contract_document/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#924 [12.0][IMP] hr_expense_petty_cash : add active/inactive
  hr_expense_petty_cash/models/petty_cash.py
  hr_expense_petty_cash/views/petty_cash_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#930 [14.0][MIG] hr_contract_currency
  hr_contract_currency/README.rst
  hr_contract_currency/__init__.py
  hr_contract_currency/__manifest__.py
  hr_contract_currency/i18n/fr.po
  hr_contract_currency/i18n/hr_contract_currency.pot
  hr_contract_currency/models/__init__.py
  hr_contract_currency/models/hr_contract.py
  hr_contract_currency/readme/CONTRIBUTORS.rst
  hr_contract_currency/readme/DESCRIPTION.rst
  hr_contract_currency/static/description/icon.png
  hr_contract_currency/static/description/index.html
  hr_contract_currency/tests/__init__.py
  hr_contract_currency/tests/test_hr_contract_currency.py
  hr_contract_currency/views/hr_contract.xml
  setup/hr_contract_currency/odoo/addons/hr_contract_currency
  setup/hr_contract_currency/setup.py
Labels: approved, bot is merging ⏳
