Repository OCA/hr, pull requests merged in 2021-07, with the labels that each got.

#999 [14.0] [MIG] hr_employee_birth_name
  hr_employee_birth_name/README.rst
  hr_employee_birth_name/__init__.py
  hr_employee_birth_name/__manifest__.py
  hr_employee_birth_name/i18n/ar.po
  hr_employee_birth_name/i18n/cs_CZ.po
  hr_employee_birth_name/i18n/de.po
  hr_employee_birth_name/i18n/es.po
  hr_employee_birth_name/i18n/fi.po
  hr_employee_birth_name/i18n/fr.po
  hr_employee_birth_name/i18n/hr.po
  hr_employee_birth_name/i18n/hr_HR.po
  hr_employee_birth_name/i18n/hr_employee_birth_name.pot
  hr_employee_birth_name/i18n/it.po
  hr_employee_birth_name/i18n/lt.po
  hr_employee_birth_name/i18n/nl_NL.po
  hr_employee_birth_name/i18n/pt_BR.po
  hr_employee_birth_name/i18n/ro.po
  hr_employee_birth_name/i18n/sl.po
  hr_employee_birth_name/models/__init__.py
  hr_employee_birth_name/models/hr_employee.py
  hr_employee_birth_name/readme/CONTRIBUTORS.rst
  hr_employee_birth_name/readme/DESCRIPTION.rst
  hr_employee_birth_name/readme/INSTALL.rst
  hr_employee_birth_name/readme/USAGE.rst
  hr_employee_birth_name/static/description/icon.png
  hr_employee_birth_name/static/description/index.html
  hr_employee_birth_name/views/hr_employee_view.xml
  setup/hr_employee_birth_name/odoo/addons/hr_employee_birth_name
  setup/hr_employee_birth_name/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1007 [13.0][FIX] hr_employee_calendar_planning: Prevent disable resource.calendar when is related to some employee
  hr_employee_calendar_planning/i18n/es.po
  hr_employee_calendar_planning/i18n/hr_employee_calendar_planning.pot
  hr_employee_calendar_planning/models/resource_calendar.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
Labels: approved, bot is merging ⏳

#1008 [14.0][FIX] hr_employee_calendar_planning: Prevent disable resource.calendar when is related to some employee
  hr_employee_calendar_planning/i18n/es.po
  hr_employee_calendar_planning/i18n/hr_employee_calendar_planning.pot
  hr_employee_calendar_planning/models/resource_calendar.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
Labels: approved, bot is merging ⏳

#1010 [FIX] hr_employee_relative: change attribute replace by invisible
  hr_employee_relative/views/hr_employee.xml
Labels: approved, bot is merging ⏳, ready to merge

#1012 [13.0][FIX] hr_employee_calendar_planning: Add check_company to calendar_id field in to show only allowed records according to company
  hr_employee_calendar_planning/i18n/es.po
  hr_employee_calendar_planning/i18n/hr_employee_calendar_planning.pot
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/models/resource_calendar.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
  hr_employee_calendar_planning/views/hr_employee_views.xml
Labels: approved, bot is merging ⏳

#1013 [14.0][FIX] hr_employee_calendar_planning: Add check_company to calendar_id field in to show only allowed records according to company
  hr_employee_calendar_planning/i18n/es.po
  hr_employee_calendar_planning/i18n/hr_employee_calendar_planning.pot
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/models/resource_calendar.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
  hr_employee_calendar_planning/views/hr_employee_views.xml
Labels: bot is merging ⏳
