Repository OCA/hr, pull requests merged in 2021-02, with the labels that each got.

#965 [12.0][FIX] hr_expense_invoice: Set groups to invoice_id field in expense view
  hr_expense_invoice/readme/CONTRIBUTORS.rst
  hr_expense_invoice/views/hr_expense_views.xml
Labels: approved, bot is merging ⏳

#893 [12.0][ADD] hr_expense_analytic_require
  hr_expense_analytic_require/README.rst
  hr_expense_analytic_require/__init__.py
  hr_expense_analytic_require/__manifest__.py
  hr_expense_analytic_require/data/res_company_data.xml
  hr_expense_analytic_require/models/__init__.py
  hr_expense_analytic_require/models/company.py
  hr_expense_analytic_require/models/hr_expense.py
  hr_expense_analytic_require/models/res_config_settings.py
  hr_expense_analytic_require/readme/CONFIGURE.rst
  hr_expense_analytic_require/readme/CONTRIBUTORS.rst
  hr_expense_analytic_require/readme/DESCRIPTION.rst
  hr_expense_analytic_require/readme/USAGE.rst
  hr_expense_analytic_require/static/description/icon.png
  hr_expense_analytic_require/views/hr_expense_views.xml
  hr_expense_analytic_require/views/res_company_view.xml
  hr_expense_analytic_require/views/res_config_settings_views.xml
Labels: bot is merging ⏳

#953 14.0 mig hr org chart overview
  hr_org_chart_overview/README.rst
  hr_org_chart_overview/__init__.py
  hr_org_chart_overview/__manifest__.py
  hr_org_chart_overview/i18n/hr_org_chart_overview.pot
  hr_org_chart_overview/models/__init__.py
  hr_org_chart_overview/models/hr_employee.py
  hr_org_chart_overview/readme/CONTRIBUTORS.rst
  hr_org_chart_overview/readme/DESCRIPTION.rst
  hr_org_chart_overview/readme/USAGE.rst
  hr_org_chart_overview/static/description/icon.png
  hr_org_chart_overview/static/description/index.html
  hr_org_chart_overview/static/src/js/hr_org_chart_overview.js
  hr_org_chart_overview/static/src/lib/orgchart/html2canvas.min.js
  hr_org_chart_overview/static/src/lib/orgchart/jquery.orgchart.css
  hr_org_chart_overview/static/src/lib/orgchart/jquery.orgchart.js
  hr_org_chart_overview/static/src/lib/orgchart/jspdf.min.js
  hr_org_chart_overview/static/src/scss/hr_org_chart_style.scss
  hr_org_chart_overview/static/src/xml/hr_org_chart_overview.xml
  hr_org_chart_overview/views/hr_org_chart_overview_templates.xml
  hr_org_chart_overview/views/hr_views.xml
  setup/hr_org_chart_overview/odoo/addons/hr_org_chart_overview
  setup/hr_org_chart_overview/setup.py
Labels: approved, bot is merging ⏳

#950 [13.0][IMP] hr_employee_relative: Add smart button
  hr_employee_relative/models/hr_employee.py
  hr_employee_relative/tests/test_hr_employee_relatives.py
  hr_employee_relative/views/hr_employee.xml
  hr_employee_relative/views/hr_employee_relative.xml
Labels: approved, bot is merging ⏳

#971 [FIX] hr_employee_firstname: Avoid access error on employee update
  hr_employee_firstname/models/hr_employee.py
Labels: approved, bot is merging ⏳

#973 [FIX] hr_employee_firstname: Avoid access error on employee update
  hr_employee_firstname/models/hr_employee.py
Labels: bot is merging ⏳

#928 [14.0][MIG] hr_employee_age
  hr_employee_age/README.rst
  hr_employee_age/__init__.py
  hr_employee_age/__manifest__.py
  hr_employee_age/i18n/ar.po
  hr_employee_age/i18n/cs_CZ.po
  hr_employee_age/i18n/de.po
  hr_employee_age/i18n/es.po
  hr_employee_age/i18n/fi.po
  hr_employee_age/i18n/fr.po
  hr_employee_age/i18n/hr.po
  hr_employee_age/i18n/hr_HR.po
  hr_employee_age/i18n/hr_employee_age.pot
  hr_employee_age/i18n/it.po
  hr_employee_age/i18n/lt.po
  hr_employee_age/i18n/nl_NL.po
  hr_employee_age/i18n/pt_BR.po
  hr_employee_age/i18n/ro.po
  hr_employee_age/i18n/sl.po
  hr_employee_age/models/__init__.py
  hr_employee_age/models/hr_employee.py
  hr_employee_age/readme/CONTRIBUTORS.rst
  hr_employee_age/readme/DESCRIPTION.rst
  hr_employee_age/readme/USAGE.rst
  hr_employee_age/static/description/icon.png
  hr_employee_age/static/description/index.html
  hr_employee_age/tests/__init__.py
  hr_employee_age/tests/test_hr_employee.py
  hr_employee_age/views/hr_employee.xml
  setup/hr_employee_age/odoo/addons/hr_employee_age
  setup/hr_employee_age/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#936 [14.0][MIG] hr_employee_medical_examination
  hr_employee_medical_examination/README.rst
  hr_employee_medical_examination/__init__.py
  hr_employee_medical_examination/__manifest__.py
  hr_employee_medical_examination/i18n/es.po
  hr_employee_medical_examination/i18n/hr_employee_medical_examination.pot
  hr_employee_medical_examination/models/__init__.py
  hr_employee_medical_examination/models/hr_employee.py
  hr_employee_medical_examination/models/hr_employee_medical_examination.py
  hr_employee_medical_examination/readme/CONTRIBUTORS.rst
  hr_employee_medical_examination/readme/DESCRIPTION.rst
  hr_employee_medical_examination/readme/USAGE.rst
  hr_employee_medical_examination/security/hr_employee_medical_examination_security.xml
  hr_employee_medical_examination/security/ir.model.access.csv
  hr_employee_medical_examination/static/description/icon.png
  hr_employee_medical_examination/static/description/index.html
  hr_employee_medical_examination/tests/__init__.py
  hr_employee_medical_examination/tests/test_hr_employee_medical_examination.py
  hr_employee_medical_examination/views/hr_employee_medical_examination_views.xml
  hr_employee_medical_examination/views/hr_employee_views.xml
  hr_employee_medical_examination/wizards/__init__.py
  hr_employee_medical_examination/wizards/wizard_generate_medical_examination.py
  hr_employee_medical_examination/wizards/wizard_generate_medical_examination.xml
  setup/hr_employee_medical_examination/odoo/addons/hr_employee_medical_examination
  setup/hr_employee_medical_examination/setup.py
Labels: approved, bot is merging ⏳, ready to merge
