Repository OCA/hr, pull requests merged in 2021-08, with the labels that each got.

#1017 [13.0][FIX] hr_employee_document: Add security rule to allow user without employee groups can access to attachments related to own employee
  hr_employee_document/README.rst
  hr_employee_document/__manifest__.py
  hr_employee_document/readme/DESCRIPTION.rst
  hr_employee_document/readme/ROADMAP.rst
  hr_employee_document/security/security.xml
  hr_employee_document/static/description/index.html
  hr_employee_document/tests/test_hr_employee_document.py
Labels: approved, ready to merge, bot is merging ⏳

#1011 [MIG] hr_course: migrate to 14.0
  hr_course/README.rst
  hr_course/__init__.py
  hr_course/__manifest__.py
  hr_course/i18n/es.po
  hr_course/i18n/hr_course.pot
  hr_course/models/__init__.py
  hr_course/models/hr_course.py
  hr_course/models/hr_employee.py
  hr_course/readme/CONTRIBUTORS.rst
  hr_course/readme/DESCRIPTION.rst
  hr_course/readme/USAGE.rst
  hr_course/security/course_security.xml
  hr_course/security/ir.model.access.csv
  hr_course/static/description/icon.png
  hr_course/static/description/index.html
  hr_course/tests/__init__.py
  hr_course/tests/test_hr_course.py
  hr_course/views/hr_course_category_views.xml
  hr_course/views/hr_course_views.xml
  hr_course/views/hr_employee_views.xml
  setup/hr_course/odoo/addons/hr_course
  setup/hr_course/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1020 [12.0][FIX] hr_expense_invoice: Update prices correctly after invoice creation from expense with some taxes defined
  hr_expense_invoice/models/hr_expense.py
Labels: bot is merging ⏳

#1021 [13.0][ADD] hr_recruitment_notification: subscribe users to new applications automatically
  hr_recruitment_notification/README.rst
  hr_recruitment_notification/__init__.py
  hr_recruitment_notification/__manifest__.py
  hr_recruitment_notification/data/message_subtypes.xml
  hr_recruitment_notification/i18n/es.po
  hr_recruitment_notification/i18n/hr_recruitment_notification.pot
  hr_recruitment_notification/readme/CONTRIBUTORS.rst
  hr_recruitment_notification/readme/DESCRIPTION.rst
  hr_recruitment_notification/static/description/icon.png
  hr_recruitment_notification/static/description/index.html
  hr_recruitment_notification/tests/__init__.py
  hr_recruitment_notification/tests/test_hr_application_notification.py
  setup/hr_recruitment_notification/odoo/addons/hr_recruitment_notification
  setup/hr_recruitment_notification/setup.py
Labels: approved, bot is merging ⏳
