Repository OCA/hr, pull requests merged in 2021-11, with the labels that each got.

#1038 [MIG] hr_employee_firstname: Migration to 15.0
  hr_employee_firstname/README.rst
  hr_employee_firstname/__init__.py
  hr_employee_firstname/__manifest__.py
  hr_employee_firstname/i18n/ar.po
  hr_employee_firstname/i18n/ca.po
  hr_employee_firstname/i18n/cs_CZ.po
  hr_employee_firstname/i18n/de.po
  hr_employee_firstname/i18n/es.po
  hr_employee_firstname/i18n/fa.po
  hr_employee_firstname/i18n/fi.po
  hr_employee_firstname/i18n/fr.po
  hr_employee_firstname/i18n/hr.po
  hr_employee_firstname/i18n/hr_HR.po
  hr_employee_firstname/i18n/hr_employee_firstname.pot
  hr_employee_firstname/i18n/it.po
  hr_employee_firstname/i18n/lt.po
  hr_employee_firstname/i18n/nl_NL.po
  hr_employee_firstname/i18n/pt_BR.po
  hr_employee_firstname/i18n/ro.po
  hr_employee_firstname/i18n/sl.po
  hr_employee_firstname/init_hook.py
  hr_employee_firstname/models/__init__.py
  hr_employee_firstname/models/base_config_settings.py
  hr_employee_firstname/models/hr_employee.py
  hr_employee_firstname/models/hr_employee_base.py
  hr_employee_firstname/readme/CONTRIBUTORS.rst
  hr_employee_firstname/readme/DESCRIPTION.rst
  hr_employee_firstname/readme/USAGE.rst
  hr_employee_firstname/static/description/icon.png
  hr_employee_firstname/static/description/index.html
  hr_employee_firstname/tests/__init__.py
  hr_employee_firstname/tests/test_hr_employee_firstname.py
  hr_employee_firstname/views/base_config_view.xml
  hr_employee_firstname/views/hr_view.xml
  setup/hr_employee_firstname/odoo/addons/hr_employee_firstname
  setup/hr_employee_firstname/setup.py
Labels: approved, bot is merging ⏳

#1046 [MIG] hr_employee_lastnames: Migration to 15.0
  hr_employee_lastnames/README.rst
  hr_employee_lastnames/__init__.py
  hr_employee_lastnames/__manifest__.py
  hr_employee_lastnames/hook.py
  hr_employee_lastnames/i18n/ca.po
  hr_employee_lastnames/i18n/es.po
  hr_employee_lastnames/i18n/hr_employee_lastnames.pot
  hr_employee_lastnames/i18n/pt_BR.po
  hr_employee_lastnames/models/__init__.py
  hr_employee_lastnames/models/hr_employee.py
  hr_employee_lastnames/models/hr_employee_base.py
  hr_employee_lastnames/readme/CONTRIBUTORS.rst
  hr_employee_lastnames/readme/DESCRIPTION.rst
  hr_employee_lastnames/readme/USAGE.rst
  hr_employee_lastnames/static/description/icon.png
  hr_employee_lastnames/static/description/index.html
  hr_employee_lastnames/tests/__init__.py
  hr_employee_lastnames/tests/test_hr_employee_lastnames.py
  hr_employee_lastnames/views/hr_views.xml
  setup/hr_employee_lastnames/odoo/addons/hr_employee_lastnames
  setup/hr_employee_lastnames/setup.py
Labels: approved, bot is merging ⏳

#1050 [13.0] [IMP] hr_course
  hr_course/__manifest__.py
  hr_course/demo/hr_course.xml
  hr_course/migrations/13.0.2.0.0/noupdate_changes.xml
  hr_course/migrations/13.0.2.0.0/post-migration.py
  hr_course/migrations/13.0.2.0.0/pre-migration.py
  hr_course/models/hr_course.py
  hr_course/readme/USAGE.rst
  hr_course/security/course_security.xml
  hr_course/security/ir.model.access.csv
  hr_course/tests/test_hr_course.py
  hr_course/views/hr_course_schedule_views.xml
  hr_course/views/hr_course_views.xml
  hr_course/views/hr_employee_views.xml
Labels: approved, bot is merging ⏳

#1026 [13.0][MIG] hr_personal_equipment_request: Migration to 13.0
  hr_personal_equipment_request/README.rst
  hr_personal_equipment_request/__init__.py
  hr_personal_equipment_request/__manifest__.py
  hr_personal_equipment_request/models/__init__.py
  hr_personal_equipment_request/models/hr_employee.py
  hr_personal_equipment_request/models/hr_personal_equipment.py
  hr_personal_equipment_request/models/hr_personal_equipment_request.py
  hr_personal_equipment_request/models/product_template.py
  hr_personal_equipment_request/readme/CONTRIBUTORS.rst
  hr_personal_equipment_request/readme/DESCRIPTION.rst
  hr_personal_equipment_request/readme/USAGE.rst
  hr_personal_equipment_request/security/hr_personal_equipment_request_security.xml
  hr_personal_equipment_request/security/ir.model.access.csv
  hr_personal_equipment_request/static/description/icon.png
  hr_personal_equipment_request/static/description/index.html
  hr_personal_equipment_request/tests/__init__.py
  hr_personal_equipment_request/tests/test_hr_personal_equipment_request.py
  hr_personal_equipment_request/views/hr_employee.xml
  hr_personal_equipment_request/views/hr_personal_equipment.xml
  hr_personal_equipment_request/views/hr_personal_equipment_request.xml
  hr_personal_equipment_request/views/product_template.xml
  setup/hr_personal_equipment_request/odoo/addons/hr_personal_equipment_request
  setup/hr_personal_equipment_request/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#991 [12.0][FIX] hr_holidays_validity_date: Check for `restrict_dates` when validating an allocation
  hr_holidays_validity_date/models/__init__.py
  hr_holidays_validity_date/models/hr_leave_allocation.py
Labels: approved, ready to merge, bot is merging ⏳

#1009 [14.0][MIG] hr_employee_id
  hr_employee_id/README.rst
  hr_employee_id/__init__.py
  hr_employee_id/__manifest__.py
  hr_employee_id/data/hr_employee_sequence.xml
  hr_employee_id/i18n/ar.po
  hr_employee_id/i18n/cs_CZ.po
  hr_employee_id/i18n/de.po
  hr_employee_id/i18n/es.po
  hr_employee_id/i18n/fi.po
  hr_employee_id/i18n/fr.po
  hr_employee_id/i18n/hr.po
  hr_employee_id/i18n/hr_HR.po
  hr_employee_id/i18n/hr_employee_id.pot
  hr_employee_id/i18n/it.po
  hr_employee_id/i18n/lt.po
  hr_employee_id/i18n/nl_NL.po
  hr_employee_id/i18n/pt_BR.po
  hr_employee_id/i18n/ro.po
  hr_employee_id/i18n/sl.po
  hr_employee_id/models/__init__.py
  hr_employee_id/models/hr_employee.py
  hr_employee_id/models/res_company.py
  hr_employee_id/models/res_config_settings.py
  hr_employee_id/readme/CONFIGURE.rst
  hr_employee_id/readme/CONTRIBUTORS.rst
  hr_employee_id/readme/DESCRIPTION.rst
  hr_employee_id/readme/INSTALL.rst
  hr_employee_id/readme/ROADMAP.rst
  hr_employee_id/readme/USAGE.rst
  hr_employee_id/static/description/icon.png
  hr_employee_id/static/description/index.html
  hr_employee_id/tests/__init__.py
  hr_employee_id/tests/test_employee_id.py
  hr_employee_id/views/hr_employee_views.xml
  hr_employee_id/views/res_config_settings_views.xml
  setup/hr_employee_id/odoo/addons/hr_employee_id
  setup/hr_employee_id/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1014 [11.0][FIX] hr_holidays_settings: wrong header in Settings
  hr_holidays_settings/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#905 [ADD][12.0] Added hr_expense_portal module.
  hr_expense_portal/README.rst
  hr_expense_portal/__init__.py
  hr_expense_portal/__manifest__.py
  hr_expense_portal/controllers/__init__.py
  hr_expense_portal/controllers/expense_portal.py
  hr_expense_portal/readme/CONTRIBUTORS.rst
  hr_expense_portal/readme/CREDITS.rst
  hr_expense_portal/readme/DESCRIPTION.rst
  hr_expense_portal/security/ir.model.access.csv
  hr_expense_portal/security/security.xml
  hr_expense_portal/static/description/icon.png
  hr_expense_portal/static/description/index.html
  hr_expense_portal/views/expense_template.xml
Labels: enhancement, needs review, bot is merging ⏳

#982 [14.0] [FIX] [hr_employee_service] use built-in departure date as termination date
  hr_employee_service/models/hr_employee.py
  hr_employee_service/tests/test_hr_employee_service.py
  hr_employee_service/views/hr_employee.xml
Labels: bot is merging ⏳
