Repository OCA/hr, pull requests merged in 2022-03, with the labels that each got.

#1072 [IMP] hr_personal_equipmen_request: add colors depending on state to tree view
  hr_personal_equipment_request/views/hr_personal_equipment.xml
  hr_personal_equipment_request/views/hr_personal_equipment_request.xml
Labels: approved, ready to merge, bot is merging ⏳

#1066 [12.0][FIX] hr_calendar_rest_time: Remove offending `all_day` value
  hr_calendar_rest_time/__manifest__.py
  hr_calendar_rest_time/migrations/12.0.2.0.0/pre-migration.py
  hr_calendar_rest_time/models/resource_calendar_attendance.py
  hr_calendar_rest_time/tests/test_hr_calendar_rest_time.py
Labels: bot is merging ⏳

#1084 [13.0][FIX] hr_calendar_rest_time: Remove offending all_day value
  hr_calendar_rest_time/__manifest__.py
  hr_calendar_rest_time/migrations/13.0.2.0.0/pre-migration.py
  hr_calendar_rest_time/models/resource_calendar_attendance.py
  hr_calendar_rest_time/tests/test_hr_calendar_rest_time.py
Labels: bot is merging ⏳

#1090 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
  hr_employee_id/views/hr_employee_views.xml
  hr_employee_lastnames/models/hr_employee.py
  hr_employee_relative/views/hr_employee.xml
Labels: help wanted, needs review
