Repository OCA/hr, pull requests merged in 2022-07, with the labels that each got.

#1129 [13.0][UPD] Brainbean Apps => CorporateHub
  hr_contract_document/__manifest__.py
  hr_contract_document/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#1127 [15.0][MIG] hr_holidays_settings
  hr_holidays_settings/README.rst
  hr_holidays_settings/__init__.py
  hr_holidays_settings/__manifest__.py
  hr_holidays_settings/i18n/ar.po
  hr_holidays_settings/i18n/de.po
  hr_holidays_settings/i18n/es.po
  hr_holidays_settings/i18n/fa.po
  hr_holidays_settings/i18n/fi.po
  hr_holidays_settings/i18n/fr.po
  hr_holidays_settings/i18n/hr.po
  hr_holidays_settings/i18n/hr_HR.po
  hr_holidays_settings/i18n/hr_holidays_settings.pot
  hr_holidays_settings/i18n/it.po
  hr_holidays_settings/i18n/nl_NL.po
  hr_holidays_settings/i18n/pt_BR.po
  hr_holidays_settings/i18n/ro.po
  hr_holidays_settings/i18n/sl.po
  hr_holidays_settings/readme/CONTRIBUTORS.rst
  hr_holidays_settings/readme/DESCRIPTION.rst
  hr_holidays_settings/readme/USAGE.rst
  hr_holidays_settings/static/description/icon.png
  hr_holidays_settings/static/description/index.html
  hr_holidays_settings/views/res_config_settings.xml
  setup/hr_holidays_settings/odoo/addons/hr_holidays_settings
  setup/hr_holidays_settings/setup.py
Labels: bot is merging ⏳

#1120 [15.0][MIG] hr_employee_service_contract: Migration to 15.0
  hr_employee_service_contract/README.rst
  hr_employee_service_contract/__init__.py
  hr_employee_service_contract/__manifest__.py
  hr_employee_service_contract/i18n/de.po
  hr_employee_service_contract/i18n/es.po
  hr_employee_service_contract/i18n/fr.po
  hr_employee_service_contract/i18n/hr_employee_service_contract.pot
  hr_employee_service_contract/models/__init__.py
  hr_employee_service_contract/models/hr_employee.py
  hr_employee_service_contract/readme/CONTRIBUTORS.rst
  hr_employee_service_contract/readme/DESCRIPTION.rst
  hr_employee_service_contract/static/description/icon.png
  hr_employee_service_contract/static/description/index.html
  hr_employee_service_contract/tests/__init__.py
  hr_employee_service_contract/tests/test_hr_employee_service.py
  setup/hr_employee_service_contract/odoo/addons/hr_employee_service_contract
  setup/hr_employee_service_contract/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1131 [14.0][MIG] hr_employee_document: Migration to 14.0
  hr_employee_document/README.rst
  hr_employee_document/__init__.py
  hr_employee_document/__manifest__.py
  hr_employee_document/i18n/fr.po
  hr_employee_document/i18n/hr.po
  hr_employee_document/i18n/hr_employee_document.pot
  hr_employee_document/models/__init__.py
  hr_employee_document/models/hr_employee.py
  hr_employee_document/models/hr_employee_public.py
  hr_employee_document/readme/CONTRIBUTORS.rst
  hr_employee_document/readme/DESCRIPTION.rst
  hr_employee_document/readme/ROADMAP.rst
  hr_employee_document/security/security.xml
  hr_employee_document/static/description/icon.png
  hr_employee_document/static/description/index.html
  hr_employee_document/tests/__init__.py
  hr_employee_document/tests/test_hr_employee_document.py
  hr_employee_document/views/hr_employee.xml
  hr_employee_document/views/hr_employee_public.xml
  setup/hr_employee_document/odoo/addons/hr_employee_document
  setup/hr_employee_document/setup.py
Labels: approved, bot is merging ⏳
