Repository OCA/hr, pull requests merged in 2022-01, with the labels that each got.

#1064 [IMP] hr_course
  hr_course/README.rst
  hr_course/__manifest__.py
  hr_course/demo/hr_course.xml
  hr_course/i18n/es.po
  hr_course/i18n/hr_course.pot
  hr_course/migrations/14.0.2.0.0/noupdate_changes.xml
  hr_course/migrations/14.0.2.0.0/post-migration.py
  hr_course/migrations/14.0.2.0.0/pre-migration.py
  hr_course/models/__init__.py
  hr_course/models/hr_course.py
  hr_course/models/hr_course_schedule.py
  hr_course/readme/DESCRIPTION.rst
  hr_course/readme/USAGE.rst
  hr_course/security/course_security.xml
  hr_course/security/ir.model.access.csv
  hr_course/static/description/index.html
  hr_course/tests/test_hr_course.py
  hr_course/views/hr_course_schedule_views.xml
  hr_course/views/hr_course_views.xml
  hr_course/views/hr_employee_views.xml
Labels: approved, bot is merging ⏳

#1051 [MIG] hr_employee_partner_external: Migration to 13.0
  hr_employee_partner_external/README.rst
  hr_employee_partner_external/__init__.py
  hr_employee_partner_external/__manifest__.py
  hr_employee_partner_external/i18n/hr_employee_partner_external.pot
  hr_employee_partner_external/i18n/it.po
  hr_employee_partner_external/models/__init__.py
  hr_employee_partner_external/models/hr_employee.py
  hr_employee_partner_external/readme/CONTRIBUTORS.rst
  hr_employee_partner_external/readme/DESCRIPTION.rst
  hr_employee_partner_external/readme/HISTORY.rst
  hr_employee_partner_external/readme/USAGE.rst
  hr_employee_partner_external/static/description/icon.png
  hr_employee_partner_external/static/description/index.html
  hr_employee_partner_external/views/hr_employee.xml
  setup/hr_employee_partner_external/odoo/addons/hr_employee_partner_external
  setup/hr_employee_partner_external/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1053 [ADD] hr_personal_equipment_request_tier_validation
  hr_personal_equipment_request_tier_validation/README.rst
  hr_personal_equipment_request_tier_validation/__init__.py
  hr_personal_equipment_request_tier_validation/__manifest__.py
  hr_personal_equipment_request_tier_validation/data/tier_definition.xml
  hr_personal_equipment_request_tier_validation/models/__init__.py
  hr_personal_equipment_request_tier_validation/models/hr_personal_equipment_request.py
  hr_personal_equipment_request_tier_validation/models/tier_definition.py
  hr_personal_equipment_request_tier_validation/readme/CONTRIBUTORS.rst
  hr_personal_equipment_request_tier_validation/readme/DESCRIPTION.rst
  hr_personal_equipment_request_tier_validation/static/description/icon.png
  hr_personal_equipment_request_tier_validation/static/description/index.html
  oca_dependencies.txt
  setup/hr_personal_equipment_request_tier_validation/odoo/addons/hr_personal_equipment_request_tier_validation
  setup/hr_personal_equipment_request_tier_validation/setup.py
Labels: approved, bot is merging ⏳

#1067 [14.0][MIG] hr_employee_ppe
  hr_employee_ppe/README.rst
  hr_employee_ppe/__init__.py
  hr_employee_ppe/__manifest__.py
  hr_employee_ppe/data/hr_employee_ppe_cron.xml
  hr_employee_ppe/i18n/hr_employee_ppe.pot
  hr_employee_ppe/i18n/pt_BR.po
  hr_employee_ppe/models/__init__.py
  hr_employee_ppe/models/hr_personal_equipment.py
  hr_employee_ppe/models/hr_personal_equipment_request.py
  hr_employee_ppe/models/product_template.py
  hr_employee_ppe/readme/CONTRIBUTORS.rst
  hr_employee_ppe/readme/CREDITS.rst
  hr_employee_ppe/readme/DESCRIPTION.rst
  hr_employee_ppe/readme/INSTALL.rst
  hr_employee_ppe/readme/USAGE.rst
  hr_employee_ppe/reports/hr_employee_ppe_report.xml
  hr_employee_ppe/reports/hr_employee_ppe_report_template.xml
  hr_employee_ppe/static/description/banner.png
  hr_employee_ppe/static/description/icon.png
  hr_employee_ppe/static/description/index.html
  hr_employee_ppe/tests/__init__.py
  hr_employee_ppe/tests/test_hr_employee_ppe.py
  hr_employee_ppe/views/hr_personal_equipment.xml
  hr_employee_ppe/views/hr_personal_equipment_request.xml
  hr_employee_ppe/views/product_template.xml
  setup/hr_employee_ppe/odoo/addons/hr_employee_ppe
  setup/hr_employee_ppe/setup.py
Labels: approved, bot is merging ⏳

#1029 [13.0][ADD] hr_personal_equipment_stock
  hr_personal_equipment_stock/README.rst
  hr_personal_equipment_stock/__init__.py
  hr_personal_equipment_stock/__manifest__.py
  hr_personal_equipment_stock/models/__init__.py
  hr_personal_equipment_stock/models/hr_personal_equipment.py
  hr_personal_equipment_stock/models/hr_personal_equipment_request.py
  hr_personal_equipment_stock/models/procurement_group.py
  hr_personal_equipment_stock/models/stock_location.py
  hr_personal_equipment_stock/models/stock_move.py
  hr_personal_equipment_stock/models/stock_picking.py
  hr_personal_equipment_stock/models/stock_rule.py
  hr_personal_equipment_stock/readme/CONFIGURE.rst
  hr_personal_equipment_stock/readme/CONTRIBUTORS.rst
  hr_personal_equipment_stock/readme/CREDITS.rst
  hr_personal_equipment_stock/readme/DESCRIPTION.rst
  hr_personal_equipment_stock/readme/INSTALL.rst
  hr_personal_equipment_stock/readme/USAGE.rst
  hr_personal_equipment_stock/static/description/icon.png
  hr_personal_equipment_stock/static/description/index.html
  hr_personal_equipment_stock/tests/__init__.py
  hr_personal_equipment_stock/tests/test_hr_personal_equipment_stock.py
  hr_personal_equipment_stock/views/hr_personal_equipment.xml
  hr_personal_equipment_stock/views/hr_personal_equipment_request.xml
  hr_personal_equipment_stock/views/procurement_group.xml
  hr_personal_equipment_stock/views/stock_location.xml
  hr_personal_equipment_stock/views/stock_move.xml
  hr_personal_equipment_stock/views/stock_picking.xml
  setup/hr_personal_equipment_stock/odoo/addons/hr_personal_equipment_stock
  setup/hr_personal_equipment_stock/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1048 [ADD] hr_course_survey
  hr_course_survey/__init__.py
  hr_course_survey/__manifest__.py
  hr_course_survey/data/mail.xml
  hr_course_survey/models/__init__.py
  hr_course_survey/models/hr_course.py
  hr_course_survey/models/hr_course_attendee.py
  hr_course_survey/models/hr_course_schedule.py
  hr_course_survey/models/survey_user_input.py
  hr_course_survey/readme/CONTRIBUTORS.rst
  hr_course_survey/readme/DESCRIPTION.rst
  hr_course_survey/readme/USAGE.rst
  hr_course_survey/static/description/icon.png
  hr_course_survey/tests/__init__.py
  hr_course_survey/tests/test_hr_course.py
  hr_course_survey/views/hr_course.xml
  hr_course_survey/views/hr_course_attendee.xml
  hr_course_survey/views/hr_course_schedule.xml
  setup/hr_course_survey/odoo/addons/hr_course_survey
  setup/hr_course_survey/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1028 [ADD] hr_personal_equipment_variant_configurator
  hr_personal_equipment_variant_configurator/README.rst
  hr_personal_equipment_variant_configurator/__init__.py
  hr_personal_equipment_variant_configurator/__manifest__.py
  hr_personal_equipment_variant_configurator/models/__init__.py
  hr_personal_equipment_variant_configurator/models/hr_personal_equipment.py
  hr_personal_equipment_variant_configurator/readme/CONTRIBUTORS.rst
  hr_personal_equipment_variant_configurator/readme/DESCRIPTION.rst
  hr_personal_equipment_variant_configurator/readme/INSTALL.rst
  hr_personal_equipment_variant_configurator/static/description/index.html
  hr_personal_equipment_variant_configurator/views/hr_personal_equipment_request.xml
  oca_dependencies.txt
  setup/hr_personal_equipment_variant_configurator/odoo/addons/hr_personal_equipment_variant_configurator
  setup/hr_personal_equipment_variant_configurator/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1069 [FIX] hr_personal_equipment_stock: change manifest url
  hr_personal_equipment_stock/__manifest__.py
Labels: bot is merging ⏳

#1062 [MIG] hr_job_category: Migration to 14.0
  hr_job_category/README.rst
  hr_job_category/__init__.py
  hr_job_category/__manifest__.py
  hr_job_category/i18n/de.po
  hr_job_category/i18n/es.po
  hr_job_category/i18n/fi.po
  hr_job_category/i18n/fr.po
  hr_job_category/i18n/hr_job_category.pot
  hr_job_category/i18n/it.po
  hr_job_category/i18n/pt_BR.po
  hr_job_category/i18n/ro.po
  hr_job_category/i18n/sl.po
  hr_job_category/models/__init__.py
  hr_job_category/models/hr.py
  hr_job_category/readme/CONTRIBUTORS.rst
  hr_job_category/readme/DESCRIPTION.rst
  hr_job_category/readme/INSTALL.rst
  hr_job_category/readme/USAGE.rst
  hr_job_category/static/description/icon.png
  hr_job_category/static/description/index.html
  hr_job_category/tests/__init__.py
  hr_job_category/tests/test_hr_job_categories.py
  hr_job_category/views/hr_view.xml
  setup/hr_job_category/odoo/addons/hr_job_category
  setup/hr_job_category/setup.py
Labels: approved, bot is merging ⏳

#1037 [ADD] hr_contract_type
  hr_contract_type/README.rst
  hr_contract_type/__init__.py
  hr_contract_type/__manifest__.py
  hr_contract_type/hooks.py
  hr_contract_type/models/__init__.py
  hr_contract_type/models/hr_contract.py
  hr_contract_type/models/hr_contract_type.py
  hr_contract_type/readme/CONTRIBUTORS.rst
  hr_contract_type/readme/DESCRIPTION.rst
  hr_contract_type/readme/ROADMAP.rst
  hr_contract_type/security/ir.model.access.csv
  hr_contract_type/static/description/icon.png
  hr_contract_type/static/description/index.html
  hr_contract_type/views/hr_contract.xml
  hr_contract_type/views/hr_contract_type.xml
  setup/hr_contract_type/odoo/addons/hr_contract_type
  setup/hr_contract_type/setup.py
Labels: approved, ready to merge, bot is merging ⏳
