Repository OCA/hr, pull requests merged in 2022-09, with the labels that each got.

#1139 [MIG] hr_contract_reference: Migration to 15.0
  hr_contract_reference/README.rst
  hr_contract_reference/__init__.py
  hr_contract_reference/__manifest__.py
  hr_contract_reference/data/hr_contract_sequence.xml
  hr_contract_reference/i18n/ar.po
  hr_contract_reference/i18n/cs_CZ.po
  hr_contract_reference/i18n/de.po
  hr_contract_reference/i18n/es.po
  hr_contract_reference/i18n/fi.po
  hr_contract_reference/i18n/fr.po
  hr_contract_reference/i18n/hi_IN.po
  hr_contract_reference/i18n/hr.po
  hr_contract_reference/i18n/hr_contract_reference.pot
  hr_contract_reference/i18n/it.po
  hr_contract_reference/i18n/lt.po
  hr_contract_reference/i18n/nl_NL.po
  hr_contract_reference/i18n/pt_BR.po
  hr_contract_reference/i18n/ro.po
  hr_contract_reference/i18n/sl.po
  hr_contract_reference/models/__init__.py
  hr_contract_reference/models/hr_contract.py
  hr_contract_reference/readme/CONFIGURE.rst
  hr_contract_reference/readme/CONTRIBUTORS.rst
  hr_contract_reference/readme/DESCRIPTION.rst
  hr_contract_reference/readme/USAGE.rst
  hr_contract_reference/static/description/icon.png
  hr_contract_reference/static/description/index.html
  hr_contract_reference/tests/__init__.py
  hr_contract_reference/tests/test_contract_reference.py
  setup/hr_contract_reference/odoo/addons/hr_contract_reference
  setup/hr_contract_reference/setup.py
Labels: approved

#1123 15.0 mig hr emergency contact
  hr_emergency_contact/README.rst
  hr_emergency_contact/__init__.py
  hr_emergency_contact/__manifest__.py
  hr_emergency_contact/i18n/ar.po
  hr_emergency_contact/i18n/cs_CZ.po
  hr_emergency_contact/i18n/de.po
  hr_emergency_contact/i18n/es.po
  hr_emergency_contact/i18n/fi.po
  hr_emergency_contact/i18n/fr.po
  hr_emergency_contact/i18n/hr.po
  hr_emergency_contact/i18n/hr_HR.po
  hr_emergency_contact/i18n/hr_emergency_contact.pot
  hr_emergency_contact/i18n/it.po
  hr_emergency_contact/i18n/lt.po
  hr_emergency_contact/i18n/nl_NL.po
  hr_emergency_contact/i18n/pt_BR.po
  hr_emergency_contact/i18n/ro.po
  hr_emergency_contact/i18n/sl.po
  hr_emergency_contact/models/__init__.py
  hr_emergency_contact/models/hr_employee.py
  hr_emergency_contact/static/description/icon.png
  hr_emergency_contact/views/hr_employee_views.xml
  setup/hr_emergency_contact/odoo/addons/hr_emergency_contact
  setup/hr_emergency_contact/setup.py
Labels: bot is merging ⏳

#1122 15.0 mig hr employee birth name
  hr_employee_birth_name/README.rst
  hr_employee_birth_name/__init__.py
  hr_employee_birth_name/__manifest__.py
  hr_employee_birth_name/i18n/ar.po
  hr_employee_birth_name/i18n/cs_CZ.po
  hr_employee_birth_name/i18n/de.po
  hr_employee_birth_name/i18n/es.po
  hr_employee_birth_name/i18n/fi.po
  hr_employee_birth_name/i18n/fr.po
  hr_employee_birth_name/i18n/hr.po
  hr_employee_birth_name/i18n/hr_HR.po
  hr_employee_birth_name/i18n/hr_employee_birth_name.pot
  hr_employee_birth_name/i18n/it.po
  hr_employee_birth_name/i18n/lt.po
  hr_employee_birth_name/i18n/nl_NL.po
  hr_employee_birth_name/i18n/pt_BR.po
  hr_employee_birth_name/i18n/ro.po
  hr_employee_birth_name/i18n/sl.po
  hr_employee_birth_name/models/__init__.py
  hr_employee_birth_name/models/hr_employee.py
  hr_employee_birth_name/readme/CONTRIBUTORS.rst
  hr_employee_birth_name/readme/DESCRIPTION.rst
  hr_employee_birth_name/readme/INSTALL.rst
  hr_employee_birth_name/readme/USAGE.rst
  hr_employee_birth_name/static/description/icon.png
  hr_employee_birth_name/static/description/index.html
  hr_employee_birth_name/views/hr_employee_view.xml
  setup/hr_employee_birth_name/odoo/addons/hr_employee_birth_name
  setup/hr_employee_birth_name/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1121 [MIG] hr_job_category: Migration to 15.0
  hr_job_category/README.rst
  hr_job_category/__init__.py
  hr_job_category/__manifest__.py
  hr_job_category/i18n/de.po
  hr_job_category/i18n/es.po
  hr_job_category/i18n/fi.po
  hr_job_category/i18n/fr.po
  hr_job_category/i18n/hr_job_category.pot
  hr_job_category/i18n/it.po
  hr_job_category/i18n/pt_BR.po
  hr_job_category/i18n/ro.po
  hr_job_category/i18n/sl.po
  hr_job_category/models/__init__.py
  hr_job_category/models/hr.py
  hr_job_category/readme/CONTRIBUTORS.rst
  hr_job_category/readme/DESCRIPTION.rst
  hr_job_category/readme/INSTALL.rst
  hr_job_category/readme/USAGE.rst
  hr_job_category/static/description/icon.png
  hr_job_category/static/description/index.html
  hr_job_category/tests/__init__.py
  hr_job_category/tests/test_hr_job_categories.py
  hr_job_category/views/hr_view.xml
  setup/hr_job_category/odoo/addons/hr_job_category
  setup/hr_job_category/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1097 [14.0][MIG] hr_worked_days_from_timesheet
  hr_worked_days_from_timesheet/README.rst
  hr_worked_days_from_timesheet/__init__.py
  hr_worked_days_from_timesheet/__manifest__.py
  hr_worked_days_from_timesheet/i18n/cs_CZ.po
  hr_worked_days_from_timesheet/i18n/de.po
  hr_worked_days_from_timesheet/i18n/es.po
  hr_worked_days_from_timesheet/i18n/fr.po
  hr_worked_days_from_timesheet/i18n/hr_worked_days_from_timesheet.pot
  hr_worked_days_from_timesheet/i18n/sl.po
  hr_worked_days_from_timesheet/models/__init__.py
  hr_worked_days_from_timesheet/models/hr_payslip.py
  hr_worked_days_from_timesheet/models/hr_payslip_worked_days.py
  hr_worked_days_from_timesheet/readme/CONTRIBUTORS.rst
  hr_worked_days_from_timesheet/readme/DESCRIPTION.rst
  hr_worked_days_from_timesheet/readme/USAGE.rst
  hr_worked_days_from_timesheet/static/description/icon.png
  hr_worked_days_from_timesheet/static/description/index.html
  hr_worked_days_from_timesheet/tests/__init__.py
  hr_worked_days_from_timesheet/tests/test_worked_days_from_timesheet.py
  hr_worked_days_from_timesheet/views/hr_payslip_view.xml
  setup/hr_worked_days_from_timesheet/odoo/addons/hr_worked_days_from_timesheet
  setup/hr_worked_days_from_timesheet/setup.py
Labels: approved, bot is merging ⏳

#1080 [13.0][FIX] resource_hook: Avoid crash when validating leaves
  resource_hook/hooks.py
Labels: bot is merging ⏳

#1041 [MIG] gamification_badge_report : Migation to 14.0.
  gamification_badge_report/README.rst
  gamification_badge_report/__init__.py
  gamification_badge_report/__manifest__.py
  gamification_badge_report/readme/CONTRIBUTORS.rst
  gamification_badge_report/readme/CREDITS.rst
  gamification_badge_report/readme/DESCRIPTION.rst
  gamification_badge_report/report/__init__.py
  gamification_badge_report/report/gamification_badge_report.py
  gamification_badge_report/report/gamification_badge_report_view.xml
  gamification_badge_report/security/ir.model.access.csv
  gamification_badge_report/static/description/icon.png
  gamification_badge_report/static/description/index.html
  gamification_badge_report/tests/__init__.py
  gamification_badge_report/tests/test_gamification_badge_report.py
  setup/gamification_badge_report/odoo/addons/gamification_badge_report
  setup/gamification_badge_report/setup.py
Labels: approved, bot is merging ⏳

#1087 [12.0] [ADD] hr_expense_type: new module
  hr_expense_type/README.rst
  hr_expense_type/__init__.py
  hr_expense_type/__manifest__.py
  hr_expense_type/i18n/es.po
  hr_expense_type/i18n/hr_expense_type.pot
  hr_expense_type/models/__init__.py
  hr_expense_type/models/hr_expense.py
  hr_expense_type/models/hr_expense_type.py
  hr_expense_type/readme/CONTRIBUTORS.rst
  hr_expense_type/readme/DESCRIPTION.rst
  hr_expense_type/readme/USAGE.rst
  hr_expense_type/security/ir.model.access.csv
  hr_expense_type/static/description/icon.png
  hr_expense_type/static/description/index.html
  hr_expense_type/views/hr_expense_type_views.xml
  hr_expense_type/views/hr_expense_views.xml
Labels: approved, ready to merge, bot is merging ⏳
