Repository OCA/hr, pull requests merged in 2022-12, with the labels that each got.

#1060 [15.0][MIG] hr_org_chart_overview
  hr_org_chart_overview/README.rst
  hr_org_chart_overview/__init__.py
  hr_org_chart_overview/__manifest__.py
  hr_org_chart_overview/i18n/hr_org_chart_overview.pot
  hr_org_chart_overview/i18n/pt_BR.po
  hr_org_chart_overview/i18n/sv.po
  hr_org_chart_overview/models/__init__.py
  hr_org_chart_overview/models/hr_employee.py
  hr_org_chart_overview/readme/CONTRIBUTORS.rst
  hr_org_chart_overview/readme/DESCRIPTION.rst
  hr_org_chart_overview/readme/USAGE.rst
  hr_org_chart_overview/static/description/icon.png
  hr_org_chart_overview/static/description/index.html
  hr_org_chart_overview/static/src/js/hr_org_chart_overview.js
  hr_org_chart_overview/static/src/lib/orgchart/html2canvas.min.js
  hr_org_chart_overview/static/src/lib/orgchart/jquery.orgchart.css
  hr_org_chart_overview/static/src/lib/orgchart/jquery.orgchart.js
  hr_org_chart_overview/static/src/lib/orgchart/jspdf.min.js
  hr_org_chart_overview/static/src/scss/hr_org_chart_style.scss
  hr_org_chart_overview/static/src/xml/hr_org_chart_overview.xml
  hr_org_chart_overview/views/hr_views.xml
  setup/hr_org_chart_overview/odoo/addons/hr_org_chart_overview
  setup/hr_org_chart_overview/setup.py
Labels: bot is merging ⏳

#1171 [14.0][ADD] hr_contract_employee_calendar_planning
  hr_contract_employee_calendar_planning/README.rst
  hr_contract_employee_calendar_planning/__init__.py
  hr_contract_employee_calendar_planning/__manifest__.py
  hr_contract_employee_calendar_planning/hooks.py
  hr_contract_employee_calendar_planning/models/__init__.py
  hr_contract_employee_calendar_planning/models/contract.py
  hr_contract_employee_calendar_planning/readme/CONTRIBUTORS.rst
  hr_contract_employee_calendar_planning/readme/DESCRIPTION.rst
  hr_contract_employee_calendar_planning/readme/USAGE.rst
  hr_contract_employee_calendar_planning/static/description/index.html
  hr_contract_employee_calendar_planning/tests/__init__.py
  hr_contract_employee_calendar_planning/tests/test_hr_contract_employee_calendar_planning.py
  hr_contract_employee_calendar_planning/views/contract.xml
  setup/hr_contract_employee_calendar_planning/odoo/addons/hr_contract_employee_calendar_planning
  setup/hr_contract_employee_calendar_planning/setup.py
Labels: approved, bot is merging ⏳

#1176 [16.0][FIX] test refresh->invalidate_recordset
  hr_employee_lastnames/tests/test_hr_employee_lastnames.py
Labels: bot is merging ⏳

#1174 [16.0][MIG] hr_employee_medical_examination: Migration to 16.0
  hr_employee_medical_examination/README.rst
  hr_employee_medical_examination/__init__.py
  hr_employee_medical_examination/__manifest__.py
  hr_employee_medical_examination/i18n/de.po
  hr_employee_medical_examination/i18n/es.po
  hr_employee_medical_examination/i18n/hr_employee_medical_examination.pot
  hr_employee_medical_examination/models/__init__.py
  hr_employee_medical_examination/models/hr_employee.py
  hr_employee_medical_examination/models/hr_employee_medical_examination.py
  hr_employee_medical_examination/readme/CONTRIBUTORS.rst
  hr_employee_medical_examination/readme/DESCRIPTION.rst
  hr_employee_medical_examination/readme/USAGE.rst
  hr_employee_medical_examination/security/hr_employee_medical_examination_security.xml
  hr_employee_medical_examination/security/ir.model.access.csv
  hr_employee_medical_examination/static/description/icon.png
  hr_employee_medical_examination/static/description/index.html
  hr_employee_medical_examination/tests/__init__.py
  hr_employee_medical_examination/tests/test_hr_employee_medical_examination.py
  hr_employee_medical_examination/views/hr_employee_medical_examination_views.xml
  hr_employee_medical_examination/views/hr_employee_views.xml
  hr_employee_medical_examination/wizards/__init__.py
  hr_employee_medical_examination/wizards/wizard_generate_medical_examination.py
  hr_employee_medical_examination/wizards/wizard_generate_medical_examination.xml
  setup/hr_employee_medical_examination/odoo/addons/hr_employee_medical_examination
  setup/hr_employee_medical_examination/setup.py
Labels: approved, bot is merging ⏳

#1172 [16.0][MIG] hr_course: Migration to 16.0
  hr_course/README.rst
  hr_course/__init__.py
  hr_course/__manifest__.py
  hr_course/demo/hr_course.xml
  hr_course/i18n/de.po
  hr_course/i18n/es.po
  hr_course/i18n/hr_course.pot
  hr_course/models/__init__.py
  hr_course/models/hr_course.py
  hr_course/models/hr_course_schedule.py
  hr_course/models/hr_employee.py
  hr_course/readme/CONTRIBUTORS.rst
  hr_course/readme/DESCRIPTION.rst
  hr_course/readme/USAGE.rst
  hr_course/security/course_security.xml
  hr_course/security/ir.model.access.csv
  hr_course/static/description/icon.png
  hr_course/static/description/index.html
  hr_course/tests/__init__.py
  hr_course/tests/test_hr_course.py
  hr_course/views/hr_course_category_views.xml
  hr_course/views/hr_course_schedule_views.xml
  hr_course/views/hr_course_views.xml
  hr_course/views/hr_employee_views.xml
  setup/hr_course/odoo/addons/hr_course
  setup/hr_course/setup.py
Labels: approved, bot is merging ⏳

#1173 [16.0][MIG] hr_employee_ssn: Migration to 16.0
  hr_employee_ssn/README.rst
  hr_employee_ssn/__init__.py
  hr_employee_ssn/__manifest__.py
  hr_employee_ssn/i18n/de.po
  hr_employee_ssn/i18n/es_AR.po
  hr_employee_ssn/i18n/fr.po
  hr_employee_ssn/i18n/hr_employee_ssn.pot
  hr_employee_ssn/readme/CONTRIBUTORS.rst
  hr_employee_ssn/readme/DESCRIPTION.rst
  hr_employee_ssn/static/description/icon.png
  hr_employee_ssn/static/description/index.html
  hr_employee_ssn/views/hr_employee_views.xml
  setup/hr_employee_ssn/odoo/addons/hr_employee_ssn
  setup/hr_employee_ssn/setup.py
Labels: approved, bot is merging ⏳

#1175 [16.0][MIG] hr_personal_equipment_request: Migration to 16.0
  hr_personal_equipment_request/README.rst
  hr_personal_equipment_request/__init__.py
  hr_personal_equipment_request/__manifest__.py
  hr_personal_equipment_request/i18n/de.po
  hr_personal_equipment_request/i18n/es.po
  hr_personal_equipment_request/i18n/es_PA.po
  hr_personal_equipment_request/i18n/hr_personal_equipment_request.pot
  hr_personal_equipment_request/i18n/pt_BR.po
  hr_personal_equipment_request/models/__init__.py
  hr_personal_equipment_request/models/hr_employee.py
  hr_personal_equipment_request/models/hr_personal_equipment.py
  hr_personal_equipment_request/models/hr_personal_equipment_request.py
  hr_personal_equipment_request/models/product_template.py
  hr_personal_equipment_request/readme/CONTRIBUTORS.rst
  hr_personal_equipment_request/readme/DESCRIPTION.rst
  hr_personal_equipment_request/readme/USAGE.rst
  hr_personal_equipment_request/security/hr_personal_equipment_request_security.xml
  hr_personal_equipment_request/security/ir.model.access.csv
  hr_personal_equipment_request/static/description/icon.png
  hr_personal_equipment_request/static/description/index.html
  hr_personal_equipment_request/tests/__init__.py
  hr_personal_equipment_request/tests/test_hr_personal_equipment_request.py
  hr_personal_equipment_request/views/hr_employee_views.xml
  hr_personal_equipment_request/views/hr_personal_equipment_request_views.xml
  hr_personal_equipment_request/views/hr_personal_equipment_views.xml
  hr_personal_equipment_request/views/product_template_views.xml
  setup/hr_personal_equipment_request/odoo/addons/hr_personal_equipment_request
  setup/hr_personal_equipment_request/setup.py
Labels: approved, bot is merging ⏳

#1166 [15.0][MIG] hr_employee_digitized_signature
  hr_employee_digitized_signature/README.rst
  hr_employee_digitized_signature/__init__.py
  hr_employee_digitized_signature/__manifest__.py
  hr_employee_digitized_signature/i18n/de.po
  hr_employee_digitized_signature/i18n/es_AR.po
  hr_employee_digitized_signature/i18n/hr_employee_digitized_signature.pot
  hr_employee_digitized_signature/models/__init__.py
  hr_employee_digitized_signature/models/hr_employee.py
  hr_employee_digitized_signature/readme/CONTRIBUTORS.rst
  hr_employee_digitized_signature/readme/DESCRIPTION.rst
  hr_employee_digitized_signature/static/description/icon.png
  hr_employee_digitized_signature/static/description/index.html
  hr_employee_digitized_signature/views/hr_employee_views.xml
  setup/hr_employee_digitized_signature/odoo/addons/hr_employee_digitized_signature
  setup/hr_employee_digitized_signature/setup.py
Labels: approved, ready to merge, bot is merging ⏳
