Repository OCA/hr, pull requests merged in 2022-04, with the labels that each got.

#1089 [FIX] hr_holidays_public: use tz.localize instead datetime.replace
  hr_holidays_public/models/resource_calendar.py
Labels: approved, bot is merging ⏳

#1073 [IMP] hr_personal_equipment_request: add colors depending on state to…
  hr_personal_equipment_request/views/hr_personal_equipment.xml
  hr_personal_equipment_request/views/hr_personal_equipment_request.xml
Labels: approved, bot is merging ⏳

#1093 Updated from template
  .copier-answers.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
Labels: approved, bot is merging ⏳

#1094 [14.0][FIX] hr_employee_calendar_planning: Prevent inconsistent company + Avoid create employees without calendar planing.
  hr_employee_calendar_planning/i18n/es.po
  hr_employee_calendar_planning/i18n/hr_employee_calendar_planning.pot
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/models/resource_calendar.py
Labels: bot is merging ⏳

#1045 [FIX] hr_employee_calendar_planning: Avoid error with parent
  hr_employee_calendar_planning/views/hr_employee_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1095 [14.0][FIX] hr_employee_calendar_planning: Avoid error with parent
  hr_employee_calendar_planning/views/hr_employee_views.xml
Labels: bot is merging ⏳
