Repository OCA/hr, pull requests merged in 2022-10, with the labels that each got.

#1049 [14.0][IMP] Add validity_end_date to hr_course model
  hr_course/__manifest__.py
  hr_course/data/ir_cron_data.xml
  hr_course/data/mail_channel.xml
  hr_course/data/mail_template.xml
  hr_course/i18n/fr.po
  hr_course/i18n/hr_course.pot
  hr_course/models/__init__.py
  hr_course/models/hr_course.py
  hr_course/models/hr_course_attendee.py
  hr_course/models/hr_course_category.py
  hr_course/models/hr_course_schedule.py
  hr_course/models/res_company.py
  hr_course/models/res_config_settings.py
  hr_course/readme/CONTRIBUTORS.rst
  hr_course/views/hr_course_schedule_views.xml
  hr_course/views/hr_settings.xml
Labels: approved, bot is merging ⏳, stale

#1144 [14.0][MIG] hr_contract_document
  hr_contract_document/README.rst
  hr_contract_document/__init__.py
  hr_contract_document/__manifest__.py
  hr_contract_document/i18n/es.po
  hr_contract_document/i18n/hr_contract_document.pot
  hr_contract_document/models/__init__.py
  hr_contract_document/models/hr_contract.py
  hr_contract_document/readme/CONTRIBUTORS.rst
  hr_contract_document/readme/DESCRIPTION.rst
  hr_contract_document/static/description/icon.png
  hr_contract_document/static/description/index.html
  hr_contract_document/tests/__init__.py
  hr_contract_document/tests/test_hr_contract_document.py
  hr_contract_document/views/hr_contract.xml
  hr_contract_document/views/ir_attachment.xml
  setup/hr_contract_document/odoo/addons/hr_contract_document
  setup/hr_contract_document/setup.py
Labels: bot is merging ⏳

#1147 [13.0][IMP] hr_employee_calendar_planning: Hide resource_calendar_id field from employee public form view
  hr_employee_calendar_planning/views/hr_employee_views.xml
Labels: bot is merging ⏳

#1149 [14.0][IMP] hr_employee_calendar_planning: Hide resource_calendar_id field from employee public form view
  hr_employee_calendar_planning/views/hr_employee_views.xml
Labels: approved, bot is merging ⏳

#1150 [15.0][IMP] hr_employee_calendar_planning: Hide resource_calendar_id field from employee public form view
  hr_employee_calendar_planning/views/hr_employee_views.xml
Labels: approved, bot is merging ⏳

#1145 [12.0][FIX] hr_expense_invoice: Change _validate_expense_invoice() function to use amount_total from invoices.
  hr_expense_invoice/models/hr_expense_sheet.py
Labels: approved, bot is merging ⏳
