Repository OCA/hr, pull requests merged in 2022-11, with the labels that each got.

#1079 [FIX] hr_holidays_public: Consider public holdays for leaves in hours
  hr_holidays_public/models/hr_leave.py
  hr_holidays_public/tests/__init__.py
  hr_holidays_public/tests/test_holidays_calculation.py
  hr_holidays_public/tests/test_holidays_calculation_common.py
  hr_holidays_public/tests/test_holidays_in_days_calculation.py
  hr_holidays_public/tests/test_holidays_in_hours_calculation.py
Labels: approved, bot is merging ⏳

#1151 [14.0] Fix Github Actions
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  hr_period/__init__.py
  hr_period/__manifest__.py
  hr_period/data/date_range_type.xml
  hr_period/data/ir_sequence_data.xml
  hr_period/i18n/de.po
  hr_period/i18n/es.po
  hr_period/i18n/es_AR.po
  hr_period/i18n/fr.po
  hr_period/i18n/hr.po
  hr_period/i18n/hr_period.pot
  hr_period/models/__init__.py
  hr_period/models/date_range_type.py
  hr_period/models/hr_contract.py
  hr_period/models/hr_employee.py
  hr_period/models/hr_fiscal_year.py
  hr_period/models/hr_payslip.py
  hr_period/models/hr_payslip_employees.py
  hr_period/models/hr_payslip_run.py
  hr_period/models/hr_period.py
  hr_period/readme/CONFIGURE.rst
  hr_period/readme/INSTALL.rst
  hr_period/readme/ROADMAP.rst
  hr_period/readme/USAGE.rst
  hr_period/security/hr_period_security.xml
  hr_period/security/ir.model.access.csv
  hr_period/tests/__init__.py
  hr_period/tests/test_hr_fiscalyear.py
  hr_period/tests/test_payslip.py
  hr_period/views/date_range_type_view.xml
  hr_period/views/hr_fiscalyear_view.xml
  hr_period/views/hr_payslip_employee_view.xml
  hr_period/views/hr_payslip_run_view.xml
  hr_period/views/hr_payslip_view.xml
  hr_period/views/hr_period_view.xml
Labels: approved, bot is merging ⏳

#1154 [MIG] hr_employee_firstname: Migration to 16.0
  hr_employee_firstname/README.rst
  hr_employee_firstname/__init__.py
  hr_employee_firstname/__manifest__.py
  hr_employee_firstname/i18n/ar.po
  hr_employee_firstname/i18n/ca.po
  hr_employee_firstname/i18n/cs_CZ.po
  hr_employee_firstname/i18n/de.po
  hr_employee_firstname/i18n/es.po
  hr_employee_firstname/i18n/fa.po
  hr_employee_firstname/i18n/fi.po
  hr_employee_firstname/i18n/fr.po
  hr_employee_firstname/i18n/hr.po
  hr_employee_firstname/i18n/hr_HR.po
  hr_employee_firstname/i18n/hr_employee_firstname.pot
  hr_employee_firstname/i18n/it.po
  hr_employee_firstname/i18n/lt.po
  hr_employee_firstname/i18n/nl_NL.po
  hr_employee_firstname/i18n/pt_BR.po
  hr_employee_firstname/i18n/ro.po
  hr_employee_firstname/i18n/sl.po
  hr_employee_firstname/init_hook.py
  hr_employee_firstname/models/__init__.py
  hr_employee_firstname/models/base_config_settings.py
  hr_employee_firstname/models/hr_employee.py
  hr_employee_firstname/models/hr_employee_base.py
  hr_employee_firstname/readme/CONTRIBUTORS.rst
  hr_employee_firstname/readme/DESCRIPTION.rst
  hr_employee_firstname/readme/USAGE.rst
  hr_employee_firstname/static/description/icon.png
  hr_employee_firstname/static/description/index.html
  hr_employee_firstname/tests/__init__.py
  hr_employee_firstname/tests/test_hr_employee_firstname.py
  hr_employee_firstname/views/base_config_view.xml
  hr_employee_firstname/views/hr_view.xml
  setup/hr_employee_firstname/odoo/addons/hr_employee_firstname
  setup/hr_employee_firstname/setup.py
Labels: approved, bot is merging ⏳

#1152 [15.0][MIG] hr_employee_ssn: Migration to 15.0
  hr_employee_ssn/README.rst
  hr_employee_ssn/__init__.py
  hr_employee_ssn/__manifest__.py
  hr_employee_ssn/i18n/de.po
  hr_employee_ssn/i18n/es_AR.po
  hr_employee_ssn/i18n/fr.po
  hr_employee_ssn/i18n/hr_employee_ssn.pot
  hr_employee_ssn/readme/CONTRIBUTORS.rst
  hr_employee_ssn/readme/DESCRIPTION.rst
  hr_employee_ssn/static/description/icon.png
  hr_employee_ssn/static/description/index.html
  hr_employee_ssn/views/hr_employee_views.xml
  setup/hr_employee_ssn/odoo/addons/hr_employee_ssn
  setup/hr_employee_ssn/setup.py
Labels: bot is merging ⏳

#1148 [12.0][ADD] hr_expense_advance_clearing_consolidation: consolidate more than one advance that has residual clearing
  hr_expense_advance_clearing_consolidation/README.rst
  hr_expense_advance_clearing_consolidation/__init__.py
  hr_expense_advance_clearing_consolidation/__manifest__.py
  hr_expense_advance_clearing_consolidation/models/__init__.py
  hr_expense_advance_clearing_consolidation/models/hr_expense_sheet.py
  hr_expense_advance_clearing_consolidation/readme/CONTRIBUTORS.rst
  hr_expense_advance_clearing_consolidation/readme/DESCRIPTION.rst
  hr_expense_advance_clearing_consolidation/readme/USAGE.rst
  hr_expense_advance_clearing_consolidation/static/description/icon.png
  hr_expense_advance_clearing_consolidation/static/description/index.html
  hr_expense_advance_clearing_consolidation/tests/__init__.py
  hr_expense_advance_clearing_consolidation/tests/test_hr_expense_advance_clearing_consolidation.py
  hr_expense_advance_clearing_consolidation/views/hr_expense_sheet_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1156 [MIG] hr_employee_lastnames: Migration to 16.0
  hr_employee_firstname/models/hr_employee.py
  hr_employee_lastnames/README.rst
  hr_employee_lastnames/__init__.py
  hr_employee_lastnames/__manifest__.py
  hr_employee_lastnames/hook.py
  hr_employee_lastnames/i18n/ca.po
  hr_employee_lastnames/i18n/es.po
  hr_employee_lastnames/i18n/hr_employee_lastnames.pot
  hr_employee_lastnames/i18n/pt_BR.po
  hr_employee_lastnames/models/__init__.py
  hr_employee_lastnames/models/hr_employee.py
  hr_employee_lastnames/models/hr_employee_base.py
  hr_employee_lastnames/readme/CONTRIBUTORS.rst
  hr_employee_lastnames/readme/DESCRIPTION.rst
  hr_employee_lastnames/readme/USAGE.rst
  hr_employee_lastnames/static/description/icon.png
  hr_employee_lastnames/static/description/index.html
  hr_employee_lastnames/tests/__init__.py
  hr_employee_lastnames/tests/test_hr_employee_lastnames.py
  hr_employee_lastnames/views/hr_views.xml
  setup/hr_employee_lastnames/odoo/addons/hr_employee_lastnames
  setup/hr_employee_lastnames/setup.py
Labels: approved, bot is merging ⏳

#1157 [15.0][MIG] hr_employee_document: Migration to 15.0
  hr_employee_document/README.rst
  hr_employee_document/__init__.py
  hr_employee_document/__manifest__.py
  hr_employee_document/i18n/fr.po
  hr_employee_document/i18n/hr.po
  hr_employee_document/i18n/hr_employee_document.pot
  hr_employee_document/models/__init__.py
  hr_employee_document/models/hr_employee.py
  hr_employee_document/models/hr_employee_public.py
  hr_employee_document/readme/CONTRIBUTORS.rst
  hr_employee_document/readme/DESCRIPTION.rst
  hr_employee_document/readme/ROADMAP.rst
  hr_employee_document/security/security.xml
  hr_employee_document/static/description/icon.png
  hr_employee_document/static/description/index.html
  hr_employee_document/tests/__init__.py
  hr_employee_document/tests/test_hr_employee_document.py
  hr_employee_document/views/hr_employee.xml
  hr_employee_document/views/hr_employee_public.xml
  setup/hr_employee_document/odoo/addons/hr_employee_document
  setup/hr_employee_document/setup.py
Labels: approved, bot is merging ⏳

#1155 [16.0][MIG] hr employee partner external
  hr_employee_partner_external/README.rst
  hr_employee_partner_external/__init__.py
  hr_employee_partner_external/__manifest__.py
  hr_employee_partner_external/i18n/es.po
  hr_employee_partner_external/i18n/hr_employee_partner_external.pot
  hr_employee_partner_external/i18n/it.po
  hr_employee_partner_external/models/__init__.py
  hr_employee_partner_external/models/hr_employee.py
  hr_employee_partner_external/readme/CONTRIBUTORS.rst
  hr_employee_partner_external/readme/DESCRIPTION.rst
  hr_employee_partner_external/readme/HISTORY.rst
  hr_employee_partner_external/readme/USAGE.rst
  hr_employee_partner_external/static/description/icon.png
  hr_employee_partner_external/static/description/index.html
  hr_employee_partner_external/views/hr_employee.xml
  setup/hr_employee_partner_external/odoo/addons/hr_employee_partner_external
  setup/hr_employee_partner_external/setup.py
Labels: approved, ready to merge

#1161 [14.0][MIG] hr_personal_equipment_variant_configurator: Migration to 14.0
  hr_personal_equipment_variant_configurator/README.rst
  hr_personal_equipment_variant_configurator/__init__.py
  hr_personal_equipment_variant_configurator/__manifest__.py
  hr_personal_equipment_variant_configurator/i18n/es.po
  hr_personal_equipment_variant_configurator/i18n/es_PA.po
  hr_personal_equipment_variant_configurator/i18n/hr_personal_equipment_variant_configurator.pot
  hr_personal_equipment_variant_configurator/models/__init__.py
  hr_personal_equipment_variant_configurator/models/hr_personal_equipment.py
  hr_personal_equipment_variant_configurator/readme/CONTRIBUTORS.rst
  hr_personal_equipment_variant_configurator/readme/DESCRIPTION.rst
  hr_personal_equipment_variant_configurator/readme/INSTALL.rst
  hr_personal_equipment_variant_configurator/static/description/icon.png
  hr_personal_equipment_variant_configurator/static/description/index.html
  hr_personal_equipment_variant_configurator/views/hr_personal_equipment_request.xml
  setup/hr_personal_equipment_variant_configurator/odoo/addons/hr_personal_equipment_variant_configurator
  setup/hr_personal_equipment_variant_configurator/setup.py
Labels: approved, bot is merging ⏳

#1165 [UPD] update copier v15.0
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#1158 [15.0][MIG] hr_employee_id
  hr_employee_id/README.rst
  hr_employee_id/__init__.py
  hr_employee_id/__manifest__.py
  hr_employee_id/data/hr_employee_sequence.xml
  hr_employee_id/i18n/ar.po
  hr_employee_id/i18n/cs_CZ.po
  hr_employee_id/i18n/de.po
  hr_employee_id/i18n/es.po
  hr_employee_id/i18n/fi.po
  hr_employee_id/i18n/fr.po
  hr_employee_id/i18n/hr.po
  hr_employee_id/i18n/hr_HR.po
  hr_employee_id/i18n/hr_employee_id.pot
  hr_employee_id/i18n/it.po
  hr_employee_id/i18n/lt.po
  hr_employee_id/i18n/nl_NL.po
  hr_employee_id/i18n/pt_BR.po
  hr_employee_id/i18n/ro.po
  hr_employee_id/i18n/sl.po
  hr_employee_id/models/__init__.py
  hr_employee_id/models/hr_employee.py
  hr_employee_id/models/res_company.py
  hr_employee_id/models/res_config_settings.py
  hr_employee_id/readme/CONFIGURE.rst
  hr_employee_id/readme/CONTRIBUTORS.rst
  hr_employee_id/readme/DESCRIPTION.rst
  hr_employee_id/readme/INSTALL.rst
  hr_employee_id/readme/ROADMAP.rst
  hr_employee_id/readme/USAGE.rst
  hr_employee_id/static/description/icon.png
  hr_employee_id/static/description/index.html
  hr_employee_id/tests/__init__.py
  hr_employee_id/tests/test_employee_id.py
  hr_employee_id/views/hr_employee_views.xml
  hr_employee_id/views/res_config_settings_views.xml
  setup/hr_employee_id/odoo/addons/hr_employee_id
  setup/hr_employee_id/setup.py
Labels: approved, bot is merging ⏳

#1164 [15.0][MIG] hr_department_code
  hr_department_code/README.rst
  hr_department_code/__init__.py
  hr_department_code/__manifest__.py
  hr_department_code/i18n/de.po
  hr_department_code/i18n/hr.po
  hr_department_code/i18n/hr_department_code.pot
  hr_department_code/models/__init__.py
  hr_department_code/models/hr_department.py
  hr_department_code/readme/CONTRIBUTORS.rst
  hr_department_code/readme/DESCRIPTION.rst
  hr_department_code/static/description/icon.png
  hr_department_code/static/description/index.html
  hr_department_code/tests/__init__.py
  hr_department_code/tests/test_hr_department_code.py
  hr_department_code/views/hr_department_views.xml
  setup/hr_department_code/odoo/addons/hr_department_code
  setup/hr_department_code/setup.py
Labels: approved, bot is merging ⏳

#1168 [14.0][FIX] hr_employee_calendar_planning: prevent loop
  hr_employee_calendar_planning/models/hr_employee.py
Labels: approved, bot is merging ⏳

#1169 [15.0][FIX] hr_employee_calendar_planning: prevent loop
  hr_employee_calendar_planning/models/hr_employee.py
Labels: approved, bot is merging ⏳
