Repository OCA/hr, pull requests merged in 2023-11, with the labels that each got.

#1289 [IMP] hr_employee_firstname: rename hooks file
  hr_employee_firstname/__init__.py
  hr_employee_firstname/__manifest__.py
  hr_employee_firstname/hooks.py
Labels: approved, bot is merging ⏳

#1314 [17.0][MIG] hr_employee_firstname: Migration to 17.0
  hr_employee_firstname/README.rst
  hr_employee_firstname/__init__.py
  hr_employee_firstname/__manifest__.py
  hr_employee_firstname/hooks.py
  hr_employee_firstname/i18n/ar.po
  hr_employee_firstname/i18n/ca.po
  hr_employee_firstname/i18n/cs_CZ.po
  hr_employee_firstname/i18n/de.po
  hr_employee_firstname/i18n/es.po
  hr_employee_firstname/i18n/fa.po
  hr_employee_firstname/i18n/fi.po
  hr_employee_firstname/i18n/fr.po
  hr_employee_firstname/i18n/hr.po
  hr_employee_firstname/i18n/hr_HR.po
  hr_employee_firstname/i18n/hr_employee_firstname.pot
  hr_employee_firstname/i18n/it.po
  hr_employee_firstname/i18n/lt.po
  hr_employee_firstname/i18n/nl_NL.po
  hr_employee_firstname/i18n/pt_BR.po
  hr_employee_firstname/i18n/ro.po
  hr_employee_firstname/i18n/sl.po
  hr_employee_firstname/models/__init__.py
  hr_employee_firstname/models/base_config_settings.py
  hr_employee_firstname/models/hr_employee.py
  hr_employee_firstname/models/hr_employee_base.py
  hr_employee_firstname/pyproject.toml
  hr_employee_firstname/readme/CONTRIBUTORS.md
  hr_employee_firstname/readme/DESCRIPTION.md
  hr_employee_firstname/readme/USAGE.md
  hr_employee_firstname/static/description/icon.png
  hr_employee_firstname/static/description/index.html
  hr_employee_firstname/tests/__init__.py
  hr_employee_firstname/tests/test_hr_employee_firstname.py
  hr_employee_firstname/views/base_config_view.xml
  hr_employee_firstname/views/hr_view.xml
Labels: bot is merging ⏳

#1320 [14.0][FIX] (Backport 15.0 to 14.0) hr_employee_document: Remove record rules from hr.employee to avoid side effects
  hr_employee_document/README.rst
  hr_employee_document/__manifest__.py
  hr_employee_document/models/__init__.py
  hr_employee_document/models/hr_employee.py
  hr_employee_document/models/hr_employee_public.py
  hr_employee_document/models/ir_rule.py
  hr_employee_document/security/security.xml
  hr_employee_document/static/description/index.html
  hr_employee_document/tests/test_hr_employee_document.py
Labels: approved, bot is merging ⏳

#1316 [17.0][MIG] hr_holidays_settings : Migration to 17.0
  hr_holidays_settings/README.rst
  hr_holidays_settings/__init__.py
  hr_holidays_settings/__manifest__.py
  hr_holidays_settings/i18n/ar.po
  hr_holidays_settings/i18n/de.po
  hr_holidays_settings/i18n/es.po
  hr_holidays_settings/i18n/fa.po
  hr_holidays_settings/i18n/fi.po
  hr_holidays_settings/i18n/fr.po
  hr_holidays_settings/i18n/hr.po
  hr_holidays_settings/i18n/hr_HR.po
  hr_holidays_settings/i18n/hr_holidays_settings.pot
  hr_holidays_settings/i18n/it.po
  hr_holidays_settings/i18n/nl_NL.po
  hr_holidays_settings/i18n/pt_BR.po
  hr_holidays_settings/i18n/ro.po
  hr_holidays_settings/i18n/sl.po
  hr_holidays_settings/pyproject.toml
  hr_holidays_settings/readme/CONTRIBUTORS.md
  hr_holidays_settings/readme/DESCRIPTION.md
  hr_holidays_settings/readme/USAGE.md
  hr_holidays_settings/static/description/icon.png
  hr_holidays_settings/static/description/index.html
  hr_holidays_settings/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#1282 [15.0][MIG] hr_contract_type
  hr_contract_type/README.rst
  hr_contract_type/__init__.py
  hr_contract_type/__manifest__.py
  hr_contract_type/hooks.py
  hr_contract_type/i18n/es.po
  hr_contract_type/i18n/es_PA.po
  hr_contract_type/i18n/hr_contract_type.pot
  hr_contract_type/i18n/it.po
  hr_contract_type/i18n/pt_BR.po
  hr_contract_type/models/__init__.py
  hr_contract_type/models/hr_contract.py
  hr_contract_type/models/hr_contract_type.py
  hr_contract_type/readme/CONTRIBUTORS.rst
  hr_contract_type/readme/DESCRIPTION.rst
  hr_contract_type/readme/ROADMAP.rst
  hr_contract_type/security/ir.model.access.csv
  hr_contract_type/static/description/icon.png
  hr_contract_type/static/description/index.html
  hr_contract_type/views/hr_contract.xml
  hr_contract_type/views/hr_contract_type.xml
  setup/hr_contract_type/odoo/addons/hr_contract_type
  setup/hr_contract_type/setup.py
Labels: approved, bot is merging ⏳

#1323 [FIX] hr_employee_document: ir.rule _compute_domain method
  hr_employee_document/models/ir_rule.py
Labels: approved, bot is merging ⏳
