Repository OCA/hr, pull requests merged in 2023-03, with the labels that each got.

#1199 [13.0][IMP] hr_course: Mis changes
  hr_course/models/hr_course.py
  hr_course/views/hr_course_views.xml
Labels: approved, bot is merging ⏳

#1204 [14.0][IMP] hr_course: Mis changes
  hr_course/models/hr_course.py
  hr_course/views/hr_course_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1208 [15.0][IMP] hr_course: Mis changes
  hr_course/models/hr_course.py
  hr_course/views/hr_course_views.xml
Labels: approved, bot is merging ⏳

#1207 [FIX] hr_course_survey: use render template properly
  hr_course_survey/models/hr_course_attendee.py
Labels: approved, bot is merging ⏳

#1209 [16.0][IMP] hr_course: Mis changes
  hr_course/models/hr_course.py
  hr_course/views/hr_course_views.xml
Labels: approved

#1210 [13.0][ADD] hr_study: New module
  hr_study/README.rst
  hr_study/__init__.py
  hr_study/__manifest__.py
  hr_study/demo/hr_study.xml
  hr_study/i18n/es.po
  hr_study/i18n/hr_study.pot
  hr_study/models/__init__.py
  hr_study/models/hr_employee.py
  hr_study/models/hr_study.py
  hr_study/readme/CONFIGURE.rst
  hr_study/readme/CONTRIBUTORS.rst
  hr_study/readme/DESCRIPTION.rst
  hr_study/readme/ROADMAP.rst
  hr_study/readme/USAGE.rst
  hr_study/security/ir.model.access.csv
  hr_study/security/security.xml
  hr_study/static/description/icon.png
  hr_study/static/description/index.html
  hr_study/tests/__init__.py
  hr_study/tests/test_hr_study.py
  hr_study/views/hr_employee_view.xml
  hr_study/views/hr_study_views.xml
  setup/hr_study/odoo/addons/hr_study
  setup/hr_study/setup.py
Labels: approved, bot is merging ⏳

#1211 [15.0][MIG] hr_study: Migration to 15.0
  hr_study/README.rst
  hr_study/__init__.py
  hr_study/__manifest__.py
  hr_study/demo/hr_study.xml
  hr_study/i18n/es.po
  hr_study/i18n/hr_study.pot
  hr_study/models/__init__.py
  hr_study/models/hr_employee.py
  hr_study/models/hr_study.py
  hr_study/readme/CONFIGURE.rst
  hr_study/readme/CONTRIBUTORS.rst
  hr_study/readme/DESCRIPTION.rst
  hr_study/readme/ROADMAP.rst
  hr_study/readme/USAGE.rst
  hr_study/security/ir.model.access.csv
  hr_study/security/security.xml
  hr_study/static/description/icon.png
  hr_study/static/description/index.html
  hr_study/tests/__init__.py
  hr_study/tests/test_hr_study.py
  hr_study/views/hr_employee_view.xml
  hr_study/views/hr_study_views.xml
  setup/hr_study/odoo/addons/hr_study
  setup/hr_study/setup.py
Labels: approved, bot is merging ⏳

#1190 [15.0][mig]-hr_worked_days_from_timesheet
  hr_worked_days_from_timesheet/README.rst
  hr_worked_days_from_timesheet/__init__.py
  hr_worked_days_from_timesheet/__manifest__.py
  hr_worked_days_from_timesheet/i18n/cs_CZ.po
  hr_worked_days_from_timesheet/i18n/de.po
  hr_worked_days_from_timesheet/i18n/es.po
  hr_worked_days_from_timesheet/i18n/fr.po
  hr_worked_days_from_timesheet/i18n/hr_worked_days_from_timesheet.pot
  hr_worked_days_from_timesheet/i18n/sl.po
  hr_worked_days_from_timesheet/models/__init__.py
  hr_worked_days_from_timesheet/models/hr_payslip.py
  hr_worked_days_from_timesheet/models/hr_payslip_worked_days.py
  hr_worked_days_from_timesheet/readme/CONTRIBUTORS.rst
  hr_worked_days_from_timesheet/readme/DESCRIPTION.rst
  hr_worked_days_from_timesheet/readme/USAGE.rst
  hr_worked_days_from_timesheet/static/description/icon.png
  hr_worked_days_from_timesheet/static/description/index.html
  hr_worked_days_from_timesheet/tests/__init__.py
  hr_worked_days_from_timesheet/tests/test_worked_days_from_timesheet.py
  hr_worked_days_from_timesheet/views/hr_payslip_view.xml
  setup/hr_worked_days_from_timesheet/odoo/addons/hr_worked_days_from_timesheet
  setup/hr_worked_days_from_timesheet/setup.py
Labels: approved, ready to merge, bot is merging ⏳
