Repository OCA/hr, pull requests merged in 2023-06, with the labels that each got.

#1238 [14.0][FIX] hr_employee_calendar_planning: fill calendar if empty
  hr_employee_calendar_planning/models/hr_employee.py
Labels: approved, bot is merging ⏳

#1240 [15.0][FIX] hr_employee_calendar_planning: fill calendar if empty
  hr_employee_calendar_planning/models/hr_employee.py
Labels: approved, bot is merging ⏳

#1236 [15.0][IMP] hr_course: Add internal notes
  hr_course/models/hr_course_schedule.py
  hr_course/views/hr_course_schedule_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1239 [14.0][IMP] hr_employee_calendar_planning: Allow to archive when calendars have finished
  hr_employee_calendar_planning/__manifest__.py
  hr_employee_calendar_planning/models/resource_calendar.py
  hr_employee_calendar_planning/views/resource_calendar_views.xml
Labels: approved, bot is merging ⏳

#1249 [14.0][BKP][MIG] hr_employee_birthday_mail
  hr_employee_birthday_mail/README.rst
  hr_employee_birthday_mail/__init__.py
  hr_employee_birthday_mail/__manifest__.py
  hr_employee_birthday_mail/data/data.xml
  hr_employee_birthday_mail/data/ir_cron.xml
  hr_employee_birthday_mail/models/__init__.py
  hr_employee_birthday_mail/models/hr_employee.py
  hr_employee_birthday_mail/readme/CONTRIBUTORS.rst
  hr_employee_birthday_mail/readme/DESCRIPTION.rst
  hr_employee_birthday_mail/readme/USAGE.rst
  hr_employee_birthday_mail/views/hr_employee_views.xml
  setup/hr_employee_birthday_mail/odoo/addons/hr_employee_birthday_mail
  setup/hr_employee_birthday_mail/setup.py
Labels: approved, bot is merging ⏳

#1257 [14.0][RM] hr_holidays_setting: migrated in wrong repository
  hr_holidays_settings/README.rst
  hr_holidays_settings/__init__.py
  hr_holidays_settings/__manifest__.py
  hr_holidays_settings/i18n/ar.po
  hr_holidays_settings/i18n/de.po
  hr_holidays_settings/i18n/es.po
  hr_holidays_settings/i18n/es_AR.po
  hr_holidays_settings/i18n/fa.po
  hr_holidays_settings/i18n/fi.po
  hr_holidays_settings/i18n/fr.po
  hr_holidays_settings/i18n/hr.po
  hr_holidays_settings/i18n/hr_HR.po
  hr_holidays_settings/i18n/hr_holidays_settings.pot
  hr_holidays_settings/i18n/it.po
  hr_holidays_settings/i18n/nl_NL.po
  hr_holidays_settings/i18n/pt_BR.po
  hr_holidays_settings/i18n/ro.po
  hr_holidays_settings/i18n/sl.po
  hr_holidays_settings/readme/CONTRIBUTORS.rst
  hr_holidays_settings/readme/DESCRIPTION.rst
  hr_holidays_settings/readme/USAGE.rst
  hr_holidays_settings/static/description/icon.png
  hr_holidays_settings/static/description/index.html
  hr_holidays_settings/views/res_config_settings.xml
  setup/hr_holidays_settings/odoo/addons/hr_holidays_settings
  setup/hr_holidays_settings/setup.py
Labels: bot is merging ⏳

#1253 [15.0][IMP] hr_employee_calendar_planning: Allow to archive when calendars have finished
  hr_employee_calendar_planning/__manifest__.py
  hr_employee_calendar_planning/models/resource_calendar.py
  hr_employee_calendar_planning/views/resource_calendar_views.xml
Labels: approved, bot is merging ⏳

#1259 [13.0][IMP] hr_employee_calendar_planning: set calendar_ids from Create employee button from user
  hr_employee_calendar_planning/__manifest__.py
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/models/resource_calendar.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
  hr_employee_calendar_planning/views/resource_calendar_views.xml
Labels: approved, bot is merging ⏳
