Repository OCA/hr, pull requests merged in 2023-05, with the labels that each got.

#1222 [16.0][MIG] hr_employee_phone_extension: Migration to 16.0
  hr_employee_phone_extension/README.rst
  hr_employee_phone_extension/__init__.py
  hr_employee_phone_extension/__manifest__.py
  hr_employee_phone_extension/i18n/ar.po
  hr_employee_phone_extension/i18n/cs_CZ.po
  hr_employee_phone_extension/i18n/de.po
  hr_employee_phone_extension/i18n/es.po
  hr_employee_phone_extension/i18n/es_AR.po
  hr_employee_phone_extension/i18n/fi.po
  hr_employee_phone_extension/i18n/fr.po
  hr_employee_phone_extension/i18n/hr.po
  hr_employee_phone_extension/i18n/hr_HR.po
  hr_employee_phone_extension/i18n/hr_employee_phone_extension.pot
  hr_employee_phone_extension/i18n/it.po
  hr_employee_phone_extension/i18n/lt.po
  hr_employee_phone_extension/i18n/nl_NL.po
  hr_employee_phone_extension/i18n/pt.po
  hr_employee_phone_extension/i18n/pt_BR.po
  hr_employee_phone_extension/i18n/ro.po
  hr_employee_phone_extension/i18n/sl.po
  hr_employee_phone_extension/models/__init__.py
  hr_employee_phone_extension/models/hr_employee.py
  hr_employee_phone_extension/readme/CONTRIBUTORS.rst
  hr_employee_phone_extension/readme/DESCRIPTION.rst
  hr_employee_phone_extension/readme/INSTALL.rst
  hr_employee_phone_extension/readme/USAGE.rst
  hr_employee_phone_extension/static/description/icon.png
  hr_employee_phone_extension/static/description/index.html
  hr_employee_phone_extension/views/hr_employee_view.xml
  setup/hr_employee_phone_extension/odoo/addons/hr_employee_phone_extension
  setup/hr_employee_phone_extension/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#1224 [14.0][IMP] hr_employee_calendar_planning: set calendar_ids from Create employee button from user
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
Labels: approved, bot is merging ⏳

#1227 [15.0][IMP] hr_employee_calendar_planning: set calendar_ids from Create employee button from user
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
Labels: approved, bot is merging ⏳

#1232 [14.0][IMP] hr_employee_calendar_planning: remove date_start from _sync_user
  hr_employee_calendar_planning/models/hr_employee.py
Labels: bot is merging ⏳

#1235 [12.0][FIX] - hr_attendance_rfid - Handle ValidationError properly
  hr_attendance_rfid/models/hr_employee.py
Labels: bot is merging ⏳
