Repository OCA/hr, pull requests merged in 2023-10, with the labels that each got.

#1287 [15.0][IMP] hr: test performance improvement
  hr_contract_employee_calendar_planning/tests/test_hr_contract_employee_calendar_planning.py
Labels: bot is merging ⏳

#1286 [12.0][FIX] hr_employee_calendar_planning: Allow duplicate employee and not copy resource calendar
  hr_employee_calendar_planning/models/hr_employee.py
Labels: approved, bot is merging ⏳

#1288 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  hr_course/i18n/hr_course.pot
  hr_course/views/hr_course_category_views.xml
  hr_employee_id/i18n/fr.po
  hr_employee_id/i18n/hr.po
  hr_employee_id/i18n/hr_HR.po
  hr_employee_id/i18n/nl_NL.po
  hr_employee_id/i18n/sl.po
  hr_employee_medical_examination/i18n/hr_employee_medical_examination.pot
  hr_employee_medical_examination/security/hr_employee_medical_examination_security.xml
  hr_employee_relative/data/data_relative_relation.xml
  hr_employee_relative/i18n/hr_employee_relative.pot
  hr_employee_relative/views/hr_employee_relative.xml
  hr_org_chart_overview/static/src/js/hr_org_chart_overview.js
  hr_org_chart_overview/views/hr_views.xml
  hr_personal_equipment_request/i18n/hr_personal_equipment_request.pot
  hr_personal_equipment_request/views/hr_personal_equipment.xml
  hr_personal_equipment_request_tier_validation/i18n/hr_personal_equipment_request_tier_validation.pot
  hr_recruitment_notification/data/message_subtypes.xml
Labels: help wanted, needs review, bot is merging ⏳
