Repository OCA/hr, pull requests merged in 2023-04, with the labels that each got.

#1219 [15.0][MIG] hr_employee_phone_extension
  hr_employee_phone_extension/README.rst
  hr_employee_phone_extension/__init__.py
  hr_employee_phone_extension/__manifest__.py
  hr_employee_phone_extension/i18n/ar.po
  hr_employee_phone_extension/i18n/cs_CZ.po
  hr_employee_phone_extension/i18n/de.po
  hr_employee_phone_extension/i18n/es.po
  hr_employee_phone_extension/i18n/es_AR.po
  hr_employee_phone_extension/i18n/fi.po
  hr_employee_phone_extension/i18n/fr.po
  hr_employee_phone_extension/i18n/hr.po
  hr_employee_phone_extension/i18n/hr_HR.po
  hr_employee_phone_extension/i18n/hr_employee_phone_extension.pot
  hr_employee_phone_extension/i18n/it.po
  hr_employee_phone_extension/i18n/lt.po
  hr_employee_phone_extension/i18n/nl_NL.po
  hr_employee_phone_extension/i18n/pt.po
  hr_employee_phone_extension/i18n/pt_BR.po
  hr_employee_phone_extension/i18n/ro.po
  hr_employee_phone_extension/i18n/sl.po
  hr_employee_phone_extension/models/__init__.py
  hr_employee_phone_extension/models/hr_employee.py
  hr_employee_phone_extension/readme/CONTRIBUTORS.rst
  hr_employee_phone_extension/readme/DESCRIPTION.rst
  hr_employee_phone_extension/readme/INSTALL.rst
  hr_employee_phone_extension/readme/USAGE.rst
  hr_employee_phone_extension/static/description/icon.png
  hr_employee_phone_extension/static/description/index.html
  hr_employee_phone_extension/views/hr_employee_view.xml
  setup/hr_employee_phone_extension/odoo/addons/hr_employee_phone_extension
  setup/hr_employee_phone_extension/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1217 [FIX] hr_course_survey: URL was not working properly
  hr_course_survey/data/mail.xml
Labels: bot is merging ⏳

#1200 [14.0][FIX] hr_employee_ppe: compute field contains PPE
  hr_employee_ppe/models/hr_personal_equipment_request.py
Labels: approved, ready to merge, bot is merging ⏳

#1221 [14.0] [IMP] hr_employee_service: Add helper function
  hr_employee_service/models/hr_employee.py
  hr_employee_service/tests/test_hr_employee_service.py
Labels: bot is merging ⏳

#1182 [15.0][MIG]hr_contract_employee_calendar_planning
  hr_contract_employee_calendar_planning/README.rst
  hr_contract_employee_calendar_planning/__init__.py
  hr_contract_employee_calendar_planning/__manifest__.py
  hr_contract_employee_calendar_planning/hooks.py
  hr_contract_employee_calendar_planning/i18n/hr_contract_employee_calendar_planning.pot
  hr_contract_employee_calendar_planning/models/__init__.py
  hr_contract_employee_calendar_planning/models/contract.py
  hr_contract_employee_calendar_planning/readme/CONTRIBUTORS.rst
  hr_contract_employee_calendar_planning/readme/DESCRIPTION.rst
  hr_contract_employee_calendar_planning/readme/USAGE.rst
  hr_contract_employee_calendar_planning/static/description/icon.png
  hr_contract_employee_calendar_planning/static/description/index.html
  hr_contract_employee_calendar_planning/tests/__init__.py
  hr_contract_employee_calendar_planning/tests/test_hr_contract_employee_calendar_planning.py
  hr_contract_employee_calendar_planning/views/contract.xml
  setup/hr_contract_employee_calendar_planning/odoo/addons/hr_contract_employee_calendar_planning
  setup/hr_contract_employee_calendar_planning/setup.py
Labels: approved, migration, bot is merging ⏳

#1202 [15.0][MIG] hr_contract_multi_job
  hr_contract_multi_job/README.rst
  hr_contract_multi_job/__init__.py
  hr_contract_multi_job/__manifest__.py
  hr_contract_multi_job/i18n/ar.po
  hr_contract_multi_job/i18n/de.po
  hr_contract_multi_job/i18n/es.po
  hr_contract_multi_job/i18n/fi.po
  hr_contract_multi_job/i18n/fr.po
  hr_contract_multi_job/i18n/hr_contract_multi_job.pot
  hr_contract_multi_job/i18n/it.po
  hr_contract_multi_job/i18n/pt_BR.po
  hr_contract_multi_job/i18n/ro.po
  hr_contract_multi_job/i18n/sl.po
  hr_contract_multi_job/models/__init__.py
  hr_contract_multi_job/models/hr_contract.py
  hr_contract_multi_job/models/hr_contract_job.py
  hr_contract_multi_job/models/hr_job.py
  hr_contract_multi_job/readme/CONTRIBUTORS.rst
  hr_contract_multi_job/readme/DESCRIPTION.rst
  hr_contract_multi_job/readme/USAGE.rst
  hr_contract_multi_job/security/ir.model.access.csv
  hr_contract_multi_job/static/description/icon.png
  hr_contract_multi_job/static/description/index.html
  hr_contract_multi_job/tests/__init__.py
  hr_contract_multi_job/tests/test_hr_contract_multi_jobs.py
  hr_contract_multi_job/views/hr_contract_view.xml
  setup/hr_contract_multi_job/odoo/addons/hr_contract_multi_job
  setup/hr_contract_multi_job/setup.py
Labels: approved, ready to merge, bot is merging ⏳
