Repository OCA/hr, pull requests merged in 2023-02, with the labels that each got.

#1184 [14.0][FIX] hr_contract_document: fix read
  hr_contract_document/models/hr_contract.py
Labels: approved, bot is merging ⏳

#1185 [14.0][FIX] hr_course & hr_employee_medical_examination: fix read
  hr_course/models/hr_employee.py
  hr_employee_medical_examination/wizards/wizard_generate_medical_examination.py
Labels: approved, bot is merging ⏳

#1191 [13.0][IMP] hr_employee_calendar_planning: Allow duplicate employee
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
Labels: approved, bot is merging ⏳

#1193 [14.0][IMP] hr_employee_calendar_planning: Allow duplicate employee
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
Labels: approved, bot is merging ⏳

#1194 [15.0][IMP] hr_employee_calendar_planning: Allow duplicate employee
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
Labels: bot is merging ⏳

#1187 [16.0][MIG] hr_employee_digitized_signature: Migration to 16.0
  hr_employee_digitized_signature/README.rst
  hr_employee_digitized_signature/__init__.py
  hr_employee_digitized_signature/__manifest__.py
  hr_employee_digitized_signature/i18n/de.po
  hr_employee_digitized_signature/i18n/es_AR.po
  hr_employee_digitized_signature/i18n/hr_employee_digitized_signature.pot
  hr_employee_digitized_signature/models/__init__.py
  hr_employee_digitized_signature/models/hr_employee.py
  hr_employee_digitized_signature/readme/CONTRIBUTORS.rst
  hr_employee_digitized_signature/readme/DESCRIPTION.rst
  hr_employee_digitized_signature/static/description/icon.png
  hr_employee_digitized_signature/static/description/index.html
  hr_employee_digitized_signature/views/hr_employee_views.xml
  setup/hr_employee_digitized_signature/odoo/addons/hr_employee_digitized_signature
  setup/hr_employee_digitized_signature/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1160 [15.0][FIX] hr_employee_birth_name: Fixed bug when accessing hr.employee
  hr_employee_birth_name/models/hr_employee.py
Labels: bot is merging ⏳

#1180 [16.0][MIG] hr_employee_relative: Migration to 16.0.
  hr_employee_relative/README.rst
  hr_employee_relative/__init__.py
  hr_employee_relative/__manifest__.py
  hr_employee_relative/data/data_relative_relation.xml
  hr_employee_relative/i18n/de.po
  hr_employee_relative/i18n/es.po
  hr_employee_relative/i18n/fr.po
  hr_employee_relative/i18n/hr.po
  hr_employee_relative/i18n/hr_employee_relative.pot
  hr_employee_relative/i18n/pt_BR.po
  hr_employee_relative/models/__init__.py
  hr_employee_relative/models/hr_employee.py
  hr_employee_relative/models/hr_employee_relative.py
  hr_employee_relative/models/hr_employee_relative_relation.py
  hr_employee_relative/readme/CONTRIBUTORS.rst
  hr_employee_relative/readme/DESCRIPTION.rst
  hr_employee_relative/security/ir.model.access.csv
  hr_employee_relative/static/description/icon.png
  hr_employee_relative/static/description/index.html
  hr_employee_relative/tests/__init__.py
  hr_employee_relative/tests/test_hr_employee_relatives.py
  hr_employee_relative/views/hr_employee.xml
  hr_employee_relative/views/hr_employee_relative.xml
  requirements.txt
  setup/hr_employee_relative/odoo/addons/hr_employee_relative
  setup/hr_employee_relative/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1195 [14.0][FIX] hr_employee_birth_name: add missing group to avoid access errors
  hr_employee_birth_name/models/hr_employee.py
Labels: bot is merging ⏳

#1197 [14.0][MIG] resource_hook: Migration to 14.0
  resource_hook/README.rst
  resource_hook/__init__.py
  resource_hook/__manifest__.py
  resource_hook/hooks.py
  resource_hook/i18n/es.po
  resource_hook/i18n/resource_hook.pot
  resource_hook/models/__init__.py
  resource_hook/models/resource_calendar.py
  resource_hook/models/resource_mixin.py
  resource_hook/readme/CONTRIBUTORS.rst
  resource_hook/readme/DESCRIPTION.rst
  resource_hook/readme/HISTORY.rst
  resource_hook/static/description/icon.png
  resource_hook/static/description/index.html
  setup/resource_hook/odoo/addons/resource_hook
  setup/resource_hook/setup.py
Labels: approved, bot is merging ⏳
