Repository OCA/hr, pull requests merged in 2024-05, with the labels that each got.

#1347 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  hr_employee_second_lastname/hooks.py
Labels: help wanted, needs review, bot is merging ⏳

#1346 [15.0][IMP] hr_job_category: Add tests and fix tag inheritance
  hr_job_category/models/hr.py
  hr_job_category/tests/test_hr_job_categories.py
Labels: bot is merging ⏳

#1326 [16.0][MIG] hr_department_code
  hr_department_code/README.rst
  hr_department_code/__init__.py
  hr_department_code/__manifest__.py
  hr_department_code/i18n/de.po
  hr_department_code/i18n/hr.po
  hr_department_code/i18n/hr_department_code.pot
  hr_department_code/i18n/it.po
  hr_department_code/models/__init__.py
  hr_department_code/models/hr_department.py
  hr_department_code/readme/CONTRIBUTORS.rst
  hr_department_code/readme/DESCRIPTION.rst
  hr_department_code/static/description/icon.png
  hr_department_code/static/description/index.html
  hr_department_code/tests/__init__.py
  hr_department_code/tests/test_hr_department_code.py
  hr_department_code/views/hr_department_views.xml
  setup/hr_department_code/odoo/addons/hr_department_code
  setup/hr_department_code/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1353 [16.0][FIX] hr_employee_phone_extension: Add fields in model hr.employee.base
  hr_employee_phone_extension/README.rst
  hr_employee_phone_extension/__manifest__.py
  hr_employee_phone_extension/i18n/es.po
  hr_employee_phone_extension/i18n/hr_employee_phone_extension.pot
  hr_employee_phone_extension/models/__init__.py
  hr_employee_phone_extension/models/hr_employee_base.py
  hr_employee_phone_extension/readme/CONTRIBUTORS.rst
  hr_employee_phone_extension/static/description/index.html
  hr_employee_phone_extension/views/hr_employee_public_views.xml
  hr_employee_phone_extension/views/hr_employee_views.xml
Labels: approved, bot is merging ⏳

#1354 [17.0][MIG] hr_employee_document: Migration to 17.0
  hr_employee_document/README.rst
  hr_employee_document/__init__.py
  hr_employee_document/__manifest__.py
  hr_employee_document/i18n/es.po
  hr_employee_document/i18n/fr.po
  hr_employee_document/i18n/hr.po
  hr_employee_document/i18n/hr_employee_document.pot
  hr_employee_document/i18n/it.po
  hr_employee_document/models/__init__.py
  hr_employee_document/models/hr_employee.py
  hr_employee_document/models/hr_employee_public.py
  hr_employee_document/models/ir_rule.py
  hr_employee_document/pyproject.toml
  hr_employee_document/readme/CONTRIBUTORS.md
  hr_employee_document/readme/DESCRIPTION.md
  hr_employee_document/readme/ROADMAP.md
  hr_employee_document/static/description/icon.png
  hr_employee_document/static/description/index.html
  hr_employee_document/tests/__init__.py
  hr_employee_document/tests/test_hr_employee_document.py
  hr_employee_document/views/hr_employee.xml
  hr_employee_document/views/hr_employee_public.xml
Labels: approved, ready to merge, bot is merging ⏳

#1356 [12.0][IMP] hr_holidays_credit: add unit in form selection widget & plurals management
  hr_holidays_credit/models/hr_leave_type.py
  hr_holidays_credit/tests/test_hr_holidays_credit.py
Labels: bot is merging ⏳

#1349 [16.0][ADD] hr_employee_group_overview_readonly
  hr_employee_group_overview_readonly/README.rst
  hr_employee_group_overview_readonly/__init__.py
  hr_employee_group_overview_readonly/__manifest__.py
  hr_employee_group_overview_readonly/models/__init__.py
  hr_employee_group_overview_readonly/models/hr_employee.py
  hr_employee_group_overview_readonly/readme/CONTRIBUTORS.rst
  hr_employee_group_overview_readonly/readme/DESCRIPTION.rst
  hr_employee_group_overview_readonly/readme/USAGE.rst
  hr_employee_group_overview_readonly/security/hr_employee_security.xml
  hr_employee_group_overview_readonly/security/ir.model.access.csv
  hr_employee_group_overview_readonly/static/description/index.html
  hr_employee_group_overview_readonly/views/hr_employee_views.xml
  setup/hr_employee_group_overview_readonly/odoo/addons/hr_employee_group_overview_readonly
  setup/hr_employee_group_overview_readonly/setup.py
Labels: enhancement, needs review, bot is merging ⏳
