Repository OCA/hr, pull requests merged in 2024-12, with the labels that each got.

#1348 [ADD] hr_holidays_team_manager
  hr_holidays_team_manager/README.rst
  hr_holidays_team_manager/__init__.py
  hr_holidays_team_manager/__manifest__.py
  hr_holidays_team_manager/data/hr_holidays_rules.xml
  hr_holidays_team_manager/data/hr_holidays_security.xml
  hr_holidays_team_manager/models/__init__.py
  hr_holidays_team_manager/models/hr_employee_base.py
  hr_holidays_team_manager/models/hr_leave_allocation.py
  hr_holidays_team_manager/readme/CONTRIBUTORS.rst
  hr_holidays_team_manager/readme/DESCRIPTION.rst
  hr_holidays_team_manager/readme/USAGE.rst
  hr_holidays_team_manager/static/description/index.html
  hr_holidays_team_manager/tests/__init__.py
  hr_holidays_team_manager/tests/test_hr_holidays_team_manager.py
  hr_holidays_team_manager/views/hr_leave_allocation_views.xml
  setup/hr_holidays_team_manager/odoo/addons/hr_holidays_team_manager
  setup/hr_holidays_team_manager/setup.py
Labels: enhancement, needs review, bot is merging ⏳, stale

#1324 [16.0][MIG] hr_contract_employee_calendar_planning
  hr_contract_employee_calendar_planning/README.rst
  hr_contract_employee_calendar_planning/__init__.py
  hr_contract_employee_calendar_planning/__manifest__.py
  hr_contract_employee_calendar_planning/hooks.py
  hr_contract_employee_calendar_planning/i18n/hr_contract_employee_calendar_planning.pot
  hr_contract_employee_calendar_planning/i18n/it.po
  hr_contract_employee_calendar_planning/models/__init__.py
  hr_contract_employee_calendar_planning/models/contract.py
  hr_contract_employee_calendar_planning/readme/CONTRIBUTORS.rst
  hr_contract_employee_calendar_planning/readme/DESCRIPTION.rst
  hr_contract_employee_calendar_planning/readme/USAGE.rst
  hr_contract_employee_calendar_planning/static/description/icon.png
  hr_contract_employee_calendar_planning/static/description/index.html
  hr_contract_employee_calendar_planning/tests/__init__.py
  hr_contract_employee_calendar_planning/tests/test_hr_contract_employee_calendar_planning.py
  hr_contract_employee_calendar_planning/views/contract.xml
  setup/hr_contract_employee_calendar_planning/odoo/addons/hr_contract_employee_calendar_planning
  setup/hr_contract_employee_calendar_planning/setup.py
Labels: approved, bot is merging ⏳

#1226 [16.0][MIG] hr_employee_service_contract: Migration to 16.0
  hr_employee_service_contract/README.rst
  hr_employee_service_contract/__init__.py
  hr_employee_service_contract/__manifest__.py
  hr_employee_service_contract/i18n/de.po
  hr_employee_service_contract/i18n/es.po
  hr_employee_service_contract/i18n/fr.po
  hr_employee_service_contract/i18n/hr_employee_service_contract.pot
  hr_employee_service_contract/models/__init__.py
  hr_employee_service_contract/models/hr_employee.py
  hr_employee_service_contract/readme/CONTRIBUTORS.rst
  hr_employee_service_contract/readme/DESCRIPTION.rst
  hr_employee_service_contract/static/description/icon.png
  hr_employee_service_contract/static/description/index.html
  hr_employee_service_contract/tests/__init__.py
  hr_employee_service_contract/tests/test_hr_employee_service.py
  setup/hr_employee_service_contract/odoo/addons/hr_employee_service_contract
  setup/hr_employee_service_contract/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1387 [17.0][ADD] hr_work_entry_profile: Migration to 17.0
  hr_work_entry_profile/README.rst
  hr_work_entry_profile/__init__.py
  hr_work_entry_profile/__manifest__.py
  hr_work_entry_profile/i18n/de.po
  hr_work_entry_profile/i18n/fr.po
  hr_work_entry_profile/images/screen.png
  hr_work_entry_profile/models/__init__.py
  hr_work_entry_profile/models/res_users.py
  hr_work_entry_profile/pyproject.toml
  hr_work_entry_profile/readme/CONTRIBUTORS.md
  hr_work_entry_profile/readme/CREDITS.md
  hr_work_entry_profile/readme/DESCRIPTION.md
  hr_work_entry_profile/static/description/icon.png
  hr_work_entry_profile/static/description/index.html
  hr_work_entry_profile/views/res_users.xml
Labels: approved, bot is merging ⏳

#1267 [14.0][FIX] hr_employee_birthay_mail: res_users configurable
  hr_employee_birthday_mail/README.rst
  hr_employee_birthday_mail/__manifest__.py
  hr_employee_birthday_mail/models/__init__.py
  hr_employee_birthday_mail/models/hr_employee.py
  hr_employee_birthday_mail/models/res_user.py
  hr_employee_birthday_mail/static/description/index.html
  hr_employee_birthday_mail/views/res_user_views.xml
Labels: approved, ready to merge, bot is merging ⏳, stale

#1392 [17.0][MIG] hr_employee_ppe: Migration to 17.0
  hr_employee_ppe/README.rst
  hr_employee_ppe/__init__.py
  hr_employee_ppe/__manifest__.py
  hr_employee_ppe/data/hr_employee_ppe_cron.xml
  hr_employee_ppe/i18n/de.po
  hr_employee_ppe/i18n/es.po
  hr_employee_ppe/i18n/hr_employee_ppe.pot
  hr_employee_ppe/i18n/it.po
  hr_employee_ppe/i18n/pt_BR.po
  hr_employee_ppe/models/__init__.py
  hr_employee_ppe/models/hr_personal_equipment.py
  hr_employee_ppe/models/hr_personal_equipment_request.py
  hr_employee_ppe/models/product_template.py
  hr_employee_ppe/pyproject.toml
  hr_employee_ppe/readme/CONTRIBUTORS.md
  hr_employee_ppe/readme/CREDITS.md
  hr_employee_ppe/readme/DESCRIPTION.md
  hr_employee_ppe/readme/INSTALL.md
  hr_employee_ppe/readme/USAGE.md
  hr_employee_ppe/reports/hr_employee_ppe_report.xml
  hr_employee_ppe/reports/hr_employee_ppe_report_template.xml
  hr_employee_ppe/static/description/banner.png
  hr_employee_ppe/static/description/icon.png
  hr_employee_ppe/static/description/index.html
  hr_employee_ppe/tests/__init__.py
  hr_employee_ppe/tests/test_hr_employee_ppe.py
  hr_employee_ppe/views/hr_personal_equipment.xml
  hr_employee_ppe/views/hr_personal_equipment_request.xml
  hr_employee_ppe/views/product_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#1402 [16.0][MIG] hr_employee_ppe: Migration to 16.0
  hr_employee_ppe/README.rst
  hr_employee_ppe/__init__.py
  hr_employee_ppe/__manifest__.py
  hr_employee_ppe/data/hr_employee_ppe_cron.xml
  hr_employee_ppe/i18n/de.po
  hr_employee_ppe/i18n/es.po
  hr_employee_ppe/i18n/hr_employee_ppe.pot
  hr_employee_ppe/i18n/it.po
  hr_employee_ppe/i18n/pt_BR.po
  hr_employee_ppe/models/__init__.py
  hr_employee_ppe/models/hr_personal_equipment.py
  hr_employee_ppe/models/hr_personal_equipment_request.py
  hr_employee_ppe/models/product_template.py
  hr_employee_ppe/readme/CONTRIBUTORS.rst
  hr_employee_ppe/readme/CREDITS.rst
  hr_employee_ppe/readme/DESCRIPTION.rst
  hr_employee_ppe/readme/INSTALL.rst
  hr_employee_ppe/readme/USAGE.rst
  hr_employee_ppe/reports/hr_employee_ppe_report.xml
  hr_employee_ppe/reports/hr_employee_ppe_report_template.xml
  hr_employee_ppe/static/description/banner.png
  hr_employee_ppe/static/description/icon.png
  hr_employee_ppe/static/description/index.html
  hr_employee_ppe/tests/__init__.py
  hr_employee_ppe/tests/test_hr_employee_ppe.py
  hr_employee_ppe/views/hr_personal_equipment.xml
  hr_employee_ppe/views/hr_personal_equipment_request.xml
  hr_employee_ppe/views/product_template.xml
  setup/hr_employee_ppe/odoo/addons/hr_employee_ppe
  setup/hr_employee_ppe/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1358 [16.0][FWP][FIX] hr_employee_birthay_mail: res_users configurable
  hr_employee_birthday_mail/README.rst
  hr_employee_birthday_mail/__manifest__.py
  hr_employee_birthday_mail/models/__init__.py
  hr_employee_birthday_mail/models/hr_employee.py
  hr_employee_birthday_mail/models/res_user.py
  hr_employee_birthday_mail/views/res_user_views.xml
Labels: approved, ready to merge, bot is merging ⏳, stale

#1409 [17.0][FIX] hr_employee_calendar_planning: Change test employee name
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
Labels: approved, bot is merging ⏳

#1423 [17.0][IMP] hr_holidays_settings: Remove DeprecationWarning: XML declarations in HTML module descriptions
  hr_holidays_settings/static/description/index.html
Labels: bot is merging ⏳

#1420 [FIX] hr_employee_firstname: apply same order (lastname, then firstname)
  hr_employee_firstname/views/hr_view.xml
Labels: approved, bot is merging ⏳

#1422 [17.0][MIG] hr_employee_ssn: Migration to 17.0
  hr_employee_ssn/README.rst
  hr_employee_ssn/__init__.py
  hr_employee_ssn/__manifest__.py
  hr_employee_ssn/i18n/de.po
  hr_employee_ssn/i18n/es_AR.po
  hr_employee_ssn/i18n/fr.po
  hr_employee_ssn/i18n/hr_employee_ssn.pot
  hr_employee_ssn/i18n/it.po
  hr_employee_ssn/pyproject.toml
  hr_employee_ssn/readme/CONTRIBUTORS.md
  hr_employee_ssn/readme/DESCRIPTION.md
  hr_employee_ssn/static/description/icon.png
  hr_employee_ssn/static/description/index.html
  hr_employee_ssn/views/hr_employee_views.xml
Labels: approved, bot is merging ⏳

#1424 [17.0][MIG] hr_professional_category: Migration to 17.0
  hr_professional_category/README.rst
  hr_professional_category/__init__.py
  hr_professional_category/__manifest__.py
  hr_professional_category/demo/hr_professional_category_demo.xml
  hr_professional_category/i18n/es.po
  hr_professional_category/i18n/hr_professional_category.pot
  hr_professional_category/i18n/it.po
  hr_professional_category/models/__init__.py
  hr_professional_category/models/hr_contract.py
  hr_professional_category/models/hr_professional_category.py
  hr_professional_category/pyproject.toml
  hr_professional_category/readme/CONFIGURE.md
  hr_professional_category/readme/CONTRIBUTORS.md
  hr_professional_category/readme/DESCRIPTION.md
  hr_professional_category/readme/USAGE.md
  hr_professional_category/security/ir.model.access.csv
  hr_professional_category/security/security.xml
  hr_professional_category/static/description/icon.png
  hr_professional_category/static/description/index.html
  hr_professional_category/tests/__init__.py
  hr_professional_category/tests/test_hr_professional_category.py
  hr_professional_category/views/hr_contract_views.xml
  hr_professional_category/views/hr_professional_category_views.xml
Labels: approved, bot is merging ⏳
