Repository OCA/hr, pull requests merged in 2024-10, with the labels that each got.

#1343 [ADD] hr_employee_document_from_applicant
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/models/resource_calendar.py
  hr_employee_document_from_applicant/README.rst
  hr_employee_document_from_applicant/__init__.py
  hr_employee_document_from_applicant/__manifest__.py
  hr_employee_document_from_applicant/i18n/es_MX.po
  hr_employee_document_from_applicant/i18n/hr_employee_document_from_applicant.pot
  hr_employee_document_from_applicant/models/__init__.py
  hr_employee_document_from_applicant/models/hr_employee.py
  hr_employee_document_from_applicant/readme/CONTRIBUTORS.rst
  hr_employee_document_from_applicant/readme/DESCRIPTION.rst
  hr_employee_document_from_applicant/readme/USAGE.rst
  hr_employee_document_from_applicant/static/description/index.html
  hr_employee_lastnames/models/hr_employee.py
  hr_employee_lastnames/tests/test_hr_employee_lastnames.py
  hr_personal_equipment_request/models/hr_personal_equipment.py
  setup/hr_employee_document_from_applicant/odoo/addons/hr_employee_document_from_applicant
  setup/hr_employee_document_from_applicant/setup.py
Labels: enhancement, needs review, bot is merging ⏳, stale, needs tests

#1396 [FIX] hr_employee_firstname: fix DeprecationWarning
  hr_employee_firstname/README.rst
  hr_employee_firstname/static/description/index.html
Labels: bot is merging ⏳

#1397 [18.0][MIG] hr_employee_firstname: Migration to 18.0
  hr_employee_firstname/README.rst
  hr_employee_firstname/__init__.py
  hr_employee_firstname/__manifest__.py
  hr_employee_firstname/hooks.py
  hr_employee_firstname/i18n/ar.po
  hr_employee_firstname/i18n/ca.po
  hr_employee_firstname/i18n/cs_CZ.po
  hr_employee_firstname/i18n/de.po
  hr_employee_firstname/i18n/es.po
  hr_employee_firstname/i18n/fa.po
  hr_employee_firstname/i18n/fi.po
  hr_employee_firstname/i18n/fr.po
  hr_employee_firstname/i18n/hr.po
  hr_employee_firstname/i18n/hr_HR.po
  hr_employee_firstname/i18n/hr_employee_firstname.pot
  hr_employee_firstname/i18n/it.po
  hr_employee_firstname/i18n/lt.po
  hr_employee_firstname/i18n/nl_NL.po
  hr_employee_firstname/i18n/pt_BR.po
  hr_employee_firstname/i18n/ro.po
  hr_employee_firstname/i18n/sl.po
  hr_employee_firstname/models/__init__.py
  hr_employee_firstname/models/base_config_settings.py
  hr_employee_firstname/models/hr_employee.py
  hr_employee_firstname/models/hr_employee_base.py
  hr_employee_firstname/pyproject.toml
  hr_employee_firstname/readme/CONTRIBUTORS.md
  hr_employee_firstname/readme/DESCRIPTION.md
  hr_employee_firstname/readme/USAGE.md
  hr_employee_firstname/static/description/icon.png
  hr_employee_firstname/static/description/index.html
  hr_employee_firstname/tests/__init__.py
  hr_employee_firstname/tests/test_hr_employee_firstname.py
  hr_employee_firstname/views/base_config_view.xml
  hr_employee_firstname/views/hr_view.xml
Labels: approved, bot is merging ⏳
