Repository OCA/hr, pull requests merged in 2024-08, with the labels that each got.

#1381 [17.0][MIG] hr_employee_partner_external: Migration to 17.0
  hr_employee_partner_external/README.rst
  hr_employee_partner_external/__init__.py
  hr_employee_partner_external/__manifest__.py
  hr_employee_partner_external/i18n/es.po
  hr_employee_partner_external/i18n/hr_employee_partner_external.pot
  hr_employee_partner_external/i18n/it.po
  hr_employee_partner_external/models/__init__.py
  hr_employee_partner_external/models/hr_employee.py
  hr_employee_partner_external/pyproject.toml
  hr_employee_partner_external/readme/CONTRIBUTORS.md
  hr_employee_partner_external/readme/DESCRIPTION.md
  hr_employee_partner_external/readme/HISTORY.md
  hr_employee_partner_external/readme/USAGE.md
  hr_employee_partner_external/static/description/icon.png
  hr_employee_partner_external/static/description/index.html
  hr_employee_partner_external/views/hr_employee.xml
Labels: approved, ready to merge, bot is merging ⏳

#1367 [17.0][MIG] hr_course: Migration to 17.0
  hr_course/README.rst
  hr_course/__init__.py
  hr_course/__manifest__.py
  hr_course/demo/hr_course.xml
  hr_course/i18n/de.po
  hr_course/i18n/es.po
  hr_course/i18n/hr_course.pot
  hr_course/i18n/it.po
  hr_course/models/__init__.py
  hr_course/models/hr_course.py
  hr_course/models/hr_course_schedule.py
  hr_course/models/hr_employee.py
  hr_course/pyproject.toml
  hr_course/readme/CONTRIBUTORS.md
  hr_course/readme/DESCRIPTION.md
  hr_course/readme/USAGE.md
  hr_course/security/course_security.xml
  hr_course/security/ir.model.access.csv
  hr_course/static/description/icon.png
  hr_course/static/description/index.html
  hr_course/tests/__init__.py
  hr_course/tests/test_hr_course.py
  hr_course/views/hr_course_category_views.xml
  hr_course/views/hr_course_schedule_views.xml
  hr_course/views/hr_course_views.xml
  hr_course/views/hr_employee_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1350 [17.0][MIG] hr_job_category
  hr_job_category/README.rst
  hr_job_category/__init__.py
  hr_job_category/__manifest__.py
  hr_job_category/i18n/de.po
  hr_job_category/i18n/es.po
  hr_job_category/i18n/fi.po
  hr_job_category/i18n/fr.po
  hr_job_category/i18n/hr_job_category.pot
  hr_job_category/i18n/it.po
  hr_job_category/i18n/pt_BR.po
  hr_job_category/i18n/ro.po
  hr_job_category/i18n/sl.po
  hr_job_category/models/__init__.py
  hr_job_category/models/hr.py
  hr_job_category/pyproject.toml
  hr_job_category/readme/CONTRIBUTORS.md
  hr_job_category/readme/DESCRIPTION.md
  hr_job_category/readme/USAGE.md
  hr_job_category/static/description/icon.png
  hr_job_category/static/description/index.html
  hr_job_category/tests/__init__.py
  hr_job_category/tests/test_hr_job_categories.py
  hr_job_category/views/hr_view.xml
Labels: bot is merging ⏳

#1355 [17.0][MIG] hr_employee_calendar_planning
  hr_employee_calendar_planning/README.rst
  hr_employee_calendar_planning/__init__.py
  hr_employee_calendar_planning/__manifest__.py
  hr_employee_calendar_planning/hooks.py
  hr_employee_calendar_planning/i18n/ca.po
  hr_employee_calendar_planning/i18n/ca_ES.po
  hr_employee_calendar_planning/i18n/de.po
  hr_employee_calendar_planning/i18n/es.po
  hr_employee_calendar_planning/i18n/es_AR.po
  hr_employee_calendar_planning/i18n/fr.po
  hr_employee_calendar_planning/i18n/hr_employee_calendar_planning.pot
  hr_employee_calendar_planning/i18n/it.po
  hr_employee_calendar_planning/models/__init__.py
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/models/resource_calendar.py
  hr_employee_calendar_planning/pyproject.toml
  hr_employee_calendar_planning/readme/CONFIGURE.md
  hr_employee_calendar_planning/readme/CONTRIBUTORS.md
  hr_employee_calendar_planning/readme/DESCRIPTION.md
  hr_employee_calendar_planning/readme/INSTALL.md
  hr_employee_calendar_planning/readme/ROADMAP.md
  hr_employee_calendar_planning/security/ir.model.access.csv
  hr_employee_calendar_planning/static/description/icon.png
  hr_employee_calendar_planning/static/description/index.html
  hr_employee_calendar_planning/tests/__init__.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
  hr_employee_calendar_planning/views/hr_employee_views.xml
  hr_employee_calendar_planning/views/resource_calendar_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1388 [17.0][MIG] hr_study: Migration to version 17.0
  hr_study/README.rst
  hr_study/__init__.py
  hr_study/__manifest__.py
  hr_study/demo/hr_study.xml
  hr_study/i18n/es.po
  hr_study/i18n/hr_study.pot
  hr_study/i18n/it.po
  hr_study/models/__init__.py
  hr_study/models/hr_employee.py
  hr_study/models/hr_study.py
  hr_study/pyproject.toml
  hr_study/readme/CONFIGURE.md
  hr_study/readme/CONTRIBUTORS.md
  hr_study/readme/DESCRIPTION.md
  hr_study/readme/ROADMAP.md
  hr_study/readme/USAGE.md
  hr_study/security/ir.model.access.csv
  hr_study/security/security.xml
  hr_study/static/description/icon.png
  hr_study/static/description/index.html
  hr_study/tests/__init__.py
  hr_study/tests/test_hr_study.py
  hr_study/views/hr_employee_view.xml
  hr_study/views/hr_study_views.xml
Labels: approved, bot is merging ⏳
