Repository OCA/hr, pull requests merged in 2024-03, with the labels that each got.

#1334 [16.0][ADD] hr_recruitment_torecruit
  hr_recruitment_torecruit/README.rst
  hr_recruitment_torecruit/__init__.py
  hr_recruitment_torecruit/__manifest__.py
  hr_recruitment_torecruit/models/__init__.py
  hr_recruitment_torecruit/models/hr_job.py
  hr_recruitment_torecruit/readme/CONTRIBUTORS.rst
  hr_recruitment_torecruit/readme/DESCRIPTION.rst
  hr_recruitment_torecruit/readme/USAGE.rst
  hr_recruitment_torecruit/static/description/icon.png
  hr_recruitment_torecruit/static/description/index.html
  hr_recruitment_torecruit/tests/__init__.py
  hr_recruitment_torecruit/tests/test_hr_recruitment_torecruit.py
  hr_recruitment_torecruit/views/hr_job.xml
  setup/hr_recruitment_torecruit/odoo/addons/hr_recruitment_torecruit
  setup/hr_recruitment_torecruit/setup.py
Labels: enhancement, needs review, bot is merging ⏳

#1115 [14.0][ADD] hr_maintenance_workspace
  hr_maintenance_workspace/README.rst
  hr_maintenance_workspace/__init__.py
  hr_maintenance_workspace/__manifest__.py
  hr_maintenance_workspace/models/__init__.py
  hr_maintenance_workspace/models/equipment.py
  hr_maintenance_workspace/models/hr_employee.py
  hr_maintenance_workspace/models/workspace.py
  hr_maintenance_workspace/readme/CONTRIBUTORS.rst
  hr_maintenance_workspace/readme/DESCRIPTION.rst
  hr_maintenance_workspace/security/ir.model.access.csv
  hr_maintenance_workspace/static/description/icon.png
  hr_maintenance_workspace/static/description/index.html
  hr_maintenance_workspace/tests/__init__.py
  hr_maintenance_workspace/tests/test_hr_maitenance_workspace.py
  hr_maintenance_workspace/views/hr_employee_views.xml
  hr_maintenance_workspace/views/hr_maintenance_workspace_menu_views.xml
  hr_maintenance_workspace/views/maintenance_views.xml
  hr_maintenance_workspace/views/maintenance_workspace_views.xml
  setup/hr_maintenance_workspace/odoo/addons/hr_maintenance_workspace
  setup/hr_maintenance_workspace/setup.py
Labels: needs fixing, bot is merging ⏳, stale

#1335 [IMP] hr_recruitment_torecruit: add filter
  hr_recruitment_torecruit/models/__init__.py
  hr_recruitment_torecruit/models/hr_contract.py
  hr_recruitment_torecruit/models/hr_job.py
  hr_recruitment_torecruit/views/hr_job.xml
Labels: enhancement, needs review, bot is merging ⏳

#1333 [16.0][FIX]only create and unlink necessary resource_calendar_leaves
  hr_employee_calendar_planning/models/hr_employee.py
Labels: approved, bot is merging ⏳

#1338 [IMP] hr_job_category: Add tests and fix tag inheritance
  hr_job_category/models/hr.py
  hr_job_category/tests/test_hr_job_categories.py
Labels: approved, bot is merging ⏳
