Repository OCA/hr, pull requests merged in 2024-09, with the labels that each got.

#1382 [17.0][MIG] hr_employee_relative: Migration to 17.0
  hr_employee_relative/README.rst
  hr_employee_relative/__init__.py
  hr_employee_relative/__manifest__.py
  hr_employee_relative/data/data_relative_relation.xml
  hr_employee_relative/i18n/de.po
  hr_employee_relative/i18n/es.po
  hr_employee_relative/i18n/fr.po
  hr_employee_relative/i18n/hr.po
  hr_employee_relative/i18n/hr_employee_relative.pot
  hr_employee_relative/i18n/it.po
  hr_employee_relative/i18n/pt_BR.po
  hr_employee_relative/models/__init__.py
  hr_employee_relative/models/hr_employee.py
  hr_employee_relative/models/hr_employee_relative.py
  hr_employee_relative/models/hr_employee_relative_relation.py
  hr_employee_relative/pyproject.toml
  hr_employee_relative/readme/CONTRIBUTORS.md
  hr_employee_relative/readme/DESCRIPTION.md
  hr_employee_relative/security/ir.model.access.csv
  hr_employee_relative/static/description/icon.png
  hr_employee_relative/static/description/index.html
  hr_employee_relative/tests/__init__.py
  hr_employee_relative/tests/test_hr_employee_relatives.py
  hr_employee_relative/views/hr_employee.xml
  hr_employee_relative/views/hr_employee_relative.xml
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#1390 [17.0][MIG] hr_announcement: Migration to version 17.0
  hr_announcement/README.rst
  hr_announcement/__init__.py
  hr_announcement/__manifest__.py
  hr_announcement/i18n/es.po
  hr_announcement/i18n/hr_announcement.pot
  hr_announcement/i18n/it.po
  hr_announcement/models/__init__.py
  hr_announcement/models/announcement.py
  hr_announcement/models/res_users.py
  hr_announcement/pyproject.toml
  hr_announcement/readme/CONTRIBUTORS.md
  hr_announcement/readme/DESCRIPTION.md
  hr_announcement/readme/USAGE.md
  hr_announcement/static/description/icon.png
  hr_announcement/static/description/index.html
  hr_announcement/views/announcement_views.xml
Labels: approved, bot is merging ⏳

#1373 [16.0][MIG] hr_employee_id: Migration to 16.0
  hr_employee_id/README.rst
  hr_employee_id/__init__.py
  hr_employee_id/__manifest__.py
  hr_employee_id/data/hr_employee_sequence.xml
  hr_employee_id/i18n/ar.po
  hr_employee_id/i18n/cs_CZ.po
  hr_employee_id/i18n/de.po
  hr_employee_id/i18n/es.po
  hr_employee_id/i18n/fi.po
  hr_employee_id/i18n/fr.po
  hr_employee_id/i18n/hr.po
  hr_employee_id/i18n/hr_HR.po
  hr_employee_id/i18n/hr_employee_id.pot
  hr_employee_id/i18n/it.po
  hr_employee_id/i18n/lt.po
  hr_employee_id/i18n/nl_NL.po
  hr_employee_id/i18n/pt_BR.po
  hr_employee_id/i18n/ro.po
  hr_employee_id/i18n/sl.po
  hr_employee_id/models/__init__.py
  hr_employee_id/models/hr_employee.py
  hr_employee_id/models/res_company.py
  hr_employee_id/models/res_config_settings.py
  hr_employee_id/readme/CONFIGURE.rst
  hr_employee_id/readme/CONTRIBUTORS.rst
  hr_employee_id/readme/DESCRIPTION.rst
  hr_employee_id/readme/INSTALL.rst
  hr_employee_id/readme/ROADMAP.rst
  hr_employee_id/readme/USAGE.rst
  hr_employee_id/static/description/icon.png
  hr_employee_id/static/description/index.html
  hr_employee_id/tests/__init__.py
  hr_employee_id/tests/test_employee_id.py
  hr_employee_id/views/hr_employee_views.xml
  hr_employee_id/views/res_config_settings_views.xml
  setup/hr_employee_id/odoo/addons/hr_employee_id
  setup/hr_employee_id/setup.py
Labels: bot is merging ⏳

#1339 [ADD][15.0] passport_expiration
  passport_expiration/README.rst
  passport_expiration/__init__.py
  passport_expiration/__manifest__.py
  passport_expiration/i18n/fr.po
  passport_expiration/i18n/passport_expiration.pot
  passport_expiration/models/__init__.py
  passport_expiration/models/hr.py
  passport_expiration/readme/CONTRIBUTORS.rst
  passport_expiration/readme/DESCRIPTION.rst
  passport_expiration/readme/USAGE.rst
  passport_expiration/static/description/icon.png
  passport_expiration/static/description/index.html
  passport_expiration/views/hr_view.xml
  setup/passport_expiration/odoo/addons/passport_expiration
  setup/passport_expiration/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1351 [FIX] hr_employee_ppe: fix error when assigning multiple PPE to an employee.
  hr_employee_ppe/models/hr_employee_ppe.py
  hr_employee_ppe/tests/test_hr_employee_ppe.py
Labels: approved, ready to merge, bot is merging ⏳, stale
