Repository OCA/hr, pull requests merged in 2025-07, with the labels that each got.

#1444 [18.0][MIG] hr_employee_birthday_mail: Migration to 18.0
  hr_employee_birthday_mail/README.rst
  hr_employee_birthday_mail/__init__.py
  hr_employee_birthday_mail/__manifest__.py
  hr_employee_birthday_mail/data/data.xml
  hr_employee_birthday_mail/data/ir_cron.xml
  hr_employee_birthday_mail/i18n/es.po
  hr_employee_birthday_mail/i18n/fr.po
  hr_employee_birthday_mail/i18n/fr_FR.po
  hr_employee_birthday_mail/i18n/hr_employee_birthday_mail.pot
  hr_employee_birthday_mail/i18n/it.po
  hr_employee_birthday_mail/models/__init__.py
  hr_employee_birthday_mail/models/hr_employee.py
  hr_employee_birthday_mail/models/res_user.py
  hr_employee_birthday_mail/pyproject.toml
  hr_employee_birthday_mail/readme/CONFIGURE.md
  hr_employee_birthday_mail/readme/CONTRIBUTORS.md
  hr_employee_birthday_mail/readme/DESCRIPTION.md
  hr_employee_birthday_mail/readme/USAGE.md
  hr_employee_birthday_mail/static/description/icon.png
  hr_employee_birthday_mail/static/description/index.html
  hr_employee_birthday_mail/views/hr_employee_views.xml
  hr_employee_birthday_mail/views/res_user_views.xml
Labels: approved, bot is merging ⏳

#1463 [18.0] [MIG] hr _employee _service: Migration to 18.0
  hr_employee_service/README.rst
  hr_employee_service/__init__.py
  hr_employee_service/__manifest__.py
  hr_employee_service/i18n/ca.po
  hr_employee_service/i18n/de.po
  hr_employee_service/i18n/es.po
  hr_employee_service/i18n/fr.po
  hr_employee_service/i18n/hr_employee_service.pot
  hr_employee_service/i18n/it.po
  hr_employee_service/i18n/pt_BR.po
  hr_employee_service/models/__init__.py
  hr_employee_service/models/hr_employee.py
  hr_employee_service/pyproject.toml
  hr_employee_service/readme/CONTRIBUTORS.md
  hr_employee_service/readme/DESCRIPTION.md
  hr_employee_service/static/description/icon.png
  hr_employee_service/static/description/index.html
  hr_employee_service/tests/__init__.py
  hr_employee_service/tests/test_hr_employee_service.py
  hr_employee_service/views/hr_employee.xml
Labels: approved, bot is merging ⏳

#1464 [18.0] [MIG] hr_employee_service_contract: Migration to 18.0
  hr_employee_service_contract/README.rst
  hr_employee_service_contract/__init__.py
  hr_employee_service_contract/__manifest__.py
  hr_employee_service_contract/i18n/de.po
  hr_employee_service_contract/i18n/es.po
  hr_employee_service_contract/i18n/fr.po
  hr_employee_service_contract/i18n/hr_employee_service_contract.pot
  hr_employee_service_contract/i18n/it.po
  hr_employee_service_contract/models/__init__.py
  hr_employee_service_contract/models/hr_employee.py
  hr_employee_service_contract/pyproject.toml
  hr_employee_service_contract/readme/CONTRIBUTORS.md
  hr_employee_service_contract/readme/DESCRIPTION.md
  hr_employee_service_contract/static/description/icon.png
  hr_employee_service_contract/static/description/index.html
  hr_employee_service_contract/tests/__init__.py
  hr_employee_service_contract/tests/test_hr_employee_service.py
Labels: approved, ready to merge, bot is merging ⏳

#1453 [16.0][IMP] multicreate warning
  hr_contract_employee_calendar_planning/models/contract.py
  hr_contract_reference/models/hr_contract.py
  hr_employee_id/models/hr_employee.py
  hr_job_category/models/hr.py
Labels: approved, bot is merging ⏳, stale

#1491 [16.0][FIX]hr_employee_calendar_planning: Fix incorrect behaviour _check_company_id
  hr_employee_calendar_planning/models/resource_calendar.py
Labels: approved, bot is merging ⏳

#1492 [17.0][FIX]hr_employee_calendar_planning: Fix _check_company_id
  hr_employee_calendar_planning/models/resource_calendar.py
Labels: bot is merging ⏳

#1494 [18.0][FIX]hr_employee_calendar_planning: Fix _check_company_id
  hr_employee_calendar_planning/models/resource_calendar.py
Labels: bot is merging ⏳

#1490 [16.0][IMP] hr_employee_medical_examination: Add Activities filter + kanban view
  hr_employee_medical_examination/README.rst
  hr_employee_medical_examination/__manifest__.py
  hr_employee_medical_examination/models/hr_employee_medical_examination.py
  hr_employee_medical_examination/static/description/index.html
  hr_employee_medical_examination/views/hr_employee_medical_examination_views.xml
Labels: approved, bot is merging ⏳
