Repository OCA/hr, pull requests merged in 2025-02, with the labels that each got.

#1439 [16.0][FIX] hr_employee_calendar_planning: Avoid error in post_init_hook with leaves that do not already exist
  hr_employee_calendar_planning/hooks.py
Labels: approved, bot is merging ⏳

#1440 [17.0][FIX] hr_employee_calendar_planning: Avoid error in post_init_hook with leaves that do not already exist
  hr_employee_calendar_planning/hooks.py
Labels: bot is merging ⏳

#1441 [18.0][MIG] hr_employee_calendar_planning: Migration to 18.0
  hr_employee_calendar_planning/README.rst
  hr_employee_calendar_planning/__init__.py
  hr_employee_calendar_planning/__manifest__.py
  hr_employee_calendar_planning/hooks.py
  hr_employee_calendar_planning/i18n/ca.po
  hr_employee_calendar_planning/i18n/ca_ES.po
  hr_employee_calendar_planning/i18n/de.po
  hr_employee_calendar_planning/i18n/es.po
  hr_employee_calendar_planning/i18n/es_AR.po
  hr_employee_calendar_planning/i18n/fr.po
  hr_employee_calendar_planning/i18n/hr_employee_calendar_planning.pot
  hr_employee_calendar_planning/i18n/it.po
  hr_employee_calendar_planning/models/__init__.py
  hr_employee_calendar_planning/models/hr_employee.py
  hr_employee_calendar_planning/models/resource_calendar.py
  hr_employee_calendar_planning/pyproject.toml
  hr_employee_calendar_planning/readme/CONFIGURE.md
  hr_employee_calendar_planning/readme/CONTRIBUTORS.md
  hr_employee_calendar_planning/readme/DESCRIPTION.md
  hr_employee_calendar_planning/readme/INSTALL.md
  hr_employee_calendar_planning/readme/ROADMAP.md
  hr_employee_calendar_planning/security/ir.model.access.csv
  hr_employee_calendar_planning/static/description/icon.png
  hr_employee_calendar_planning/static/description/index.html
  hr_employee_calendar_planning/tests/__init__.py
  hr_employee_calendar_planning/tests/test_hr_employee_calendar_planning.py
  hr_employee_calendar_planning/views/hr_employee_views.xml
  hr_employee_calendar_planning/views/resource_calendar_views.xml
Labels: approved, bot is merging ⏳

#1380 [16.0] [MIG] hr_personal_equipment_variant_configurator: Migration to 16.0
  hr_personal_equipment_variant_configurator/README.rst
  hr_personal_equipment_variant_configurator/__init__.py
  hr_personal_equipment_variant_configurator/__manifest__.py
  hr_personal_equipment_variant_configurator/i18n/es.po
  hr_personal_equipment_variant_configurator/i18n/es_PA.po
  hr_personal_equipment_variant_configurator/i18n/hr_personal_equipment_variant_configurator.pot
  hr_personal_equipment_variant_configurator/i18n/it.po
  hr_personal_equipment_variant_configurator/i18n/pt_BR.po
  hr_personal_equipment_variant_configurator/models/__init__.py
  hr_personal_equipment_variant_configurator/models/hr_personal_equipment.py
  hr_personal_equipment_variant_configurator/readme/CONFIGURE.rst
  hr_personal_equipment_variant_configurator/readme/CONTRIBUTORS.rst
  hr_personal_equipment_variant_configurator/readme/DESCRIPTION.rst
  hr_personal_equipment_variant_configurator/readme/INSTALL.rst
  hr_personal_equipment_variant_configurator/readme/USAGE.rst
  hr_personal_equipment_variant_configurator/static/description/icon.png
  hr_personal_equipment_variant_configurator/static/description/index.html
  hr_personal_equipment_variant_configurator/views/hr_personal_equipment_request.xml
  setup/hr_personal_equipment_variant_configurator/odoo/addons/hr_personal_equipment_variant_configurator
  setup/hr_personal_equipment_variant_configurator/setup.py
Labels: approved, bot is merging ⏳, stale

#1379 [16.0] [MIG] hr_personal_equipment_request_tier_validation: Migration to 16.0
  hr_personal_equipment_request_tier_validation/README.rst
  hr_personal_equipment_request_tier_validation/__init__.py
  hr_personal_equipment_request_tier_validation/__manifest__.py
  hr_personal_equipment_request_tier_validation/data/tier_definition.xml
  hr_personal_equipment_request_tier_validation/i18n/es.po
  hr_personal_equipment_request_tier_validation/i18n/es_PA.po
  hr_personal_equipment_request_tier_validation/i18n/hr_personal_equipment_request_tier_validation.pot
  hr_personal_equipment_request_tier_validation/i18n/it.po
  hr_personal_equipment_request_tier_validation/i18n/pt_BR.po
  hr_personal_equipment_request_tier_validation/models/__init__.py
  hr_personal_equipment_request_tier_validation/models/hr_personal_equipment_request.py
  hr_personal_equipment_request_tier_validation/models/tier_definition.py
  hr_personal_equipment_request_tier_validation/readme/CONTRIBUTORS.rst
  hr_personal_equipment_request_tier_validation/readme/DESCRIPTION.rst
  hr_personal_equipment_request_tier_validation/readme/USAGE.rst
  hr_personal_equipment_request_tier_validation/static/description/icon.png
  hr_personal_equipment_request_tier_validation/static/description/index.html
  hr_personal_equipment_request_tier_validation/tests/__init__.py
  hr_personal_equipment_request_tier_validation/tests/test_tier_definition.py
  setup/hr_personal_equipment_request_tier_validation/odoo/addons/hr_personal_equipment_request_tier_validation
  setup/hr_personal_equipment_request_tier_validation/setup.py
Labels: approved, bot is merging ⏳, stale

#1443 [IMP] hr_employee_service: Remove mock dependancy
  hr_employee_service/tests/test_hr_employee_service.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#1442 [16.0] [MIG] hr_job_category: Migration to 16.0
  hr_job_category/README.rst
  hr_job_category/__init__.py
  hr_job_category/__manifest__.py
  hr_job_category/i18n/de.po
  hr_job_category/i18n/es.po
  hr_job_category/i18n/fi.po
  hr_job_category/i18n/fr.po
  hr_job_category/i18n/hr_job_category.pot
  hr_job_category/i18n/it.po
  hr_job_category/i18n/pt_BR.po
  hr_job_category/i18n/ro.po
  hr_job_category/i18n/sl.po
  hr_job_category/models/__init__.py
  hr_job_category/models/hr.py
  hr_job_category/readme/CONTRIBUTORS.rst
  hr_job_category/readme/DESCRIPTION.rst
  hr_job_category/readme/INSTALL.rst
  hr_job_category/readme/USAGE.rst
  hr_job_category/static/description/icon.png
  hr_job_category/static/description/index.html
  hr_job_category/tests/__init__.py
  hr_job_category/tests/test_hr_job_categories.py
  hr_job_category/views/hr_view.xml
  setup/hr_job_category/odoo/addons/hr_job_category
  setup/hr_job_category/setup.py
Labels: approved, bot is merging ⏳

#1411 [18.0][MIG] hr_department_code: Migration to 18.0
  hr_department_code/README.rst
  hr_department_code/__init__.py
  hr_department_code/__manifest__.py
  hr_department_code/i18n/de.po
  hr_department_code/i18n/hr.po
  hr_department_code/i18n/hr_department_code.pot
  hr_department_code/i18n/it.po
  hr_department_code/models/__init__.py
  hr_department_code/models/hr_department.py
  hr_department_code/pyproject.toml
  hr_department_code/readme/CONTRIBUTORS.md
  hr_department_code/readme/DESCRIPTION.md
  hr_department_code/static/description/icon.png
  hr_department_code/static/description/index.html
  hr_department_code/tests/__init__.py
  hr_department_code/tests/test_hr_department_code.py
  hr_department_code/views/hr_department_views.xml
Labels: approved, bot is merging ⏳
