Repository OCA/hr, pull requests merged in 2025-04, with the labels that each got.

#1272 [16.0][MIG] hr_org_chart_overview
  hr_org_chart_overview/README.rst
  hr_org_chart_overview/__init__.py
  hr_org_chart_overview/__manifest__.py
  hr_org_chart_overview/i18n/hr_org_chart_overview.pot
  hr_org_chart_overview/i18n/it.po
  hr_org_chart_overview/i18n/pt_BR.po
  hr_org_chart_overview/i18n/sv.po
  hr_org_chart_overview/models/__init__.py
  hr_org_chart_overview/models/hr_employee.py
  hr_org_chart_overview/readme/CONTRIBUTORS.rst
  hr_org_chart_overview/readme/DESCRIPTION.rst
  hr_org_chart_overview/readme/USAGE.rst
  hr_org_chart_overview/static/description/icon.png
  hr_org_chart_overview/static/description/index.html
  hr_org_chart_overview/static/src/js/hr_org_chart_overview.js
  hr_org_chart_overview/static/src/lib/orgchart/html2canvas.min.js
  hr_org_chart_overview/static/src/lib/orgchart/jquery.orgchart.css
  hr_org_chart_overview/static/src/lib/orgchart/jquery.orgchart.js
  hr_org_chart_overview/static/src/lib/orgchart/jspdf.min.js
  hr_org_chart_overview/static/src/scss/hr_org_chart_style.scss
  hr_org_chart_overview/static/src/xml/hr_org_chart_overview.xml
  hr_org_chart_overview/views/hr_views.xml
  setup/hr_org_chart_overview/odoo/addons/hr_org_chart_overview
  setup/hr_org_chart_overview/setup.py
Labels: bot is merging ⏳, stale

#1456 [16.0][IMP] hr_course: Add chatter to courses and schedules
  hr_course/models/hr_course.py
  hr_course/models/hr_course_schedule.py
  hr_course/views/hr_course_schedule_views.xml
  hr_course/views/hr_course_views.xml
Labels: approved, bot is merging ⏳

#1460 [17.0] [IMP] hr_course: Add chatter to courses and schedules
  hr_course/models/hr_course.py
  hr_course/models/hr_course_schedule.py
  hr_course/views/hr_course_schedule_views.xml
  hr_course/views/hr_course_views.xml
Labels: bot is merging ⏳

#1458 [18.0][FIX] hr_employee_relative: add compute value for fields impacted by the compute method
  hr_employee_relative/models/hr_employee_relative.py
Labels: approved, ready to merge, bot is merging ⏳

#1461 [FIX] hr_personal_equipment_request_tier_validation: Fix xpath
  hr_personal_equipment_request_tier_validation/models/hr_personal_equipment_request.py
Labels: approved, bot is merging ⏳
