Repository OCA/hr, pull requests merged in 2025-03, with the labels that each got.

#1406 [17.0][MIG] hr_employee_age: Migration to 17.0.
  hr_employee_age/README.rst
  hr_employee_age/__init__.py
  hr_employee_age/__manifest__.py
  hr_employee_age/i18n/ar.po
  hr_employee_age/i18n/cs_CZ.po
  hr_employee_age/i18n/de.po
  hr_employee_age/i18n/es.po
  hr_employee_age/i18n/fi.po
  hr_employee_age/i18n/fr.po
  hr_employee_age/i18n/hr.po
  hr_employee_age/i18n/hr_HR.po
  hr_employee_age/i18n/hr_employee_age.pot
  hr_employee_age/i18n/it.po
  hr_employee_age/i18n/lt.po
  hr_employee_age/i18n/nl_NL.po
  hr_employee_age/i18n/pt_BR.po
  hr_employee_age/i18n/ro.po
  hr_employee_age/i18n/sl.po
  hr_employee_age/models/__init__.py
  hr_employee_age/models/hr_employee.py
  hr_employee_age/pyproject.toml
  hr_employee_age/readme/CONTRIBUTORS.md
  hr_employee_age/readme/DESCRIPTION.md
  hr_employee_age/readme/USAGE.md
  hr_employee_age/static/description/icon.png
  hr_employee_age/static/description/index.html
  hr_employee_age/tests/__init__.py
  hr_employee_age/tests/test_hr_employee.py
  hr_employee_age/views/hr_employee.xml
Labels: approved, ready to merge, bot is merging ⏳

#1451 [16.0][IMP] hr_job_category: some warnings
  hr_job_category/tests/test_hr_job_categories.py
Labels: bot is merging ⏳

#1452 [17.0][REM] Remove hr_holidays_settings module (moved to OCA/hr-holidays)
  hr_holidays_settings/README.rst
  hr_holidays_settings/__init__.py
  hr_holidays_settings/__manifest__.py
  hr_holidays_settings/i18n/ar.po
  hr_holidays_settings/i18n/de.po
  hr_holidays_settings/i18n/es.po
  hr_holidays_settings/i18n/fa.po
  hr_holidays_settings/i18n/fi.po
  hr_holidays_settings/i18n/fr.po
  hr_holidays_settings/i18n/hr.po
  hr_holidays_settings/i18n/hr_HR.po
  hr_holidays_settings/i18n/hr_holidays_settings.pot
  hr_holidays_settings/i18n/it.po
  hr_holidays_settings/i18n/nl_NL.po
  hr_holidays_settings/i18n/pt_BR.po
  hr_holidays_settings/i18n/ro.po
  hr_holidays_settings/i18n/sl.po
  hr_holidays_settings/pyproject.toml
  hr_holidays_settings/readme/CONTRIBUTORS.md
  hr_holidays_settings/readme/DESCRIPTION.md
  hr_holidays_settings/readme/USAGE.md
  hr_holidays_settings/static/description/icon.png
  hr_holidays_settings/static/description/index.html
  hr_holidays_settings/views/res_config_settings.xml
Labels: approved, bot is merging ⏳

#1446 [IMP] hr_contract_employee_calendar_planning: multicreate warning
  hr_contract_employee_calendar_planning/models/contract.py
Labels: approved, bot is merging ⏳

#1448 [18.0][MIG] hr_employee_age: Migration to 18.0
  hr_employee_age/README.rst
  hr_employee_age/__init__.py
  hr_employee_age/__manifest__.py
  hr_employee_age/i18n/ar.po
  hr_employee_age/i18n/cs_CZ.po
  hr_employee_age/i18n/de.po
  hr_employee_age/i18n/es.po
  hr_employee_age/i18n/fi.po
  hr_employee_age/i18n/fr.po
  hr_employee_age/i18n/hr.po
  hr_employee_age/i18n/hr_HR.po
  hr_employee_age/i18n/hr_employee_age.pot
  hr_employee_age/i18n/it.po
  hr_employee_age/i18n/lt.po
  hr_employee_age/i18n/nl_NL.po
  hr_employee_age/i18n/pt_BR.po
  hr_employee_age/i18n/ro.po
  hr_employee_age/i18n/sl.po
  hr_employee_age/models/__init__.py
  hr_employee_age/models/hr_employee.py
  hr_employee_age/pyproject.toml
  hr_employee_age/readme/CONTRIBUTORS.md
  hr_employee_age/readme/DESCRIPTION.md
  hr_employee_age/readme/USAGE.md
  hr_employee_age/static/description/icon.png
  hr_employee_age/static/description/index.html
  hr_employee_age/tests/__init__.py
  hr_employee_age/tests/test_hr_employee.py
  hr_employee_age/views/hr_employee.xml
Labels: approved, bot is merging ⏳

#1285 [16.0][MIG] hr_contract_multi_job: Migration to 16.0
  hr_contract_multi_job/README.rst
  hr_contract_multi_job/__init__.py
  hr_contract_multi_job/__manifest__.py
  hr_contract_multi_job/i18n/ar.po
  hr_contract_multi_job/i18n/de.po
  hr_contract_multi_job/i18n/es.po
  hr_contract_multi_job/i18n/fi.po
  hr_contract_multi_job/i18n/fr.po
  hr_contract_multi_job/i18n/hr_contract_multi_job.pot
  hr_contract_multi_job/i18n/it.po
  hr_contract_multi_job/i18n/pt_BR.po
  hr_contract_multi_job/i18n/ro.po
  hr_contract_multi_job/i18n/sl.po
  hr_contract_multi_job/models/__init__.py
  hr_contract_multi_job/models/hr_contract.py
  hr_contract_multi_job/models/hr_contract_job.py
  hr_contract_multi_job/models/hr_job.py
  hr_contract_multi_job/readme/CONTRIBUTORS.rst
  hr_contract_multi_job/readme/DESCRIPTION.rst
  hr_contract_multi_job/readme/USAGE.rst
  hr_contract_multi_job/security/ir.model.access.csv
  hr_contract_multi_job/static/description/icon.png
  hr_contract_multi_job/static/description/index.html
  hr_contract_multi_job/tests/__init__.py
  hr_contract_multi_job/tests/test_hr_contract_multi_jobs.py
  hr_contract_multi_job/views/hr_contract_view.xml
  setup/hr_contract_multi_job/odoo/addons/hr_contract_multi_job
  setup/hr_contract_multi_job/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1369 [17.0][FIX] hr_employee_firstname: removed useless mapped address_home_id
  hr_employee_firstname/models/hr_employee.py
Labels: bot is merging ⏳

#1370 [17.0][FIX] hr_employee_second_lastname: removed useless mapped address_home_id
  hr_employee_second_lastname/models/hr_employee.py
Labels: bot is merging ⏳
