Repository OCA/hr, pull requests merged in 2025-06, with the labels that each got.

#1466 [18.0] [MIG] hr_employee_id: Migration to 18.0
  hr_employee_id/README.rst
  hr_employee_id/__init__.py
  hr_employee_id/__manifest__.py
  hr_employee_id/data/hr_employee_sequence.xml
  hr_employee_id/i18n/ar.po
  hr_employee_id/i18n/cs_CZ.po
  hr_employee_id/i18n/de.po
  hr_employee_id/i18n/es.po
  hr_employee_id/i18n/fi.po
  hr_employee_id/i18n/fr.po
  hr_employee_id/i18n/hr.po
  hr_employee_id/i18n/hr_HR.po
  hr_employee_id/i18n/hr_employee_id.pot
  hr_employee_id/i18n/it.po
  hr_employee_id/i18n/lt.po
  hr_employee_id/i18n/nl_NL.po
  hr_employee_id/i18n/pt_BR.po
  hr_employee_id/i18n/ro.po
  hr_employee_id/i18n/sl.po
  hr_employee_id/models/__init__.py
  hr_employee_id/models/hr_employee.py
  hr_employee_id/models/res_company.py
  hr_employee_id/models/res_config_settings.py
  hr_employee_id/pyproject.toml
  hr_employee_id/readme/CONFIGURE.md
  hr_employee_id/readme/CONTRIBUTORS.md
  hr_employee_id/readme/DESCRIPTION.md
  hr_employee_id/readme/INSTALL.md
  hr_employee_id/readme/ROADMAP.md
  hr_employee_id/readme/USAGE.md
  hr_employee_id/static/description/icon.png
  hr_employee_id/static/description/index.html
  hr_employee_id/tests/__init__.py
  hr_employee_id/tests/test_employee_id.py
  hr_employee_id/views/hr_employee_views.xml
  hr_employee_id/views/res_config_settings_views.xml
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#1481 [17.0][FIX] hr_employee_medical_examination: Use _for_xml_id() to avoid access errors
  hr_employee_medical_examination/wizards/wizard_generate_medical_examination.py
Labels: bot is merging ⏳

#1482 [18.0][FIX] hr_employee_medical_examination: Use _for_xml_id() to avoid access errors
  hr_employee_medical_examination/wizards/wizard_generate_medical_examination.py
Labels: bot is merging ⏳

#1477 [17.0[[MIG] hr_employee_language: Migration to 17.0
  hr_employee_language/README.rst
  hr_employee_language/__init__.py
  hr_employee_language/__manifest__.py
  hr_employee_language/i18n/hr_employee_language.pot
  hr_employee_language/i18n/it.po
  hr_employee_language/models/__init__.py
  hr_employee_language/models/hr_employee.py
  hr_employee_language/models/hr_employee_language.py
  hr_employee_language/pyproject.toml
  hr_employee_language/readme/CONTRIBUTORS.md
  hr_employee_language/readme/DESCRIPTION.md
  hr_employee_language/readme/USAGE.md
  hr_employee_language/security/ir.model.access.csv
  hr_employee_language/static/description/icon.png
  hr_employee_language/static/description/index.html
  hr_employee_language/views/hr_employee.xml
  hr_employee_language/views/hr_employee_language.xml
Labels: approved, ready to merge, bot is merging ⏳

#1478 [18.0[MIG] hr_employee_language: Migration to 18.0
  hr_employee_language/README.rst
  hr_employee_language/__init__.py
  hr_employee_language/__manifest__.py
  hr_employee_language/i18n/hr_employee_language.pot
  hr_employee_language/i18n/it.po
  hr_employee_language/models/__init__.py
  hr_employee_language/models/hr_employee.py
  hr_employee_language/models/hr_employee_language.py
  hr_employee_language/pyproject.toml
  hr_employee_language/readme/CONTRIBUTORS.md
  hr_employee_language/readme/DESCRIPTION.md
  hr_employee_language/readme/USAGE.md
  hr_employee_language/security/ir.model.access.csv
  hr_employee_language/static/description/icon.png
  hr_employee_language/static/description/index.html
  hr_employee_language/views/hr_employee.xml
  hr_employee_language/views/hr_employee_language.xml
Labels: approved, ready to merge, bot is merging ⏳

#1476 [16.0][MIG] hr_employee_language: Migration to 16.0
  hr_employee_language/README.rst
  hr_employee_language/__init__.py
  hr_employee_language/__manifest__.py
  hr_employee_language/i18n/hr_employee_language.pot
  hr_employee_language/i18n/it.po
  hr_employee_language/models/__init__.py
  hr_employee_language/models/hr_employee.py
  hr_employee_language/models/hr_employee_language.py
  hr_employee_language/readme/CONTRIBUTORS.rst
  hr_employee_language/readme/DESCRIPTION.rst
  hr_employee_language/readme/USAGE.rst
  hr_employee_language/security/ir.model.access.csv
  hr_employee_language/static/description/icon.png
  hr_employee_language/static/description/index.html
  hr_employee_language/views/hr_employee.xml
  hr_employee_language/views/hr_employee_language.xml
  setup/hr_employee_language/odoo/addons/hr_employee_language
  setup/hr_employee_language/setup.py
Labels: approved, ready to merge, bot is merging ⏳
